/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * 8mmtape_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray5	m black	c #737373737373",
"O	s iconColor1	m black	c black",
"+	s iconGray7	m black	c #424242424242",
"@	s iconGray6	m black	c #636363636363",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor2	m white	c white",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"      .XXXXXXXXXXXXXXXXXX       ",
"      X..o............o..O      ",
"      X.o+o..........o+o.O      ",
"      X..o............o..O      ",
"      X...o+++@@@@+++o...O      ",
"      X..o+++++..+++++o..O      ",
"      X..++#o#++++#o#++..O      ",
"      X..++o$o++++o$o++..O      ",
"      X..++#o#++++#o#++..O      ",
"      X..o+++++..+++++o..O      ",
"      X...o+++o..o+++o...O      ",
"      X..................O      ",
"       OOOOOOOOOOOOOOOOOO       ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
