/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * Dtcmprs_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray3	m white	c #adadadadadad",
"$	s iconGray1	m white	c #dededededede",
"%	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
" ....................................           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXo           ",
" .XXXXXXXXXXOOOOOOOOOOOOOOXXXXXXXXXXo           ",
" .XXXXXXXXXXXOOOOOOOOOOOOXXXXXXXXXXXo           ",
" .XXXXXXXXXXXX++++++++++XXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXX++++++++XXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXX@@@@@@XXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXooooXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXooXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXoo#ooOooXoo+oXXXXXXXXXXXo           ",
" .XXXOXXXXXXXXXXXXXXXXXXXXXXXXXXOXXXo           ",
" .XXXOOXXXXXXXXXXXXXXXXXXXXXXXXOOXXXo           ",
" .XXXOOOXXXXooo+Xoooo##oXXXXXXOOOXXXo           ",
" .XXXOOO+XXXXXXXXXXXXXXXXXXXX+OOOXXXo           ",
" .XXXOOO++XXXXXXXXXXXXXXXXXX++OOOXXXo           ",
" .XXXOOO++@XXXoooXooOoooXXX@++OOOXXXo           ",
" .XXXOOO++@oXXXXXXXXXXXXXXo@++OOOXXXo           ",
" .XXXOOO++@oXXXXXXXXXXXXXXo@++OOOXXXo           ",
" .XXXOOO++@XXXoOOoooXoooXXX@++OOOXXXo           ",
" .XXXOOO++XXXXXXXXXXXXXXXXXX++OO$$$$$$$$$$$$$$$ ",
" .XXXOOO+XXXXXXXXXXXXXXXXXXXX+OO$%%%%%%%%%%%%%o ",
" .XXXOOOXXXXXXooo#oooOOooXXXXXOO$%%%%%%%%%%%%%o ",
" .XXXOOXXXXXXXXXXXXXXXXXXXXXXXXO$%%%%%%%%%%%%%o ",
" .XXXOXXXXXXXXXXXXXXXXXXXXXXXXXX$%%%%%......o%o ",
" .XXXXXXXXXXooo##ooo#oOooXXXXXXX$%%%%%ooooo.o%o ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$%%%%%%%%%.#o%o ",
" .XXXXXXXXXXXXXXXXooXXXXXXXXXXXX$%%%%%%%%.#o%%o ",
" .XXXXXXXXXXXXXXXooooXXXXXXXXXXX$%%%%%%%.#o%%%o ",
" .XXXXXXXXXXXXXX@@@@@@XXXXXXXXXX$%%%%%%.#o%%%%o ",
" .XXXXXXXXXXXXX@@@@@@@@XXXXXXXXX$%#.o%.#o%%%%%o ",
" .XXXXXXXXXXXX++++++++++XXXXXXXX$%#.o%......o%o ",
" .XXXXXXXXXXX++++++++++++XXXXXXX$%Ooo%ooooooo%o ",
" .XXXXXXXXXXOOOOOOOOOOOOOOXXXXXX$%%%%%%%%%%%%%o ",
" .XXXXXXXXXOOOOOOOOOOOOOOOOXXXXX$%%%%%%%%%%%%%o ",
" .XXXXXXXXOOOOOOOOOOOOOOOOOOXXXX$oooooooooooooo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX++++           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .ooooooooooooooooooooooooooooooooooo           ",
"                                                "};
