/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * devallmgr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray7	m black	c #424242424242",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray5	m black	c #737373737373",
"#	s iconColor6	m white	c yellow",
"$	s iconColor4	m white	c green",
"%	s iconColor7	m white	c cyan",
"&	s iconGray8	m black	c #212121212121",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor1	m black	c black",
"-	s iconColor3	m black	c red",
/* pixels */
"                                                ",
" ..............................................X",
" ..........      o.............................X",
" .......   OOO.OOOO+@..........................X",
" .....  OO. OO OO O.O+X.........+@.............X",
" ....  O#.  OOOOOOOO.OoX......++OO+@...........X",
" ...  OO#$.  OOOOOO.oo@+...+++OOOOOO++@...@+@..X",
" ... O % O$. OO OOO.++O++++OOOOo++oOOO.+++.O&..X",
" .. O%+O%O#*o OOOO..+oOOOOOOOo@+oo+@oOOOOOOO@..X",
" .. OOO@O% #*. OO.%.++O.+@+@+@oooooo@+@+@+.O&..X",
" . O#OO%@O% #@@@@% .+oO.@o+o+oo....oo+o+o@.O@..X",
" . OO##OO@O%@OO .@..++O.++oooo......oooo++.O&..X",
" .OO %%@oo#@ O   O@o+oO.@ooo..O..O.O..ooo@.O@..X",
" .OOO OO%%@O  @@ OOo++O.++oo...OOOO...oo++.O&..X",
" .OO.O.O.O@OO@..@OOo+oO.@ooo.O.O.O.O..ooo@.O@..X",
" .+.o.oo.oXoo*..*ooo++O.++o....OOOO....o++.O&..X",
" .@O+XXXXXXXXXXXXXXXXoO.@ooo.O.OO.O.O.ooo@.O@..X",
" .@.+XO*+OOOOOOOOOOO.+O.++oo...OOOO...oo++.O&..X",
" .XO+=+X@ooooooooooo+oO.@ooo..OO.O.O..ooo@.O@..X",
" .Xo+XO+oooooooooooo++O.++oo...OOOO...oo++.O&..X",
" ..X+Xooo@*XXXX@@@@@*oO.@ooo....O.O...ooo@.O@..X",
" o.X+Xoo@XXXXXX@ooo@*+O.++oo.....O.O..oo++.O=.oX",
" ..oXXo@XXXXXXXX@oo@*+.O+ooo..O.O.....ooo+O+@o.X",
" ooooXoXXXX&&&XXX+o@*XoO.++o.o......o.o++.O@+ooX",
" ooooX+XXX&*o*&XX@o@XX+.O.@oo........oo@.O@@oooX",
" ooooX@XXX&o o&XX*o*XX&+OO.++oo....oo++.OO@ooooX",
" ooooX+XXX&*o*&XX@o@XX&&+OO.@oooooooo@.OOXoooooX",
" ooooXo*XXX&&&XXX+o+XXX&&+OO.++oooo++.OO@ooooooX",
" ooooXo+XXXXXXXX@ooo@XXXX&+OO.@o++o@.OOXoooooooX",
" +oooXoo+XXXXXX@ooooo@XXXX&+OOO.++.OOO@oo+ooo+oX",
" oo+oX==================*@o&++OOOOOO+*===oo+oooX",
" o=o+=-O-O-O-O-O-O-O-O-O=XXX&&+@OO@==O-O=o+o+o+X",
" = ==-O-O-O-+-+-+-+-+-+-=&X&XX==@-O-O-O-=+o+o+oX",
"    =O-O-O-+=============X&===-O-O-O-O-=+++++++X",
"     =O-O-O-+-+-+-+-+-+-&&=-O-O-O-O-O==++++++++X",
" =    =O-O-O-+-+-+-+-+-O-O-O-O-O-O-X=X+++++++++X",
" +=    =O-O-O-O-O-O-O-O-O-O-O-O-X===+++++++@+++X",
" ++=    =+-+-+-+-+-+-+-+-+-+-====XX++++++++++++X",
" @++=    =+-+-+-+-+-+-+-+-+XXXXXX@+++@+++@+++@+X",
" ++@+=    ===================X+@+++@+++@+++@+++X",
" +@+@+=    ===XXXXXXXXXXXXXX@+@+@+@+@+@+@+@+@+@X",
" @+@+@+=    =X=@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+X",
" @@@@@@@=    ==X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" @@@@@@@@=  #-=X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" @@@@@@@@@= #-=X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" @@@@@@@@@@=- =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" @@@@@@@@@@@==X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
