/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * devallmgr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray7	m black	c #424242424242",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray5	m black	c #737373737373",
"@	s iconColor6	m white	c yellow",
"#	s iconColor4	m white	c green",
"$	s iconColor7	m white	c cyan",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray8	m black	c #212121212121",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor1	m black	c black",
"-	s iconColor3	m black	c red",
/* pixels */
"                                ",
" ..............................X",
" .......     o.................X",
" ..... OO.O.O. +...............X",
" .... .OOOOOO  @+..............X",
" ...   #OOOO  @Oo+.............X",
" ...O$  #OOO @OOo%....X........X",
" .. .O$  #O @OO.oo+..X%X.......X",
" .. OOO$  ++OOo.&X%**OOO**%X&..X",
" .. .OOO$+..+.o%&OOOOo+oOOOO&..X",
" .. .o.o.+..+o.%&.+++%o%+++.&..X",
" ...ooo.oo++o.o%&O+%o.O.%%+O&..X",
" ..%o.XXXXXXXXXX&.+%%.Oo.++.&..X",
" ..+ooXOOOOOOOo%&O+%o.oO%o+O&o.X",
" o..XoXOooooooo%&.+%.oO..++.&..X",
" .o..XX.+X*X*X*X&O+%%..oo%+O&.oX",
" o.o.oX%X=X%oo%X=.+%%o.o%++.Xo.X",
" oooooX+=O=+oo+=OXO+%%o%%+OXoooX",
" oooooX%X=X%oo%X=&XO+%+%+OXooooX",
" ooo%oXo%+%oooo%++%XO+++OXo%oooX",
" o%oooXoooooooooooo%XO.OXoooo%oX",
" %o%o==========XXXXX==X-%o%o%o%X",
" o=o=O-O-O-O-O-=.===-.-===o%o%oX",
" = =O-O-.-=====+=-O-o-==X*%%%%%X",
"    =O-O-O-O-O-O-O-o===*%%%%%%%X",
" =   =%-%-%-%-%-%===+%%+%%%+%%%X",
" %=   ============X*%+%%%+%%%+%X",
" +%=   X=XXXXX=X=*+%+%+%+%+%+%+X",
" %+%= @-=X%+%+%+%+%+%+%+%+%+%+%X",
" ++++=- =X+++++++++++++++++++++X",
" +++++==X++++++++++++++++++++++X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
