/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * Dtmagtp_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray6	m black	c #636363636363",
"#	s iconGray4	m white	c #949494949494",
"$	s iconColor1	m black	c black",
/* pixels */
"                                                ",
" ....................................           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXo           ",
" .XXXXO++++++++++++++++++++++Oo@XXXXo           ",
" .XXXXO++++++++++++++++++++++Oo@XXXXo           ",
" .XXXXO++++++++++++++++++++++Oo@XXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOo@XXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOo@XXXXo           ",
" .XXXXOOOO@@@@@@@@@@@@@@@@OOOOo@XXXXo           ",
" .XXXXOOO@@#XX#@@@@@@#XX#@@OOOo@XXXXo           ",
" .XXXXOOO@#XXXX#@@@@#XXXX#@OOOo@XXXXo           ",
" .XXXXOOO@XX$$XX@@@@XX$$XX@OOOo@XXXXo           ",
" .XXXXOOO@XX$$XX@@@@XX$$XX@OOOo@XXXXo           ",
" .XXXXOOO@#XXXX#@@@@#XXXX#@OOOo@XXXXo           ",
" .XXXXOOO@@#XX#@@@@@@#XX#@@OOOo@XXXXo           ",
" .XXXXOOOO@@@@@@@@@@@@@@@@OOOOo@XXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOo@XXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOo@XXXXo           ",
" .XXXXOOOOOOOOOOOOOOOOOOOOOOOOo@XXXXo           ",
" .XXXXXoooooooooooooooooooooooo@XXXXo           ",
" .XXXXX@@@@@@@@@@@@@@@@@@@@@@@@@XXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo           ",
" .ooooooooooooooooooooooooooooooooooo           ",
"                                                "};
