/* XPM */
static char * DtMail_t_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"16 16 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray6     m black c #636363636363",
"o	s iconColor2	m white	c white",
"O    s iconGray5     m black c #737373737373",
"+	s iconColor3	m black	c red",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray3     m white c #adadadadadad",
"$    s iconGray4     m white c #949494949494",
"%    s iconGray7     m black c #424242424242",
/* pixels */
"                ",
"                ",
"                ",
"                ",
"   ..........   ",
"  XXXXXXXXXXXX  ",
" oooooooooooooO ",
" o............O ",
" o.OO.....+++.O ",
" o............O ",
"oooo..OOOO......",
"o.@#X......o$$X%",
"o.@#$oooooo$$$X%",
"o.@#$$$$$$$$$$X%",
"o.@#$$$$$$$$$$X%",
"XXXXXXXXXXXXXXX%"};
     m black",
"6 s iconColor4 c green     m white",
"8 s iconColor5 c blue      m black",
"2 s iconColor6 c yellow    m white",
": s iconColor7 c cyan      m white",
"0 s iconColor8 c magenta   m black",
"< s iconGray1 c #e1e1e1e1e1e1  m white",
"> s iconGray2 c #c8c8c8c8c8c8  m white",
"@ s iconGray3 c #afafafafafaf  m white",
"B s iconGray4 c #969696969696  m white",
"D s iconGray5 c #7d7d7d7d7d7d  m black",
"F s iconGray6 c #646464646464  m black",
"H s iconGray7 c #4b4b4b4b4b4b  m black",
"J s iconGray8 c #323232323232  m black",
/* pixels */
"                ",
"                ",
"                ",
"                ",
"                ",
" ,,,,,,,,,,,,,, ",
" ,BJ<<<<<<<8F<. ",
" ,<<<<B<<<<F8<. ",
" ,<<<J<J<B<<<<. ",
" ,<<<<B<B<<<<<. ",
" ,<<<<<<<<<<<<. ",
" ,............. ",
"                ",
"                ",
"                ",
"                "
};
