/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * pcmcia_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray7	m black	c #424242424242",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"  .............................X",
" ..ooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooO",
".+.oo........................ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@#ooO",
".o.oo.#######################ooO",
".+.ooooooooooooooooooooooooooooO",
".+.ooooooooooooooooooooooooooooO",
".o$OOOOOOOOOOOOOOOOOOOOOOOOOOOO$",
".$OOOOOOOOOOOOOOOOOOOOOOOOOOOO$ ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
