/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * scanner_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor2	m white	c white",
"o	s iconGray4	m white	c #949494949494",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray5	m black	c #737373737373",
"$	s iconColor4	m white	c green",
"%	s iconColor3	m black	c red",
/* pixels */
"                                ",
"                                ",
"                       .X.o     ",
"                     .X.o       ",
"                   .X.o         ",
"                 .X.o           ",
"               .X.o             ",
"             .X.o               ",
"           .X.o                 ",
"         .X.o                   ",
"       .X.o                     ",
"     .X.o                       ",
"   .X.o                         ",
" .X.o                           ",
"..o                             ",
".ooOoOoOO.O.O..O..O............ ",
".oooooooooooooooooooooooooooooo+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".##############################+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@$$@@%%@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o+",
".oooooooooooooooooooooooooooooo+",
"@++++++++++++++++++++++++++++++ ",
"                                ",
"                                "};
