/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * Startup_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconColor5	m black	c blue",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray7	m black	c #424242424242",
"@	s iconColor2	m white	c white",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor1	m black	c black",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"   .........                    ",
"  .XXXXXXXXX.                   ",
" .XXoXoXoXoXO.                  ",
".XoXOXOXOXOXO+................  ",
".XOXoXoXoXoXO+@@@@@@@@@@@@@@@@. ",
".Xo.###XOXOXO+#################.",
".XO#OOOXoXoXO+XXXX@@XX@@X@@XXXX.",
".Xo#OOXXOXOXO+$$$$$$$$$$$$$$$$$#",
".XO#OXXXoXoXO+XX@@%%@@@@XX@XXX# ",
".Xo#OXXXOXOXO+XX@####@##@@#@X#& ",
".XOXXXXXoXoXO+X@##&&###&##&##&& ",
".XoXOXOXOXOXO####&& &&& && &&&  ",
".XOXoXoXoXoXO#&&&&              ",
" .oXOXOXOXOXO#&                 ",
"  &##########&                  ",
"   &&&&&&&&&&                   ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
