/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * camera_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray5	m black	c #737373737373",
"o	s iconColor2	m white	c white",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray3	m white	c #adadadadadad",
"$	s iconColor7	m white	c cyan",
/* pixels */
"                                ",
"                                ",
"                                ",
"           ...X.X.XXX           ",
"   oOOO+  .+ooo+o+o++X   @++X   ",
"  .oooo+#..+#.#.#...+X.#@ooo+X  ",
" .o...++@X++++++++++++X@++..X+O ",
" ++ooooo+.+++XXXXXX+++X+++++++X ",
" .++++++@++XXo@+@+@XX++@+++++@O ",
" +.@@@@@++.ooOOOOOO++O++@@@@@.X ",
" ++#......oOO+++@@@OO+O#...@..O ",
" +@@#@#@..O++@@@@@@@@O.O##@#.XX ",
" ++@@#@#X.++@@o+@@@@@@.O.##.#.O ",
" +#@#@#..X+@@oo@@@@@+@X.O###.XX ",
" ++@@#@X.+@@@@@@o@@@@$@.X#@.#.O ",
" +@@#@#X.+@o+@@ooo@@@+@.O###.XX ",
" ++@@#@X.+oo@@@@o@@@@+@.X##.#.O ",
" +#@#@#X.@@@@o@@@@@@+$@.O#@#.XX ",
" ++@@#@X.@@@ooo@@@@@+@@.O##.#.O ",
" +@@#@#X.#@@@o@@@@@+$@#.O###.XX ",
" ++@@#@X#X@@+@@@@++@@@X#O#@.#.O ",
" +#@#@#@.#X@@@$++$@@@X+..###.XX ",
" ++@@#@.X.#XX@@@@@@XX+.O###.#.O ",
" ++@#@#@.X.##XXXXXX@+.O..#@#.XO ",
"  .+...XXXXXX##@+@+XXOOX.O.O.O  ",
"             .XXXX.             ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
