/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * addr_mgr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor5	m black	c blue",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray4	m white	c #949494949494",
"#	s bottomShadowColor	m black	c #636363636363",
"$	s iconGray1	m white	c #dededededede",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconGray8	m black	c #212121212121",
"*	s iconColor1	m black	c black",
"=	s iconColor2	m white	c white",
"-	s topShadowColor	m white	c #bdbdbdbdbdbd",
";	s iconColor7	m white	c cyan",
/* pixels */
"                          .........             ",
"             ..........  .XXXXXXXXoO            ",
"            .XXXXXXXXXo..XXXXXXXXXXoO           ",
"           .XXXXXXXXXXXo.XXXXXXXXXXoO           ",
"          .+XXXXXXXXXXXo+XXXXXXXXXXo+O          ",
"          .@XXXXXXXXXXXo@@@@@@@@@@@@@O          ",
"         #.OXoXoXoXoXoXoOOOOOOOOOOOOOO          ",
"         .O$$$$$$$$$$$$$$$$$$$$$$$$$$OO         ",
"         .$$$$$$$$$$$$$$$$$$$$$$$$$$$$O         ",
"         .$$$$$$$$$$$$$$$$$$$$$$$$$$$$O         ",
"         .$$$$$O$$$$$$$$$$$$$$$$$$$$$$O         ",
"         .$$$$oXo$$$$oo@o$$o@@$oooO$$$O         ",
"         .$$$$XoX$$$$$$$$$$$$$$$$$$$$$O         ",
"         .$$$$oXo$$$$$$$$$$$$$$$$$$$$$O         ",
"#....#   .$$OoXoXoO$$oo$@oo$oo@$@@o$$$O   #....#",
".$$$$#   .$$oXoXoXo$$$$$$$$$$$$$$$$$$$O   .$$$$O",
".$$$$.....$$XoXoXoX$$$$$$$$$$$$$$$$$$$O....$$$$O",
".$O$O++$%%$$oXoXoXo$$$$$$$$$$$$$$$$$$$oo$++$O$OO",
".OOOO..O%%$$$$$$$$$$$$$$$$$$$$$$$$$$$$ooO..OOOOO",
".OOOO..O%%$$$$$$$$$$$$$$$$$$$$$$$$$$$$ooO..OOOOO",
".O%O%oo%%%$$$$$$$@&&O$$$$$$@&&O$$$$$$$oo%ooO%O%O",
".@@@@**@@@$$$$$$$+&&%$$$$$$+&&%$$$$$$$oo@&&@@@@O",
".@@@@**@@@$$$$$$$+&&%$$$$$$+&&%$$$$$$$oo@&&@@@@O",
".@+@+&&+oo&&&&&&&&&&&&&&&&&&&&&&&&&&&&oo+&&@+@+O",
".....&&.oo$=$=$=$+&&%=$=$=$+&&%=$=$=$=ooo&&....O",
".....&&ooo=$=$=$=$%++$=$=$=$%++$=$=$=$ooo&&....O",
"..o.o&&ooo$=$=$=$=$O@@$=$=$=$O@@$=$=$=ooo&&.o.oO",
".****&*&&&=$=$=$=$=$$%%$=$=$=$$%%$=$=$oo&&&*oo*O",
".****&*ooo$=$=$=$=$=$=$=$=$=$=$=$=$=$=ooo******O",
".******ooo=$=$=$=$=$=$=$=$=$=$=$=$=$=$ooo******O",
".&oo&O.=@*$=$=$=$=$=$=$=$=$=$=$=$=$=$=@O&OO&oo&O",
".&&&&O.=@*=$=$=$=$=$=$=$=$=$=$=$=$=$=$@O&OO&&&&O",
"#OOOO .=@*$=$=$=$=$=$=$=$=$=$=$=$=$=$=@O&O OOOO-",
"     .;%**=$=$=$=$=$=$=$=$=$=$=$=$=$=$@O.&O     ",
"    .;%&oO%%%%%%%%%%%%%%%%%%%%%%%%%%%%O%$+*O    ",
"    .=%&O .@@@@@@@@@@@@@@@@@@@@@@@@@@O .=+*O    ",
"    .=%&O  ++++++++++++++++++++++++++O .=+*O    ",
"    .=%&O  .........................O  .=+&O    ",
"    .=%&O   OOOOOOOOOOOOOOOOOOOOOOOO   .=+&O    ",
"    .=%&O                              .=+&O    ",
"    .=%&O                              .=+&O    ",
"    .=%&O                              .=+&O    ",
"    .=%&O                              .=+&O    ",
"    .=%&................................=+&O    ",
"    .$$+@$==============================;+oO    ",
"     .$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%oO     ",
"      ..&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&oO      ",
"       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO       "};
