/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * Dtcmprs_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s bottomShadowColor	m black	c #636363636363",
".	s iconGray6	m black	c #636363636363",
"X	s none	m none	c none",
"o	s iconColor2	m white	c white",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor5	m black	c blue",
/* pixels */
" .....................................XXXXXXXXXX",
".ooooooooooooooooooooooooooooooooooooOXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOO@@@@@@@@@@@@@@@@OOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOO@@@@@@@@@@@@@@OOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOO@@@@@@@@@@@@OOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOO..........OOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOO........OOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOO######OOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOO++++OOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOO++OOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOO++$++@++O++.+OOOOOOOOOOO+OXXXXXXXXXX",
".oOOO@OOOOOOOOOOOOOOOOOOOOOOOOOO@OOO+OXXXXXXXXXX",
".oOOO@@OOOOOOOOOOOOOOOOOOOOOOOO@@OOO+OXXXXXXXXXX",
".oOOO@@@OOOO+++.O++++$$+OOOOOO@@@OOO+OXXXXXXXXXX",
".oOOO@@@.OOOOOOOOOOOOOOOOOOOO.@@@OOO+OXXXXXXXXXX",
".oOOO@@@..OOOOOOOOOOOOOOOOOO..@@@OOO+OXXXXXXXXXX",
".oOOO@@@..#OOO+++O++@+++OOO#..@@@OOO+OXXXXXXXXXX",
".oOOO@@@..#+OOOOOOOOOOOOOO+#..@@@OOO+OXXXXXXXXXX",
".oOOO@@@..#+OOOOOOOOOOOOOO+#..@@@OOO+OXXXXXXXXXX",
".oOOO@@@..#OOO+@@+++O+++OOO#..@@@OOO+O.........X",
".oOOO@@@..OOOOOOOOOOOOOOOOOO..@@%%%%%%%%%%%%%%%O",
".oOOO@@@.OOOOOOOOOOOOOOOOOOOO.@@%&&&&&&&&&&&&&+O",
".oOOO@@@OOOOOO+++$+++@@++OOOOO@@%&&&&&&&&&&&&&+O",
".oOOO@@OOOOOOOOOOOOOOOOOOOOOOOO@%&&&&&&&&&&&&&+O",
".oOOO@OOOOOOOOOOOOOOOOOOOOOOOOOO%&&&&&oooooo+&+O",
".oOOOOOOOOOO+++$$+++$+@++OOOOOOO%&&&&&+++++o+&+O",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&o$+&+O",
".oOOOOOOOOOOOOOOOO++OOOOOOOOOOOO%&&&&&&&&o$+&&+O",
".oOOOOOOOOOOOOOOO++++OOOOOOOOOOO%&&&&&&&o$+&&&+O",
".oOOOOOOOOOOOOOO######OOOOOOOOOO%&&&&&&o$+&&&&+O",
".oOOOOOOOOOOOOO########OOOOOOOOO%&$o+&o$+&&&&&+O",
".oOOOOOOOOOOOO..........OOOOOOOO%&$o+&oooooo+&+O",
".oOOOOOOOOOOO............OOOOOOO%&@++&+++++++&+O",
".oOOOOOOOOOO@@@@@@@@@@@@@@OOOOOO%&&&&&&&&&&&&&+O",
".oOOOOOOOOO@@@@@@@@@@@@@@@@OOOOO%&&&&&&&&&&&&&+O",
".oOOOOOOOO@@@@@@@@@@@@@@@@@@OOOO%++++++++++++++O",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO....OOOOOOOOOOX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".o+++++++++++++++++++++++++++++++++++OXXXXXXXXXX",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXX"};
