/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * edevallmgr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s bottomShadowColor	m black	c #636363636363",
".	s iconColor2	m white	c white",
"X	s topShadowColor	m white	c #bdbdbdbdbdbd",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray7	m black	c #424242424242",
"&	s iconColor6	m white	c yellow",
"*	s iconColor4	m white	c green",
"=	s iconColor7	m white	c cyan",
"-	s iconGray8	m black	c #212121212121",
";	s iconGray6	m black	c #636363636363",
":	s iconColor3	m black	c red",
/* pixels */
"                                                ",
" ..............................................X",
" .ooooooooo......Ooooooooooooooooooooooooooooo+X",
" .oooooo...@@@o@@@@#$ooooooooooooooooooooooooo+X",
" .oooo..@@o.@@.@@.@o@#%ooooooooo#$oooooooooooo+X",
" .ooo..@&o..@@@@@@@@o@O%oooooo##@@#$oooooooooo+X",
" .oo..@@&*o..@@@@@@oOO$#ooo###@@@@@@##$ooo$#$o+X",
" .oo.@.=.@*o.@@.@@@o##@####@@@@O##O@@@o###o@-o+X",
" .o.@=#@=@&;O.@@@@oo#O@@@@@@@O$#OO#$O@@@@@@@$o+X",
" .o.@@@$@=.&;o.@@o=o##@o#$#$#$OOOOOO$#$#$#o@-o+X",
" ..@&@@=$@=.&$$$$=.o#O@o$O#O#OOooooOO#O#O$o@$o+X",
" ..@@&&@@$@=$@@.o$oo##@o##OOOOooooooOOOO##o@-o+X",
" .@@.==$OO&$.@...@$O#O@o$OOOoo@oo@o@ooOOO$o@$o+X",
" .@@@.@@==$@..$$.@@O##@o##OOooo@@@@oooOO##o@-o+X",
" .@@o@o@o@$@@$oo$@@O#O@o$OOOo@o@o@o@ooOOO$o@$o+X",
" .#oOoOOoO%OO;oo;OOO##@o##Ooooo@@@@ooooO##o@-o+X",
" .$@#%%%%%%%%%%%%%%%%O@o$OOOo@o@@o@o@oOOO$o@$o+X",
" .$o#%@;#@@@@@@@@@@@o#@o##OOooo@@@@oooOO##o@-o+X",
" .%@#+#%$OOOOOOOOOOO#O@o$OOOoo@@o@o@ooOOO$o@$o+X",
" .%O#%@#OOOOOOOOOOOO##@o##OOooo@@@@oooOO##o@-o+X",
" .o%#%OOO$;%%%%$$$$$;O@o$OOOoooo@o@oooOOO$o@$o+X",
" .o%#%OO$%%%%%%$OOO$;#@o##OOooooo@o@ooOO##o@+o+X",
" .oO%%O$%%%%%%%%$OO$;#o@#OOOoo@o@oooooOOO#@#$O+X",
" .OOO%O%%%%---%%%#O$;%O@o##OoOooooooOoO##o@$#O+X",
" .OOO%#%%%-;O;-%%$O$%%#o@o$OOooooooooOO$o@$$OO+X",
" .OOO%$%%%-O.O-%%;O;%%-#@@o##OOooooOO##o@@$OOO+X",
" .OOO%#%%%-;O;-%%$O$%%--#@@o$OOOOOOOO$o@@%OOOO+X",
" .OOO%O;%%%---%%%#O#%%%--#@@o##OOOO##o@@$OOOOO+X",
" .OOO%O#%%%%%%%%$OOO$%%%%-#@@o$O##O$o@@%OOOOOO+X",
" .OOO%OO#%%%%%%$OOOOO$%%%%-#@@@o##o@@@$OO#OOO#+X",
" .O#O%++++++++++++++++++;$O-##@@@@@@#;+++OO#OO+X",
" .+O#+:@:@:@:@:@:@:@:@:@+%%%--#$@@$++@:@+O#O#O+X",
" ..++:@:@:@:#:#:#:#:#:#:+-%-%%++$:@:@:@:+#O#O#+X",
" ...+@:@:@:#+++++++++++++%-+++:@:@:@:@:+######+X",
" ....+@:@:@:#:#:#:#:#:#:--+:@:@:@:@:@++#######+X",
" .....+@:@:@:#:#:#:#:#:@:@:@:@:@:@:%+%########+X",
" .+....+@:@:@:@:@:@:@:@:@:@:@:@:%+++#######$##+X",
" .#+....+#:#:#:#:#:#:#:#:#:#:++++%%###########+X",
" .##+....+#:#:#:#:#:#:#:#:#%%%%%%$###$###$###$+X",
" .#$#+....+++++++++++++++++++%#$###$###$###$##+X",
" .$#$#+....+++%%%%%%%%%%%%%%$#$#$#$#$#$#$#$#$#+X",
" .#$#$#+....+%+$#$#$#$#$#$#$#$#$#$#$#$#$#$#$#$+X",
" .$$$$$$+....++%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+X",
" .$$$$$$$+..&:+%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+X",
" .$$$$$$$$+.&:+%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+X",
" .$$$$$$$$$+:.+%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+X",
" .+++++++++++++++++++++++++++++++++++++++++++++X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
