/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * error_log_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s bottomShadowColor	m black	c #636363636363",
".	s iconGray6	m black	c #636363636363",
"X	s none	m none	c none",
"o	s iconColor2	m white	c white",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconColor1	m black	c black",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray7	m black	c #424242424242",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor3	m black	c red",
"*	s iconGray4	m white	c #949494949494",
"=	s iconGray3	m white	c #adadadadadad",
/* pixels */
" .................................... XXXXXXXXXX",
".ooooooooooooooooooooooooooooooooooooOXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOO++@##$O$$$OO$$$OOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOO+$$O$++#$$O$$OOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOO+$$O$$$O++O$$$OOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOO%%%%%%%%%%%%%%%%%%%%%%%X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&&&&&&&&&&&&&+X",
".oOOOOO+$$O+++$O#$$$OOOO%&&&&&&&&&&&&&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo.&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOO$$$O$+++OO$$$$OOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOO$$$O$OO@$$O$$$OOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&%oo%+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&%oo%+&&&&&&&&+X",
".oOOOOO+$$O$#O$$$$OOOOOO%&&&&&&&&OooO+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&oo+&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&++&&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&&&&&&&&&&&&&+X",
".oOOO$$+OO$$$$O+#$$$OOOO%&&&&&&&&&oo.&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&oooo+&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&oo+&&&&&&&&&+X",
".oOOOOO+++O+#O$$$O$$$OOO%&&&&&&&&&++&&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&&&&&&&&&&&&&+X",
".oOOOOOOOOOOOOOOOOOOOOOO%&&&&&&&&&&&&&&&&&&&&&+X",
".oOOOOO$$$O+$$$OO$$$OOOO%++++++++++++++++++++++X",
".oOOOOOOOOOOOOOOOOOOOOOOO***********+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOO===========+OXXXXXXXXXX",
".oOOOOO+$$O+#O+++O$$OOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+OXXXXXXXXXX",
".o+++++++++++++++++++++++++++++++++++OXXXXXXXXXX",
" OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXX"};
