/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * find_file_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s bottomShadowColor	m black	c #636363636363",
"+	s iconColor5	m black	c blue",
"@	s iconGray8	m black	c #212121212121",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor7	m white	c cyan",
"*	s iconGray4	m white	c #949494949494",
"=	s iconColor3	m black	c red",
"-	s iconColor6	m white	c yellow",
";	s iconGray7	m black	c #424242424242",
/* pixels */
"                          ................      ",
"                         .XXXXXXXXXXXXXXXXo     ",
"                         .XXXXXXXXXXXXXXXXo     ",
"    O....................XXX++++++++++++@@@ooo  ",
"    .XXXXXXXXXXXXXXXXXXXXX++++++++++++++++@@@o  ",
"    .XXXXXXXXXXXXXXXXXXXXX++++++++++++++++@@@o  ",
" O...XX######################################@o ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooooooooooooooooooooo##@##@o ",
" .Xooooooooooooooooooo@@@@@@oooooooooooo##@##@o ",
" .Xooooooooooooooooo@@o$o$o$@@oooooooooo##@##@o ",
" .Xooooooooooooooo@@%%X%X%XX%%@@oooooooo##@##@o ",
" .Xoooooooooooooo@oo%XXXXXXXX%oo@ooooooo##@##@o ",
" .Xooooooooooooo@ooX%XX&XX&XXX%%o@oooooo##@##@o ",
" .Xooooooooooooo@o%XX&XXXXX&XXXX%@oooooo##@##@o ",
" .Xoooooooooooo@oo%XX%X%%%XX&XXX%$@ooooo##@##@o ",
" .Xoooooooooooo@oo%%%X%%%%%X%XXXXo@ooooo##@##@o ",
" .Xooooooooooo@oo%o%%%%%%%%%X%%XX%o@oooo##@##@o ",
" .Xooooooooooo@oo%%%%%%%%%%%%%XXX%$@oooo##@##@o ",
" .Xooooooooooo@ooo%%%%%%%%%%%XXXX%o@oooo##@##@o ",
" .Xooooooooooo@ooo%%%%%%%%%%%%XX%o$@oooo##@##@o ",
" .Xooooooooooo@oooo%%%%%%%%%%%XX%oo@oooo##@##@o ",
" .Xooooooooooo@ooo%o%%%%%%%%%%%%%o$@oooo##@##@o ",
" .Xoooooooooooo@ooo%o%%%%%%%%%%%oo@ooooo##@##@o ",
" .Xoooooooooooo@ooooo%o%%o%%%%%oo$@ooooo##@##@o ",
" .Xooooooooooooo@ooo%&oo%%o%o%o%$@oooooo##@##@o ",
" .Xooooooooooooo@ooooo&ooo&oooooo@########@##@o ",
" .X##############@ooooo&&oooooo$@%oo*@@@@@@@@@o ",
" .@@@@@@@@@@@@@@@@@@$oooooooo$@@@*@=-*@@@@@@@oo ",
" Ooooooooooooooooooo@@o$o$o$@@oo.@#$=%*ooooooo  ",
"                      @@@@@@    .@;=$=-*        ",
"                                .;@;=$=%*       ",
"                                 .;@;=$=-*      ",
"                                  .;@;=$=%*     ",
"                                   .;@;=$=-*    ",
"                                    .;@;=$=%*   ",
"                                     .;@;=$=-*  ",
"                                      .;@;=$=%* ",
"                                       .;@;=$=# ",
"                                        .;@;=$@ ",
"                                         .;@;;@ ",
"                                          .;@@  ",
"                                                "};
