/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * websearch_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 18 1 0 0",
/* colors */
" 	s bottomShadowColor	m black	c #636363636363",
".	s none	m none	c none",
"X	s iconColor2	m white	c white",
"o	s topShadowColor	m white	c #bdbdbdbdbdbd",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor7	m white	c cyan",
"*	s iconColor1	m black	c black",
"=	s iconColor5	m black	c blue",
"-	s iconColor3	m black	c red",
";	s iconColor6	m white	c yellow",
":	s iconGray6	m black	c #636363636363",
"?	s iconGray7	m black	c #424242424242",
">	s iconColor4	m white	c green",
/* pixels */
"                                        ........",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo........",
" XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o........",
" XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o........",
" XOO@+@OOO@+@+@OOO@+@+@OOO@+@OOOOOOOOO+o........",
" XOOO+OO+OO+O+OO+OO+O+OO+OO+OOOOOOOOOO+o........",
" XOOO+O++O+#O+O++O+#O+O++O+#OOOOOOOOOO+o........",
" XOOO+O++O+OO+O++O+OO+O++O+OOOOOOOOOOO+o........",
" XOOO++#++#OO++#++#OO++#++#OOOOOOOOOOO+o........",
" XOOO++O++OOO++O++OOO++O++OOOOOOOOOOOO+o........",
" XOOO+OO+OOOO+OO+OOOO+OO+OOOOOOOOOOOOO+o........",
" XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o........",
" XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o........",
" XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o........",
" XOOO+++O++OO++++OOOOO++++++OOOOOOOOOO+o........",
" XOOOOOOOOOOOOOOOOOO++O$O$O$++OOOOOOOO+o........",
" XOOOOOOOOOOOOOOOO++%%X%X%XX%%++OOOOOO+o........",
" XOOO++++O+++O+OO+OO%XXXXXXXX%OO+OOOOO+o........",
" XOOOOOOOOOOOOOO+OOX%XX&XX&XXX%%O+OOOO+o........",
" XOOOOOOOOOOOOOO+O%XX&XXXXX&XXXX%+OOOO+o........",
" XOOO+++O+++OOO+OO%XX%X%%%XX&XXX%$+OOO+o........",
" XOOOOOOOOOOOOO+OO%%%X%%%%%X%XXXXO+OOO+o........",
" XOOOOOOOOOOOO+OO%O%%%%%%%%%X%%XX%O+OO+o........",
" XOOO++O++O++O+OO%%%%%%%%%%%%%XXX%$+OO+o........",
" XOOOOOOOOOOOO+OOO%%%%%%%%%%%XXXX%O+OO+o........",
" XOOOOOOOOOOOO+OOO%%%%%%%%%%%%XX%O$+OO+o........",
" XOOO+++O++OOO+OOOO%%%%%%%%%%%XX%OO+OO+o........",
" XOOOOOOOOOOOO+OOO%O%%%%%%%%%%%%%O$+OO+o........",
" XOOOOOOOOOOOOO+OOO%O%%%%%%%%%%%OO+#+O+o........",
" XOOOOOOOOOOOOO+OOOOO%O%%O%%%%%OO$+##++o........",
" XOOOOOOOOOOOOOO+OOO%&OO%%O%O%O%$+####+o........",
" XOOOOOOOOOOOOO*+OOOOO&OOO&OOOOOO+#=##+o........",
" XOOOOOOOOOOOO*O#+OOOOO&&OOOOOO$+%$###+o........",
" XOOOOOOOOOOO*O#OX++$OOOOOOOO$+++#+-;#+o........",
" XOOOOOOOOOOO*##X$XX++O$O$O$++OO:+@$-%#o........",
" XOOOOOOOOOO*O&OXXXXOX++++++&##&:+?-$-;#........",
" XOOOOOOOOOO*#OOOOXXXO&OOOO&O##O:?+?-$-%#.......",
" XOOOOOOOOOO*OOO&XOXOXOOO$>O:OOO$:?+?-$-;#......",
" XOOOOOOOOO:#:$$OO&$$OOO:$$O$$$$O#:?+?-$-%#.....",
" XOOOOOOOOO+#:$$OO&$$OOO$$$$O######:?+?-$-;#....",
" XOOOOOOOOO+###@#$$$$$$$O#######::O#:?+?-$-%#...",
" XOOOOOOOOO+##O###O##O########:#?#=?::?+?-$-;#..",
" XOOOOOOOOO+#############&OO&####::::?:?+?-$-%#.",
" XOOOOOOOOO+#$#&#O#O#:##:#::###:::??=?+:?+?-$-@.",
" XOOOOOOOOO+#####O&##&###:=###?:::??:?+@:?+?-$+.",
" XOOOOOOOOO+:######:###?#&##?#::??????+o@:?+??+.",
" X+++++++++++++++++++++++++++++++++++++o.@:?++..",
" ooooooooooooooooooooooooooooooooooooooo........"};
