/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * host_object_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 17 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #636363636363",
"X	s iconGray6	m black	c #636363636363",
"o	s iconColor2	m white	c white",
"O	s iconGray8	m black	c #212121212121",
"+	s topShadowColor	m white	c #bdbdbdbdbdbd",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray1	m white	c #dededededede",
"&	s iconGray7	m black	c #424242424242",
"*	s iconColor7	m white	c cyan",
"=	s iconGray3	m white	c #adadadadadad",
"-	s iconColor5	m black	c blue",
";	s iconColor8	m black	c magenta",
":	s iconColor4	m white	c green",
"?	s iconColor1	m black	c black",
/* pixels */
"                                                ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"    .XoooooooooooooooooooooooooooooooooooO.+    ",
"    Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@    ",
"    Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@    ",
"    Xo@@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#@@O@    ",
"    Xo@@XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo@@O@    ",
"    Xo@@XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%%%%%%%%%%%%$$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%$$$$$$$$$$%&$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%$$$$$$$$$$%&$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%*o*o*o*o*o%&$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%o*o*o*o*o*%&$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XO$$%*o*o*o*================$$Oo@@O@    ",
"    Xo@@XO$$%o*o*o*o================&$Oo@@O@    ",
"    Xo@@XO$$%*o*o*o*================&$Oo@@O@    ",
"    Xo@@XO$$%%%%%%%%=oooooooooooooo=O$Oo@@O@    ",
"    Xo@@XO$$$&&&&&&&=ooOOoOoOOooooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$=oooooooooooooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$=ooOoOOoOoOoooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$=oooooooooooooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$=ooOOoOOoOooooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$=oooooooooooooo=O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$================O$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$$OOOOOOOOOOOOOOOO$Oo@@O@    ",
"    Xo@@XO$$$$$$$$$$$$$$$$$$$$$$$$$$$$Oo@@O@    ",
"    Xo@@XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo@@O@    ",
"    Xo@@#ooooooooooooooooooooooooooooooo@@O@    ",
"    Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@    ",
"    Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@O@    ",
"    .@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@+    ",
"     .@@@@@@@@@$XXXXXXXXXXXXXXXX@@@@@@@@@@+     ",
"             $$$&&&&&&&&&&&&&&XXXX@             ",
" XXXXXXXXXXXXOOOOOOOOOOOOOOOOOOOOO@XXXXXXXXXX   ",
" Xoooooooooooooooooooooooooooooooooooooooooo=@+ ",
" Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OX@ ",
" Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OX@ ",
" Xo@@@-@@@@$@@@@@@@@@@@@@@@@@@========@@@@@@OX@ ",
" Xo@@-;--@--#-#@@@@@@@@@@@@@@@=X=X=X==@@:=@@OX@ ",
" Xo@@@-@@@@@@@@@@@@@@@@@@@@@@@========@@=#@@OX@ ",
" Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OX@ ",
" Xo@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@OX@ ",
" XoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX@ ",
" .XOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOO?&&$@ ",
"  X&&&&&&&@@@@@@@@@@@@@@@@@@@@@@@@@@&&&&&&&&@@  ",
"  .@@@@@@@                          @@@@@@@@    ",
"                                                "};
