/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * shred_trash_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray4	m white	c #949494949494",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray7	m black	c #424242424242",
"#	s iconColor2	m white	c white",
"$	s iconColor7	m white	c cyan",
"%	s iconColor6	m white	c yellow",
"&	s iconColor1	m black	c black",
"*	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"              ...................XX             ",
"              .oOOOOOOOOOOOOOOO+o..X            ",
"              .OoOOOOOOOOOOOOOOOOOo.X           ",
"              .OXOXXXXXXXXXXXXXXXXO@X           ",
"              .OXOXXXXXXXXXXXXXXXXO@X           ",
"              .@XOXXXXXXXXXXXXXXXXO@X           ",
"              .O@@@@@@@@@@@@@@@@@@@@X           ",
"              .+OXXXXXXXXXXXXXXXXXX@X           ",
"              .o+Xooooooooooooooooo@X           ",
"              .o+Xooooooo#ooooooooo@X           ",
"              .++Xooooooo##oooooooo@X           ",
"              .o+Xooooooo##.ooooooo@X           ",
"              .++Xo#ooooo##.ooooooo@X           ",
"              .o+Xo##oooo##.ooooooo@X           ",
"              .++Xo.$#ooo##.ooooooo@X           ",
"              .o+Xoo.##oo##.ooooooo@X           ",
"              .++Xooo.$#o##.ooooooo@X           ",
"              .o+Xoooo.####.ooooooo@X           ",
"              .++Xooooo.$##.ooooooo@X           ",
"              .o+Xoooooo.##.ooooooo@X           ",
"              .++Xooooooo#$#o%%@ooo@X           ",
"              .o+Xoooooo%%@o%@@%@oo@X           ",
"              .++Xooooo%@@%@%@oo%@o@X           ",
"              .o+Xooooo%@o%@o%oo%@o@X           ",
"              .++Xooooo%@o%@oo%%@oo@X           ",
"              .o+Xooooo%@o%@oo@@ooo@X           ",
"              .++Xoooooo%%@oooooooo@X           ",
"              .o+Xooooooooooooooooo@X           ",
"              .++Xooooooooooooooooo@X           ",
"              .o+Xooooo&&&&&&oooooo@X           ",
"              X&+Xooooo&OOOOOO*oooo@X           ",
"               X&Xooooo&&&&&&**oooo@X           ",
"                X&&&&&&&&&&&&&&&&&&&X           ",
"                 XXXXXXX     XXXXXXXX           ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
