/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * sys_info_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconColor2	m white	c white",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconColor5	m black	c blue",
"#	s iconGray7	m black	c #424242424242",
"$	s iconColor1	m black	c black",
"%	s iconGray5	m black	c #737373737373",
"&	s iconGray4	m white	c #949494949494",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"              ....................              ",
"          ....XXXXXXXXXXXXXXXXXXXX...           ",
"         .oooooooooooooooooooooooooooO          ",
"        .oOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O        ",
"       .oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O       ",
"       .oOO..........................OO+O       ",
"       .oOO.++++++++++++++++++++++++.OO+O       ",
"       .oOO.+@+@+@#@@@@@@@@@@#@+@+@+oOO+O       ",
"       .oOO.++@+@+@@@@@@@@@@@@+@+@++oOO+O       ",
"       .oOO.+@+@+@@@@@oooo$@@@@+@+@+oOO+O       ",
"       .oOO.++@+@@@@@oooooo$@@@@+@++oOO+O       ",
"       .oOO.+@+@+@@@@oo$$oo$@@@+@+@+oOO+O       ",
"       .oOO.++@+@@@@@@$$@oo$@@@@+@++oOO+O       ",
"       .oOO.+@+@@@@@@@@@@oo$@@@@@+@+oOO+O       ",
"       .oOO.++@+@@@@@@@@oo$@@@@@+@++oOO+O       ",
"       .oOO.+@+@@@@@@@@oo$@@@@@@@+@+oOO+O       ",
"       .oOO.++@+@@@@@@@oo$@@@@@@+@++oOO+O       ",
"       .oOO.+@+@+@@@@@@@$$@@@@@+@+@+oOO+O       ",
"       .oOO.++@+@@@@@@@oo@@@@@@@+@++oOO+O       ",
"       .oOO.+@+@+@@@@@@oo$@@@@@+@+@+oOO+O       ",
"       .oOO.++@+@+@@@@@@$$@@@@+@+@++oOO+O       ",
"       .oOO.+@+@+@#@@@@@@@@@@#@+@+@+oOO+O       ",
"       .oOO.++++++++++++++++++++++++oOO+O       ",
"       .oOO.oooooooooooooooooooooooooOO+O       ",
"       .oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O       ",
"        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+O        ",
"         O++++++++++++++++++++++++++++O         ",
"          OOOO####################+OOO          ",
"              O++...............++O             ",
"               O++%%%%%%%%%%%%+++O              ",
"      ..........++%%%%%%%%%%%%+++O........O     ",
"     .&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+O    ",
"    .ooooo%oo%oo%oo%oo%oo%oo%oo%ooo%o%o%ooo+O   ",
"   .ooooo%oo%oo%oo%oo%oo%oo%oo%oooo%oo%o%ooo+O  ",
"  .ooooo%oo%ooooooooooooooooo%oo%oo%o%o%o%ooo+O ",
" .oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+O",
".ooXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+",
".o&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+",
".o#############################################+",
" O+++++++++++++++++++++++++++++++++++++++++++++O",
"  OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
