/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * Fpurlweb_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s topShadowColor	m white	c #bdbdbdbdbdbd",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor5	m black	c blue",
"&	s iconGray6	m black	c #636363636363",
"*	s iconColor1	m black	c black",
"=	s iconColor7	m white	c cyan",
"-	s iconColor4	m white	c green",
";	s iconGray3	m white	c #adadadadadad",
/* pixels */
"        ........................................",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOO@+@OOO@+@+@OOO@+@+@OOO@+@OOOOOOOOO+o",
"        .XOOO+OO+OO+O+OO+OO+O+OO+OO+OOOOOOOOOO+o",
"        .XOOO+O++O+#O+O++O+#O+O++O+#OOOOOOOOOO+o",
"        .XOOO+O++O+OO+O++O+OO+O++O+OOOOOOOOOOO+o",
"        .XOOO++#++#OO++#++#OO++#++#OOOOOOOOOOO+o",
"        .XOOO++O++OOO++O++OOO++O++OOOOOOOOOOOO+o",
"        .XOOO+OO+OOOO+OO+OOOO+OO+OOOOOOOOOOOOO+o",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOO$OO%@O%%%@O%%%%OOOOOOOOOOOOOOO+o",
"        .XOOOOOO%$OOOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOO$%$OOOOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOO%$%$OOO&&&O&&&&O&&&&&OOOOOOOOO+o",
"        .XOOOOOO$%$%$OOOOOOOOOOOOOOOOOOOOOOOOO+o",
"        .XOOOOOO%$%$%$OOOOOOOOOOOOOOOOOOOOOOOO+o",
"      %%$%$%$%$%$%$%$%$OOOOOOOOOOOOOOOOOOOOOOO+o",
"    %$%$%$%$%$%$%$%$%$%$OO&&&&O&&O&&&OOOOOOOOO+o",
"   %$%$%$%$%$%$%$%$%$%$%$OOOOOOOOOOOOOOOOOOOOO+o",
"  %$%$%$%$%$%$%$%$%$%$%$OOOOOOOOOOOOOOOOOOOOOO+o",
"  $%$%$%$%$%$%$%$%$%$%$OO&&&O&&OOOOOOOOOOOOOOO+o",
" $%$%$%$%$#OOOOO%$%$%$OOOOOOOOOOOOOOOOOOOOOOOO+o",
" %$%$%$%$XOOOOOO$%$%$OOOOOOOOOOOOOOOOOOOOOOOOO+o",
" $%$%$%$.XOOOOOO%$%$OO&&&&OOOOOOOOOOOOOOOOOOOO+o",
" %$%$%$%.XOOOOOO$%$OOOOOOOOOO$********$@OOOOOO+o",
" $%$%$%$.XOOOOOO%$OOOOOOOOO**&##OO##=#&#**OOOO+o",
" %$%$%$%.XOOOOOO$OOOOOOOO**&OOXXO-O#####&=**OO+o",
" $%$%$%$.XOOOOOOOOOOOOOO*#OXXXXXXXX;O;;O=##;*O+o",
"  $%$%$%.XOOOOOOOOOOOOO*##XXXXXXOX-;O;;OO#;##++o",
"  %$%$%$.XOOOOOOOOOOOO*##XXXXXXXXOXO&O=O=#=&=#+o",
"   %$%$%.XOOOOOOOOOOO*##OXXXXXXXOXXO=O&=O#&;&&+o",
"    %$%$.XOOOOOOOOOOO*##X;XXXXOXXO#OOOOO#&-&&&+o",
"     %$%.XOOOOOOOOOO*#=OXXXXOXXO;OXX=##=###=&%+o",
"      %$.XOOOOOOOOOO*#OOOOXXXO=OOO#=O##O#-&O;;+o",
"       %.XOOOOOOOOO$#&OO=XOXOXOOO;-O&OOO;;;;O$+o",
"        .XOOOOOOOOO+#&;;OO=;;OOO&;;O;;;;O####++o",
"        .XOOOOOOOOO+#&;;OO=;;OO;;;;;O##@###$$&+o",
"        .XOOOOOOOOO+#;;;;;;;;;;;O#######&&O#$&+o",
"        .XOOOOOOOOO+###@##O##O########&#$#%$&&+o",
"        .XOOOOOOOOO+##O##########=OO=####&&&&$+o",
"        .XOOOOOOOOO+#;#=#O#O#&##&#&&###&&&$$%$+o",
"        .XOOOOOOOOO+#####O=##=###&%###$&&&$$&$+o",
"        .XOOOOOOOOO+&######&###$#=##$#&&$$$$$$+o",
"        .X+++++++++++++++++++++++++++++++++++++o",
"        .ooooooooooooooooooooooooooooooooooooooo"};
