/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * wsm_folder_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconColor5	m black	c blue",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray4	m white	c #949494949494",
"%	s bottomShadowColor	m black	c #636363636363",
/* pixels */
"                          ................      ",
"                         .XXXXXXXXXXXXXXXXo     ",
"                         .XXXXXXXXXXXXXXXXo     ",
"    .....................XXXOOOOOOOOOOOO+++oo   ",
"    .XXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOO+++o  ",
"    .XXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOO+++o  ",
" ....XX@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+o ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+@@+o ",
" .Xoooooooooooooooooooooooooooooooooooooo@@+@+o ",
" .Xoooooooooooooooooooooooooooooooooooooo@@+@+o ",
" .Xoooooooooooooooooooooooooooooooooooooo@@+@+o ",
" .Xoooooooooooooooooooooooooooooooooooooo@@+@+o ",
" .XooooXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+o@@+@+o ",
" .XooooXooooooo+Xoooooooooooooooooooooo+o@@+@+o ",
" .XooooXooXoooo+Xo...................#o+o@@+@+o ",
" .XooooXooXXooo+Xo.$$$$$$$$$$$$$$$$$$#o+o@@+@+o ",
" .XooooXooXXXoo+Xo.$#$$$$o$#$$o$#$$$$#o+o@@+@+o ",
" .XooooXooXXXXo+Xo.$XX#$X#$#X##$X#$$$#o+o@@+@+o ",
" .XooooXooXXX+o+Xo.$$$$$$$$$$$$$$$$$$#o+o@@+@+o ",
" .XooooXooXX+oo+Xo####################o+o@@+@+o ",
" .XooooXooX+ooo+Xoooooooooooooooooooooo+o@@+@+o ",
" .XooooXoo+oooo+Xoooooooooooooooooooooo+o@@+@+o ",
" .XooooXooooooo+Xooo$ooooo$oooooooooooo+o@@+@+o ",
" .XooooX++++++++Xooo++@+o$+@+o++ooooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .XoooooooooooooXooo$oooooooo$ooooooooo+o@@+@+o ",
" .XoooooooooooooXooo++o+++o+@++oooooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .XoooooooooooooXooo$ooo$ooooooo$oooooo+o@@+@+o ",
" .XoooooooooooooXooo+@+o++o+++o++oooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .XoooooooooooooXoooooooooooooooooooooo+o@@+@+o ",
" .X@@@@@@@@@@@@@Xoooooo$o$ooo$ooooooooo+@@@+++o ",
" .o+++++++++++++Xooo++o+@+++o+@++oooooo++++++oo ",
" %ooooooooooooooXoooooooooooooooooooooo+oooooo  ",
"                Xoooooooooooooooooooooo+        ",
"                Xooo$oooooooo$ooooooooo+        ",
"                Xooo+@@+o+++o+++ooooooo+        ",
"                Xoooooooooooooooooooooo+        ",
"                Xoooooooooooooooooooooo+        ",
"                Xoooooooooooooooooooooo+        ",
"                Xoooooooooooooooooooooo+        ",
"                Xoooooooooooooooooooooo+        ",
"                X+++++++++++++++++++++++        ",
"                                                ",
"                                                "};
