/* XPM */
static char * ODtapp_l_pm[] = {
"48 48 3 1",
" 	c None",
".	c #00000000CDCD",
"X	c #8B8B5A5A0000",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                          ....                  ",
"                         ......                 ",
"                         ......                 ",
"                         .......                ",
"                         .........              ",
"                          .........             ",
"                          XX........            ",
"                         XXXX........           ",
"                        XXXXX........           ",
"                       XXXXXXX......            ",
"                      XXXXXXX  ....             ",
"                     XXXXXX     ..              ",
"                    XXXXXX                      ",
"                   XXXXXX                       ",
"                   XXXXX                        ",
"                  XXXXX                         ",
"                 XXXXX                          ",
"                XXXXX                           ",
"               XXXXX                            ",
"             XXXXXX                             ",
"            XXXXXX                              ",
"           XXXXXX                               ",
"          XXXXXX                                ",
"         XXXXXXX                                ",
"        XXXXXXX                                 ",
"       XXXXXXX                                  ",
"      XXXXXX                                    ",
"     XXXXXX                                     ",
"    XXXXXX                                      ",
"   XXXXXX                                       ",
"  XXXXXX                                        ",
" XXXXXX                                         ",
"XXXXXX                                          ",
"XXXXX                                           ",
"XXXX                                            ",
" XX                                             ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
