/* XPM */
static char * ODthelp_l_pm[] = {
"48 48 7 1",
" 	c None",
".	c #000000008B8B",
"X	c #00000000CDCD",
"o	c #EEEE00000000",
"O	c #FFFFFFFFFFFF",
"+	c #FFFFA5A50000",
"@	c #8B8B5A5A0000",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                          ..............        ",
"                          .XXXXX..ooooo.        ",
"                          .XXXXX..ooooo.        ",
"              .............XXXXX..ooooo.        ",
"        .......oooo..oooo..XXXXX..ooooo.        ",
"        .XXXX..oooo..oooo..XXXXX..ooooo.        ",
"        .XXXX..oooo.OOOOo..XXXXX..ooooo.        ",
"        .XXXX..ooooOOOOOO..XXXXX..ooooo.++      ",
"        .XXXX..oooOOOooOOO.XXXXX..ooooo.++      ",
"        .XXXX..ooOOO.oooOOOXXXXX..ooooo.++      ",
"        .XXXX..oooO..ooooOOXXXXX..ooooo.++      ",
"        .XXXX..oooo..ooooOOXXXXX..ooooo.++      ",
"        .XXXX..oooo..ooooOOXXXXX..ooooo.++      ",
"    .   .XXXX..oooo..oooOOOXXXXX..ooooo.++      ",
"   .X.  .XXXX..oooo..ooOOO.XXXXX..ooooo.++      ",
"  .XXX. .XXXX..oooo..oOOO..XXXXX..ooooo.++      ",
" .XXXXX..XXXX..oooo..oOOo..XXXXX..ooooo.++      ",
".XXXXX. .XXXX..oooo..OOoo..XXXXX..ooooo.++      ",
"XXXXX.  .XXXX..oooo..OOoo..XXXXX..ooooo.++      ",
"XXXX.   .XXXX..oooo..OOoo..XXXXX..ooooo.++      ",
"XXX.    .XXXX..oooo..OOoo..XXXXX..ooooo.++      ",
"XX.     .XXXX..oooo..OOoo..XXXXX..ooooo.+++     ",
"X.      .XXXX..oooo..oooo..XXXXX..ooooo.+++     ",
".       .XXXX..oooo..OOoo..XXXXX..ooooo.++++    ",
"        .XXXX..oooo..OOoo..XXXXX..ooooo.++ +    ",
"        .XXXX..oooo..oooo..XXXXX..ooooo.++ ++   ",
".........XXXX..oooo..oooo..XXXXX..ooooo.++++++  ",
"       ..XXXX..oooo..oooo..XXXXX..ooooo.+++  ++ ",
"OOOOOOO..XXXX..oooo..oooo..XXXXX..ooooo.++    ++",
"       ..XXXX..oooo..oooo..XXXXX..ooooo.++    ++",
"OOOOOOO..XXXX..oooo..oooo..XXXXX..ooooo.++   ++ ",
"........................................++++++++",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
