/* XPM */
static char * ODtKey_m_pm[] = {
"32 32 6 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #41416969E1E1",
"o	c #FFFFF6F68F8F",
"O	c #999999999999",
"+	c #FFFFEFEFDBDB",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"    .....                       ",
"   .XXXXX.                      ",
"  .XX..XX.                      ",
"  .X. .XXX.................     ",
"  .X. .XXX.oooooooooooooooo.    ",
"  .X. .XXX.OOOOOOOOOOOOOOOOO.   ",
"  .X. .XXX.++++++++++++++++.    ",
"  .XX..XXX.+++.+++++..++++.     ",
"  .XXXXXXX.... ..++.  ...+.     ",
"   .XXXXX.       ...     .      ",
"    .....                       ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
