/* XPM */
static char * ODtShred_m_pm[] = {
"32 32 4 1",
" 	c #FFFFFFFFFFFF",
".	c #000000000000",
"X	c #999999999999",
"o	c #CDCD00000000",
"                                ",
"                                ",
"                                ",
"      ....................      ",
"      ....................      ",
"      ..XXXXXXXXXXXXXXXX..      ",
"      ..XX...X...X....oooooooooo",
"      ..XX...X...X..X..oooooooo ",
"      ..XXXXXXXXXXXXXXXXoooooo  ",
"      ..XX...X...X...XXXXoooo   ",
"      ..XXXXXXXXXXXXXXXXXXoo    ",
"  ............................  ",
"  ............................  ",
"      X.XXXX  XXXXXX  XX..      ",
"      X.XX..  ....XX  ....      ",
"       .XXXX  XXXXXX  XX..      ",
"       .XX..  .X...X  .X..      ",
"       .XXXX  XXXXXX  XX..      ",
"       .XX..  X...X.  .X..      ",
"       XXXXX  XXXXXX  XX..      ",
"      XXXX..  ....XX  ....      ",
"        XXXX  XXXXXX  XXXX      ",
"        XX..  ....XX  ..XX      ",
"        XXXX   XXXX   XXX       ",
"         X..    .XX   .XX       ",
"          XX    XX    XX        ",
"                      X         ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
