/* XPM */
static char * ODtStyle_l_pm[] = {
"48 48 10 1",
" 	c None",
"^ 	c #FFFFFF",
".	c #999999",
"X	c #CCCCFC",
"o	c #4169E1",
"O	c #0000EE",
"+	c #0AA10A",
"@	c #FFFF00",
"#	c #FFD317",
"$	c #E62A16",
"                                                ",
"                                                ",
"                                                ",
"                               ........         ",
"                            ...XoooXXXX....     ",
"                          ..XXXoooooXXXOOOX..   ",
"                        ..+++XXXoooXXXOOOOOXX.. ",
"                       .X+++++XXXXXXXXXOOOXXXXX.",
"                      .XXX+++XXXXXXXXXXXXXXXXXX.",
"                     .XXXXXXXXXXXXXXXXXXXXXXXX. ",
"        .....        .@@@XXXXXXXXXXXXXXXXXXX..  ",
"      ..XX.XX..     .@@@@@XXXXXXXXXXXXXXXX..    ",
"     .XXXX.XXXX.    .X@@@XXXXXXXXXXXXXXXX.      ",
"    .XXXX...XXXX.   .XXXXXXXXXXXXXXXXXXX.       ",
"   .XXXX.XXX.XXXX.  .XXXXXXXXXXXXXXXXXXXX...    ",
"   .XXXX.XXX.XXXX.  .X###XXXXXXXXXXXXXXXXXXX... ",
"  .XXXXX.XXX.XXXXX. .#####XXXXXXXXXXXXXXXXXXXXX.",
"  .XXXXX.XXX.XXXXX.  .###XXXXXXXXXXXXXXXXXXXXXX.",
"  .XXXXXX...XXXXXX.  .XXXXXXXXXXXXXXXXXXXXXXXXX.",
"  .XXXXXXX.XXXXXXX.   .XXXXX$$$XXXXX^^^XXXXXXXX.",
"  ........X........    .XXX$$$$$XXX^^^^^XXXXXX. ",
"  .XXXXXXXXXXXXXXX.     ..XX$$$XXXXX^^^XXXXX..  ",
"  .XXXXXXXXXXXXXXX.       ..XXXXXXXXXXXXXX..    ",
"  .XXXXXXXXXXXXXXX.         ...XXXXXXXX...      ",
"  .XXXXXXXXXXXXXXX.            ........         ",
"  .XXXXXXXXXXXXXXX.                             ",
"  .XXXXXXXXXXXXXXX.                             ",
"  .XXXXXXXXXXXXXXX.                             ",
"  .XXXXXXXXXXXXXXX.                             ",
"   .XXXXXXXXXXXXX.                              ",
"   .XXXXXXXXXXXXX.                              ",
"    .XXXXXXXXXXX.                               ",
"    .XXXXXXXXXXX.                               ",
"     .XXXXXXXXX.                                ",
"      .XXXXXXX.                                 ",
"       .......                                  ",
"         .X.    ...                             ",
"         .X.   .XXX.                            ",
"         .X.  .XX.XX.                           ",
"         .XX..XX. .X.                           ",
"          .XXXX.  .X.                           ",
"           ....   .X.                           ",
"                  .X.                           ",
"                  .X.                           ",
"                  .X.                           ",
"                  .X.                           ",
"                  .X.                           ",
"                  .X.                           "};
