/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWaudiotool_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray1	m white	c #dededededede",
"%	s iconColor5	m black	c blue",
"&	s iconColor1	m black	c black",
/* pixels */
"                                ",
"               .X               ",
"              .ooX              ",
"             .ooooX             ",
"            .ooooooX            ",
"           .ooooooooX           ",
"          .ooooooooooX          ",
"         .ooooooooooooX         ",
"        .ooooooooooooooX        ",
"       .oooooooOoo+oooooX       ",
"      .o@oooooOooo+#oooooX      ",
"     .oo@@ooo+oooo+#@oooooX     ",
"    .ooo@oooo+ooOo+#@o@@@ooX    ",
"   .ooo@@ooo#oooOo+#@o@@@oooX   ",
"  .ooo@@@ooo#oo#oo+#@o@@@ooooX  ",
" .ooooo@oooo#oo#oo+#@o@@@oooooX ",
".ooooooooooo#oo#oo+#@o@@@ooooooX",
" .oooooooooo#oo#oo+#@o@@@oooooX ",
"  .oooo@@@oo#oooOo+#@o@@@ooooX  ",
"   .oooo@oooo+ooOo+#@o@@@oooX   ",
"    .oooo@ooo+oooo+#@ooooooX    ",
"     .oooo@oooOo$$$$$$$$$$$$$$$$",
"      .oo@@ooooO$%%@%@%@%@%@%@%&",
"       .o@@ooooo$%@%..%%.%@%.%@&",
"        .ooooooo$@%.%@.@.@%@.@%&",
"         .oooooo$%@.@%.%.%.%.%@&",
"          .ooooo$@%.%@.@.@.@.@%&",
"           .oooo$%@.@%.%.%.%.%@&",
"            .ooo$@%.%@.@.....@%&",
"             .oo$%@%..%%.%.%.%@&",
"              .o$@%@%@%@%@%@%@%&",
"               .$&&&&&&&&&&&&&&&"};
