/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWcmappt_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconGray8	m black	c #212121212121",
"o	s iconColor2	m white	c white",
"O	s iconColor8	m black	c magenta",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray5	m black	c #737373737373",
"$	s iconColor6	m white	c yellow",
"%	s iconColor1	m black	c black",
"&	s iconGray4	m white	c #949494949494",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                             .X ",
" oooooooo ooooooooo oooooooo.oOX",
"o+++++++X @+++++++X @++++++.oO#.",
"o+++++++X X+++++++X X+++++.oX#. ",
"o++++++XX X++++++XX X++++.oX#.  ",
"o++++++XX X++++++XX X+++.o$#.   ",
"o+++++++XX++++++++XX+++.o$#.X   ",
"o+++++++++++++++++++++.o$#.+X   ",
"o++++++++++++++++++++.o$#.++X   ",
"o+++++++%%+%+%+++%%+.o$#.+++X   ",
"o++++++++%+++%++%++.o$#.+++&X   ",
"o++++++++%++%+++%+.o$#.X**&&X   ",
"o+++++++%%%%%%%++.o$#.X**&&&X   ",
"o+++++++++++++++.o$#.X**&+&+X   ",
"o++%%++++++++++.@@@@@@@@@@@@@@@@",
"o++%%+%+%+%+%+.o@==.=.=.=.=.=.=%",
"o++++++++++++.o$@=.=oo==o=.=o=.%",
"o++%%+++++++.o$#@.=o=.o.o.=.o.=%",
"o++%%+%+%+%+.$#.@=.o.=o=o=o=o=.%",
"o++++++++++XX#.+@.=o=.o.o.o.o.=%",
"o++%%++++++XX+++@=.o.=o=o=o=o=.%",
"o++%%+%+%+%+++%+@.=o=.o.ooooo.=%",
"o+++++++++++++++@=.=oo==o=o=o=.%",
"o+++++++++++++++@.=.=.=.=.=.=.=%",
" XXXXXXXXXXXXXXX@%%%%%%%%%%%%%%%"};
