/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWmailtool_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray2	m white	c #bdbdbdbdbdbd",
"$	s iconColor5	m black	c blue",
"%	s iconColor3	m black	c red",
"&	s iconGray6	m black	c #636363636363",
"*	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"               ...              ",
"             ..XXo              ",
"           ..XXXXX...           ",
"         ..XXXXXX..OO.          ",
"       ..XXXXX...OOO....        ",
"     ..XXXX...OOO...++++@       ",
"   ..XXX...OOO...+++#$#+@       ",
" ..XX...OOO...++++$#$#$#+@      ",
".XX..OOO...+++++%%+$#$#$+@      ",
"@..OO...+++++++%+%++$#$++@      ",
"@OO..+++++++++++%%%%++++++@     ",
"@OO@+++++++++++++%++++++++@     ",
" @OO@+++++++++++++++++++++@     ",
" &@O@+++++++++++++++++@@@++@    ",
"  @O@++++++++++++++@@@+++++@    ",
"  @&#@++++++++++@@@++++@@++@    ",
"...@#@++++++++++++++++++++++++++",
"*OO@#@+++++++++++$$@$@$@$@$@$@$*",
"*OO@@O@XX++++++++$@$..$$.$@$.$@*",
"*OO......X+++++++@$.$@.@.@$@.@$*",
"*OOOOOOOO*X++++++$@.@$.$.$.$.$@*",
"*OOOOOOOO*XXXXXX+@$.$@.@.@.@.@$*",
"*OOOOOOOOO......+$@.@$.$.$.$.$@*",
"*OOOOOOOOOOOOOOO+@$.$@.@.....@$*",
"*&OOOOOOOOOOOOOO+$@$..$$.$.$.$@*",
" *&&&&&&&&&&&&&&+@$@$@$@$@$@$@$*",
"  **************+***************"};
