/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWperf_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray5	m black	c #7d7d7d7d7d7d",
"o	s iconGray7	m black	c #4b4b4b4b4b4b",
"O	s iconGray8	m black	c #323232323232",
"+	s iconGray1	m white	c #e1e1e1e1e1e1",
"@	s iconGray2	m white	c #c8c8c8c8c8c8",
"#	s iconGray4	m white	c #969696969696",
"$	s iconColor5	m black	c blue",
"%	s iconGray3	m white	c #afafafafafaf",
"&	s iconGray6	m black	c #646464646464",
"*	s iconColor8	m black	c magenta",
"=	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
" ............................XoO",
" .++@@@@@@@@@@@@@@@@@@@@@@@@#XoO",
" .++@@@@@@@@@@@@@@@@@@$@@@@@#XoO",
" .++@@@@@@@@@@@@@@@@@@$@@@@@#XoO",
" .++@@@@@@@@@@@@@@@@@$$@$@@@#XoO",
" .++@@@@@@@@@@@@@@@@@$$$$@@@#XoO",
" .++@@@@@@@@@@@@@@@@$$$$$@@@#XoO",
"..++@@@@@@@@@@@@@@@$$$$@$@@@#XoO",
"%.............O@@@@$$$$@$$@@#XoO",
"&%*%*%*%*%*%*%*O++++++++++++++++",
" &&&&&&&&&&&&&O@+$$o$o$o$o$o$o$=",
"#.++@@@@@@@@@@#@+$o$..$$.$o$.$o=",
"##############@@+o$.$o.o.o$o.o$=",
" ############@@@+$o.o$.$.$.$.$o=",
" .++@@@@@@@@@@@@+o$.$o.o.o.o.o$=",
" .++@@@@@@@@@@@@+$o.o$.$.$.$.$o=",
" .++@@@@@@@@@@@@+o$.$o.o.....o$=",
" .++@@@@@@@@@@@@+$o$..$$.$.$.$o=",
" .++@@@@@@@@@@@@+o$o$o$o$o$o$o$=",
" .OOOOOOOOOOOOOO+==============="};
