/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWsnapshot_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray8	m black	c #212121212121",
"#	s iconGray3	m white	c #adadadadadad",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor5	m black	c blue",
"*	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"            ........            ",
"           .XXXXXXXXo           ",
"  ..... ...XXXXXXXXXo   .....   ",
" .XXXXXXXOo++++++++++o @XXXXXX  ",
" .++++#O#Oo++++++++++o @++++$$o ",
" .####O#@@++++++++++++@@%%%%%$oo",
".@@@@@@@X@@@+@@@@@@+@@@X@@@@@@Xo",
".+++++++@XX@@@@@@@@@@XX@XXXXXXoX",
".+++++++@X@@@XXXXXX@@@X@XXXXXoX@",
".OOOOOOO@X@XX@@@@@@XX@X@OOOOOOO@",
".OOOOOOOX@X@@++++++@@Xo.OOOOOOO@",
".OOOOOOO@X@+++++++++@@XoOOOOOOO@",
".OOOOOOO@X@++..X+++++@XoOOOOOOO@",
".OOOOOO@X@++X...X++++$@+@OOOOOO@",
".OOOOOO@X@+..X.XXXXXXXXXXXXXXXXX",
".OOOOOO@X@+...XXX&&o&o&o&o&o&o&*",
".OOOOOO@X@+XXXXXX&o&..&&.&o&.&o*",
".OOOOOO@X@+++XX+Xo&.&o.o.o&o.o&*",
" @@@@@@@X@@+++++X&o.o&.&.&.&.&o*",
"        @X@+++++Xo&.&o.o.o.o.o&*",
"        @X@@++++X&o.o&.&.&.&.&o*",
"         @X@@@$$Xo&.&o.o.....o&*",
"          @XX@@@X&o&..&&.&.&.&o*",
"           @@+++Xo&o&o&o&o&o&o&*",
"             @@@X***************"};
