/* XPM */
/*********************************************************************
*  (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
**********************************************************************/
static char * OWtextedit_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor1	m black	c black",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                                ",
"          .......X              ",
"         .Xooooo.OX             ",
"        .ooXooo.OooX            ",
"       .ooooXo.OooooX           ",
"      .ooooooXOooooooX          ",
"     .ooooooooooooooooX         ",
"    .ooooooooooooooooooX        ",
"  ++++++++++++++++++++++++O     ",
"  +...@+...@+...@+...@+...O     ",
" .+.oo@+.oo@+.oo@+.oo@+.ooO     ",
".o+.oo@+.oo@+.oo@+.oo@+.ooO     ",
"XoOOOOOOOOOOOOOOOOOOOOOOOOOO    ",
" Xo++++++++++++++++++++++++OX   ",
"  X+...@+...@+...@+...@+...O#X  ",
"   +.oo@+.oo@+.oo@+.oo@+.ooO#oX ",
"   +.oo@+.oo@+.oo@+.oo@+.ooO#ooX",
"    OOOOOOOOOOOOOOOOOOOOOOOOO#o$",
"    ++++++++++++++++++++++++O#X ",
"    +...@+.............@+...OX  ",
"    +.oo@+.ooooo%%%%%%%%%%%%%%%%",
"    +.oo@+.ooooo%&&@&@&@&@&@&@&$",
"    @@@@@@@@@@@@%&@&..&&.&@&.&@$",
"           X####%@&.&@.@.@&@.@&$",
"            Xooo%&@.@&.&.&.&.&@$",
"             Xoo%@&.&@.@.@.@.@&$",
"              Xo%&@.@&.&.&.&.&@$",
"               X%@&.&@.@.....@&$",
"                %&@&..&&.&.&.&@$",
"                %@&@&@&@&@&@&@&$",
"                %$$$$$$$$$$$$$$$"};
