/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * pdasync_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor3	m black	c red",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                           .X                   ",
"                           ..X                  ",
"                           ..oX                 ",
"                           ...oX                ",
"                           ..oOoX               ",
"                           ...oOoX              ",
"                  XXXXXXXXX..oOoooX             ",
"                X+@#$$$OOOO...oOoooX            ",
"              X+@###$$O$OO...oOoooooX           ",
"             X@@#@##$$$OOOO...oOoooooX          ",
"            X@@@@###$$O$OO...oOoooooooX         ",
"           X@+@@#@##$$$OOOO...oOoooooooX        ",
"          X++@@@@###$$O$OO...oOooooooooo#       ",
"          X+@+@@#@##$$$OOOO...oOoooooooO        ",
"         X+++@@@@###$$O$OO...oOoooooooO         ",
"         X++@+@@#@##$$$OOOO...oOoooooO          ",
"        X++++@@@@###$$O$OO...oOoooooO  @        ",
"        X+++@+@@#@##$$$OOOO...oOoooO   @        ",
"        X++++@@@@###$$O$OO...oOoooO   @X        ",
"        X+++@+@#$OOOOOOOOOO...oOoO    #X        ",
"        X++++@#@           ..oOoO    #+X        ",
"        X+++@$     O.      ...oO     #+X        ",
"        X+++$     O..      ..oO     $++X        ",
"        X++$     O%..      .OO     $+++X        ",
"        X+#     O%...      OO     $@+++X        ",
"        X@#    O%.%..           @#@++++X        ",
"        X$    O%.%...OOOOOOOOOO$#@+@+++X        ",
"        X#   O%%%.%...OO$O$$###@@@@++++X        ",
"        @   O%%%.%...OOOO$$$##@#@@+@+++X        ",
"        @  O%%%%%.%...OO$O$$###@@@@++++X        ",
"          O%%%%%.%...OOOO$$$##@#@@+@++X         ",
"         O%%%%%%%.%...OO$O$$###@@@@+++X         ",
"        O%%%%%%%.%...OOOO$$$##@#@@+@+X          ",
"       #%%%%%%%%%.%...OO$O$$###@@@@++X          ",
"        O%%%%%%%.%...OOOO$$$##@#@@+@X           ",
"         O%%%%%%%.%...OO$O$$###@@@@X            ",
"          O%%%%%.%...OOOO$$$##@#@@X             ",
"           O%%%%%.%...OO$O$$###@+X              ",
"            O%%%.%...OOOO$$$#@+X                ",
"             O%%%.%..XXXXXXXXX                  ",
"              O%.%...                           ",
"               O%.%..                           ",
"                O%...                           ",
"                 O%..                           ",
"                  O..                           ",
"                   O.                           ",
"                                                "};
