/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * pdasync_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor3	m black	c red",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                   .X           ",
"                   ..X          ",
"                   ..oX         ",
"           OXXXXXXX...oX        ",
"          X+@##$#$...o$oX       ",
"         X+@@###$$$...oooX      ",
"        X+@@@##$#$...o$oooX     ",
"       X+@+@@###$$$...oooooX    ",
"       O++@@@##$#$...o$oooo@    ",
"      X++@+@@###$$$...oooo#     ",
"      X+++@@@##$#$...o$oo#      ",
"      X++@+@#######...oo#       ",
"      X+++@        ..o$#  +     ",
"      X++#         ...#   +     ",
"      X+#   #.     ..#   #X     ",
"      X#   $..     .#   #+X     ",
"      +   #%..         #++X     ",
"      +  $%...        @@++X     ",
"        #%.%..#######@@+++X     ",
"       $%%%....$#$##@@+@++X     ",
"      #%%%.%..$$$###@@@+++X     ",
"     @%%%%%....$#$##@@+@+O      ",
"     $%%%%.%..$$$###@@@++X      ",
"      @%%%%....$#$##@@+@X       ",
"       @%%.%..$$$###@@@X        ",
"        @%%....$#$##@+X         ",
"         @%%..XXXXXXXO          ",
"          @%..                  ",
"           @..                  ",
"            @.                  ",
"                                "};
