/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * addr_mgr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconColor5	m black	c blue",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor1	m black	c black",
"&	s iconColor2	m white	c white",
"*	s iconGray8	m black	c #212121212121",
"=	s iconColor7	m white	c cyan",
/* pixels */
"                 .XXXXXo        ",
"        .XXXXXoOOXXXXXXXo       ",
"       +XXXXXXXo+XXXXXXXo       ",
"       @XoXoXoXo@@@@@@@@@       ",
"      +#$$$$$$$$#########+      ",
"      ####################      ",
"      ###@@###############      ",
"      ###oX###o@o#o@#oo+##      ",
"      ##$Xo$##############      ",
"      ##XoXo##o#@o#o@#@o##      ",
"###   ##oXoX##############   ###",
"#+#O#$##XoXo##############o#O#+#",
"+++.+$####################o+.+++",
"+$+o$$#####@%+####@%+#####o$o+$+",
"@@@%@@#####O%$####O%$#####o@%@@@",
"@O@%Oo%%%%%%%%%%%%%%%%%%%%oO%@O@",
"...%.o&#&#&O%$&#&#O%$#&#&#o.%...",
".o.%oo#&#&#&#o.&#&#&o.#&#&oo%.o.",
"%%%%**&#&#&#&#@$&#&#&@$#&#o*%%o%",
"%%%%oo#&#&#&#&#&#&#&#&#&#&oo%%%%",
"*o* &%&#&#&#&#&#&#&#&#&#&#+% *o*",
"    &%#&#&#&#&#&#&#&#&#&#&+%    ",
"   =$%&#&#&#&#&#&#&#&#&#&#+.o   ",
"   #% @@@@@@@@@@@@@@@@@@@@ #%   ",
"   &%  OOOOOOOOOOOOOOOOOO  &%   ",
"   &%   ................   &*   ",
"   &%                      &*   ",
"   &*                      &*   ",
"   &*                      &*   ",
"   &*                      &*   ",
"   #o#&&&&&&&&&&&&&&&&&&&&&&o   ",
"    .%%%%%%%%%%%%%%%%%%%%%%o    "};
