/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * mail_addr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor4	m white	c green",
"#	s iconGray2	m white	c #bdbdbdbdbdbd",
"$	s iconColor3	m black	c red",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
" .............................................. ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXoOOXoOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+@+@#Xo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX$O$XXX$O$O%@+XXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$O$XXX%@O@#Xo ",
" .XXoOOOXoOXXXXXXXXXXXXXXXXXXXX$O$XXX$O$@O@+XXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$O$XXXO@O@#Xo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@+@+XXo ",
" .XXXXXXXXXXXXXXXXXXO&&&&OXXXXXXXXXXXXXX#X#X#Xo ",
" .XXXXXXXXXXXXXXXXX&XXXXXX&XXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXX&XXXXXXXX&XXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXX&XXX&&&X&XXOXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXOXXX&XXX&XXX&XXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXX&XX&XXXX&XXX&XXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXX&XX&XXXX&XXXOXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXX&XX&XXX&XXX&XXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXOXXX&&&X&&&XXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXX&XXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXX&XXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXO&&&&&XXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .ooooooooooooooooooooooooooooooooooooooooooooo ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
