! XPM2
48 48 16 1
a c #000000
b c #212121
c c #424242
d c #636363
e c #737373
f c #949494
g c #adadad
h c #bdbdbd
i c #dedede
j c #ffffff
k c #ff0000
l c #00ff00
m c #0000ff
n c #00ffff
o c #ff00ff
p c #ffff00
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjijjegjjjjjjjjjjjjf
jfffffffffffffffffffffffffffijjigbdffffffffffffa
jfffffffffffffffffffffffffgijjjgcacffffffffffffa
jfffffffffffffffffffffefijijjjfbadfffffffffffffa
jfffffffffffffffffffffgijjjjifbadffffffffffffffa
jffffffffffffffffffffhjjjjjigbadfffffffffffffffa
jfffffffffffffffffffgijjjjiebadffffffffffffffffa
jffffffffffffffffffgijjjjieaadfffffffffffffffffa
jffffffffffffffffffijjjjiebadffffffffffheffffffa
jffffffffffffffffeehjjjihcaeffffffffffgjgdfffffa
jffffffffffffffeemeijjjiicamfffffffffghjfcfffffa
jffffffffffffeddmdfhjjjjjfcmmffffffffijjdafffffa
jffffffffffeeedmdmdhjjiijjhecmfffffghjjicafffffa
jffffffffeddmdmdmdmfiijiijjhdmmeffgiijjfccfffffa
jffffffedddmdmdmdmdchijjiijjhemcggiijjhccffffffa
jffffdddmdmdmdmdmdmdfijijjijjhghiiijjifabffffffa
jffddmemdmdmdmdmdmdceiiijiijjjijjijjjgbceffffffa
jfemmememdmdmdmdmdmdeffhjjijjjiijijjicaefffffffa
jfdbmmememdmdmdmdmdmeffehijjiiijjjjidaaefffffffa
jfcmbmmememdmdmdmdmeffddfhijjjjjjigdabdffffffffa
jfcbmbmmemdmdmdmdmdcfeeedeghiiiigfcaacfffffffffa
jfcmbmbmmdmdmdmdmddchiihedefffdcbadmdmmffffffffa
jfdbmbmbmmdmdmdmdmchijjjgeddcbmdmdmdmdmmfffffffa
jfdmbmbmbmmdmdmdmdcijjjjifccbbdmdmdmdmdmmffffffa
jfedmbmbmbmmdmdmdcgijjjjgdcaadmdmdmdmdmdmmfffffa
jffedmbmbmbmmdmdecgjjjjifcbbdmdmdmdmdmdmdmmffffa
jffeedmbmbmbmmdmcihjjjjhebbemdmdmdmdmdmdmdmmfffa
jfddcddmbmbmbmmccijjjjhecbbmdmdmdmdmdmdmdmmccffa
jfecdcddmbmbmbmcghjjjjhcbbmdmdmdmdmdmdmmmccedffa
jfeecdcddmbmbmccijjjjifcabdmdmdmdmdmdmmccffffffa
jfffecdcdembbccgijjjjfdcbmmdmdmdmdmmmccefhjhfffa
jffffecdcddcccchjjjjiebbcmdmdmdmdmmccdghiijhfffa
jfffffecdcdecchijjjjhebamdmdmdmmmccfghijjjjifffa
jffffffecdcddchjjjjhecbbdmdmdmmccffhijjjjjjihffa
jfffffffecdcchhjjjjhcbbmmdmmmccefhijjjjjjihfdffa
jfffffffffcdcijjjjifcacmdmmccffhijjjjjjiifdmmbfa
jfffffffffdcfijjjjfdcbmmmccffhijjjjjjjhfcmmmbbfa
jffffffffffcgjjjjiebbbcmddfhiijjjjjihfcmmmbbfffa
jffffffffffhhjjjjhebaacefhijjjjjjiifdmmmbbeeeffa
jffffffffffhjjjjhddbabcegijjjjjjhfcmmmbbdddddffa
jfffffffffhjjjjjhcbbdmcehjjjjihfcmmmbbdcdddefffa
jfffffffffdijjjifcabdmmefijiifdmmmbbcdddddfffffa
jfffffffffbbjjigdccccdcmdhhfcmmmbbdddddefffffffa
jfffffffffcbdddbabcdccdmmdmcmmbbdcddddfffffffffa
jfffffffffeeaaaabbeeecbbmmmmbbcdddddfffffffffffa
jfffffffffffeeeeeeeeeedebbbbddddddfffffffffffffa
jfffffffffffffffffdddeeeeeeeeedffffffffffffffffa
faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
