/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * mail_addr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray7	m black	c #424242424242",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray5	m black	c #737373737373",
"@	s iconColor3	m black	c red",
"#	s iconColor4	m white	c green",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"...............................X",
".ooooooooooooooooooooooooooOoOoX",
".o++o++oooooooooooooo@+oo@+#O#OX",
".oooooooooooooooooooooo@+o$+#+oX",
".o+++o+oooooooooooooo@+oo@++#+OX",
".oooooooooooooooooooooo@+oO#O#oX",
".oooooooooooo%%%%%oooooooooooooX",
".oooooooooo$%ooooo%ooooooooooooX",
".oooooooooo%oo%%o%o%oooooooooooX",
".ooooooooo%oo%oo%oo%oooooooooooX",
".ooooooooo%o%ooo%oo%oooooooooooX",
".ooooooooo%o%oo%oo%ooooooooooooX",
".ooooooooo%oo%%o%%oooooooooooooX",
".oooooooooo%oooooooooooooooooooX",
".ooooooooooo%%%%%ooooooooooooooX",
".ooooooooooooooooooooooooooooooX",
".ooooooooooooooooooooooooooooooX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
