/* XPM */
static char * record_blinkerOff_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"6 32 4 1 0 0",
/* colors */
" 	s bottomShadowColor	m black	c #636363636363",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconColor3	m black	c red",
"o	s topShadowColor	m white	c #bdbdbdbdbdbd",
/* pixels */
"      ",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
" X.X o",
" .X. o",
"     o",
" ooooo"};
