/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtconv_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconColor3	m black	c red",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"   ........................     X               ",
"   .ooooooooooooooooooooooX    XX               ",
"   .ooooooooooooooooooooooX   XXX               ",
"   .ooooooooooooooooooooooX  XXXXXXX            ",
"   .ooXXOXXXoooXXoXXooooooX   XXX   XX          ",
"   .ooooooooooooooooooooooX    XX     X         ",
"   .ooooooooooooooooooooooX     X     X         ",
"   .ooXXXXXooooXXoXXooooooX            X        ",
"   .ooooooooooooooooooooooX            X        ",
"   .ooooooooooooooooooooooX            X        ",
"   .ooXXXOOXXXooooXXooooooXo...........X...     ",
"   .ooooooooooooooooooooooX+@@@@@@@@@@@X@@X     ",
"   .ooooooooooooooooooooooX+@@@@@@@@@@@X@@X     ",
"   .ooXXXXXooooXXXooooooooX+@@@@@@@@@@@@@@X     ",
"   .ooooooooooooooooooooooX+@@@@@@@@@@@@@@X     ",
"   .ooooooooooo...............@XXX@@@@@@@@X     ",
"   .ooooooooooo.O#O#O#O#O#O#OX@@@@@@@@@@@@X     ",
"   .ooooooooooo.#O#O#O#O#O#O#X@@@@@@@@@@@@X     ",
"   .ooXXXoooooo.O#O#O#O#O#O#OX@XX@@@@@@@@@X     ",
"   .ooooooooooo.#O#O#O#O#O#O#X@@@@@@@@@@@@X     ",
"   .ooooooooooo.O#O#O#O#O#O#OX@@@@@@@@@@@@X     ",
"   .ooXXXXXoooo.#O#O#O#O#O#O#X@@@@@@@@@@@@X     ",
"   .ooooooooooo.O#O#O#O#O#O#OX@@@@@@@@@@@@X     ",
"   .ooooooooooo.#O#O#O#O#O#O#X@@@@@@@@@@@@X     ",
"   .ooXXoXXoXXo.XXXXXXXXXXXXXX@OOX@@@@@@@@X     ",
"   .ooooooooooooooooooooooX+@@@@@@@@@@@@@@X     ",
"   .ooooooooooooooooooooooX+@@@@@@@@@@@@@@X     ",
"   .ooXoooooooooooooooooooX+@@@...............  ",
"   .ooXoooooooooooooooooooX+@@@.$%$%$%$%$%$%$X  ",
"   .XXXXXXXXXXXXXXXXXXXXXXX+@@@.%$%$%$%$%$%$%X  ",
"      X            o++++++++@@@.$%$%$%$%$%$%$X  ",
"      X            .@@@@@@@@@@@.%$%$%$%$%$%$%X  ",
"      X            .@@XXXXX@@@X.$%$%$%$%$%$%$X  ",
"       X     X     .@@@@@@@@@@@.%$%$%$%$%$%$%X  ",
"       X     XX    .@@@@@@@@@@@.$%$%$%$%$%$%$X  ",
"        XX   XXX   .@@XXX@@X@@@.%$%$%$%$%$%$%X  ",
"          XXXXXXX  .@@@@@@@@@@@.XXXXXXXXXXXXXX  ",
"             XXX   .@@@@@@@@@@@@@@@@@@@@@@X     ",
"             XX    .@@@@@@@@@@@@@@@@@@@@@@X     ",
"             X     .XXXXXXXXXXXXXXXXXXXXXXX     ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
