/* XPM */
static char * ClipPanel_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 5 1 0 0",
/* colors */
" 	s iconGray1	m white	c #dededededede",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconGray3	m white	c #adadadadadad",
"O	c #646464646464",
/* pixels */
"             ..........XX..........            X",
"  ooooooooooo..........XX..........OooooooooooXX",
" oooooooooooo......................OOooooooooooO",
" oooooooooooo......................OOooooooooooO",
" oooooooooooo......................OOooooooooooO",
" oooooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooO",
" ooooooooooooooOOOOOOOOOOOOOOOOOOOOOOooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" ooooooooooooooooooooooooooooooooooooooooooooooO",
" XooooooooooooooooooooooooooooooooooooooooooooOX",
"XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXX"};
