/* XPM */
static char * SDtEarth_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconColor4	m white	c green",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
/* pixels */
"             .....X             ",
"          oX....OXoX.X          ",
"        .oXoXOXOXoXoX.Xo        ",
"      ..oXoXoXoXo.OXoXoX+X      ",
"     .XoXoXoXoXoX.Xooo.OX@X     ",
"    XXoXoXOXoXoXoXoX.....X@X    ",
"   ..oXoXOXOXoXoXoXoXOXO.OX@X   ",
"   .OXoXOXOXOXoXoXoX+X@o.X@X#   ",
"  ..XoXOXOXOXoXoXoX+X@o@X.X#X#  ",
"  ..OXoXOXOXoXoXoo.X@..o@o#X#X  ",
" ....oXoXoXoXo.o..X@Xo....X.X#X ",
" ...OXoXoXoXoo.....X........$X# ",
" ..O.oXoXoXoXo.............#.$. ",
"...X.XoXoXoooo..X.........#.$.$%",
"....X.XoXoo...........X....$.$.$",
"........oXoo......OXOX....$.$.$%",
"........Xoo.......X#X#...$.$.$.$",
"......XX.X+......X#o#o#o$.$.$.$%",
"........X+o......O.....#.$.$.$.$",
" .........@......X.XOX#.$.$.$.$ ",
" ...........X.....X#.O.OXO.$.$% ",
" ..........X@XOXO.#..X#X$.$.$.$ ",
"  .........OX#X#X#X#..X.X$.$.$  ",
"  ...........X#X#X#XOX%X%.$.$%  ",
"   ...........X#X#X#X%X%X$.$%   ",
"   ............##X#X%X%X%.$X#   ",
"    .........#.$X#X%X%X%X$X#    ",
"     .......#.$.#X%X%X%.$.%     ",
"      .#.#.$.$.$X%X%X%.$%$      ",
"        $.$.$.$.$X%X%X%%        ",
"          %%%$.$.$.$%%          ",
"             %%%%%$             "};
