/* XPM */
static char * Earth-30_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
/* pixels */
"         ......         ",
"      ............      ",
"     .........X....     ",
"    .............oX.    ",
"   ..........XoXoXOXO   ",
"  ...........oXoXOXOX.  ",
" .........oXoXoXOXOXOX. ",
" .........XoXoXOXOXOX+. ",
" ......X@...oXOXOXOX+X+ ",
".......@X.....XOXOX+X+X.",
".....XoX........OX+X+X#.",
"...oXoXo........X+X+X#X.",
"..oXoX.Xo.......+X+X#X$.",
".oXoXoXo..X......+X#.$..",
".XoXoXoXO..X...X+X#X$X$X",
" oXoXo.....O...+X#X.X$X ",
" X.XoX.X..OX...X#X$...% ",
" ..oXOXOX.X.....X$X%.%X ",
"  o..XO.O.....#X$X..%X  ",
"   .............X.X%X   ",
"    ...........X.X%X    ",
"     ...........X%X     ",
"      X........X%.      ",
"         ......         "};
