/* XPM */
static char * Earth-90_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconColor2	m white	c white",
"$	s iconGray5	m black	c #737373737373",
/* pixels */
"         ......         ",
"      X..XoXoXoX..      ",
"     ..oXoXoXoXoX..     ",
"    ...XoXoXoXoXoX.X    ",
"   ..oXOXOXoXoXoX.X+.   ",
"  ....OXOXOXoXoXo.+X+X  ",
" .....XOXOXoXoXoX+X+.@X ",
" .....#XOXoXo.oX+X+..X$ ",
" ......OXoXoX..+X+X@X$X ",
".....X.Xo....X.X+.@X..$X",
"......Xo........X@X$.$X$",
"......oX...........X$.$X",
"..................X$.$X$",
"......oX....+X@X......$X",
".......oX...X@X$......X$",
" ......X+X+X@..X....... ",
" ......XX+X@X$......... ",
" .......+X@X.X......... ",
"  ......X@X$..X$X.....  ",
"   ....X@X$X$X$X.....   ",
"    ...@X$X$.$X.....    ",
"     ...$X$X$X.....     ",
"      ...$X..$...X      ",
"         ...X.X         "};
