/* XPM */
static char * Earth+90_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	c #00000000FFFF",
"o	c #0000FFFF0000",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray5	m black	c #737373737373",
/* pixels */
"         .X.XXX         ",
"      .XXX.XXo.XXX      ",
"     XXXXXo.o.ooXXX     ",
"    XXXXXo.X.oo.oXXX    ",
"   XXXXXo.o.oo.o.XXXX   ",
"  XXXXXoOoXXo.o.XXXXXX  ",
" XXXXXXXXXoX.o.oXXXXXXX ",
" XXXXXXXXXo.o.o.oXXXXXX ",
" XXXXXXXOXXo.o.o.XXXXXX ",
"o.XXXXXXo.o.XXX.oXXXXXXX",
".oXXXXXX.o.oXXXX+oXXXXXX",
"o.oXo.XXXXXXXXXXXXXXXXXX",
".oXo.XXXXXXXXXXX@oXXXXXX",
"o.oXo.o.XXXXXXXXo#XXXXXX",
".oXX.oXo.X+XXXXo#XoXXXXX",
" .o.o.o.oXX@o@o#oXXXXXX ",
" o.XXo.o+oXo@o#o$oXXXXX ",
" .oXo.o+o@o@o#o$o$XXXXX ",
"  .o.oXo@o@o#o$o$oXXXX  ",
"   Xo+X@o@o#o$o$o#oXX   ",
"    oX@o@o#o$o$o#XXX    ",
"     XX@o#o$o$o#oXX     ",
"      XX#o$o$o#XXo      ",
"         XXXXXX         "};
