/* XPM */
static char * Earth-60_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	c #0000FFFF0000",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray1	m white	c #dededededede",
"#	s iconColor2	m white	c white",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray6	m black	c #636363636363",
/* pixels */
"         ......         ",
"      ......XoXo..      ",
"     .....o.oXoXoX.     ",
"    ......XoXoXoXoOo    ",
"   ......XoXoXoXoOo+.   ",
"  ........@oXoXoOo+o+.  ",
" ......o.@o@oXoOo+o+o.. ",
" ........o@oXoOo+o+o+o. ",
" ......#o@o.oOo+o+o+.$o ",
"........@......o+o+o$o$o",
"......o.......o.o+o$o$o$",
"......@o........+o$o.o$o",
"......oX........o$o$o.o%",
"......Xo...o+....o.o%.%o",
".....XoX..o.o$...$o%o.o%",
" ....oXoO.+.$o.o.o.o.o% ",
" ...oXoOo+.$.$...$.%o%o ",
" ...XoOo+.$..o.....o%o. ",
"  ..oOo+o.o$........o%  ",
"   .Oo+o.o$o$.......%   ",
"    .+o$o$..........    ",
"     ..............     ",
"      ..o.........      ",
"         o.....         "};
