/* XPM */
static char * Earth+150_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	c #0000FFFF0000",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray5	m black	c #737373737373",
/* pixels */
"         ......         ",
"      .Xo........o      ",
"     oXo...........     ",
"    oXo.o...........    ",
"   oXo.o.............   ",
"  oX..oOoO.....X.Xo..+  ",
" oX.XoOo.....o.oXo@o+.. ",
" X...OoOo...oo..o.o+o.o ",
" oXo.oOoO...o.....+o+o# ",
"oXoXoOoOo...o..@o+o+o#o.",
"..X.OoO......o..+o+o#o@.",
".XoXoXoX.......+o.o#o@..",
".oXoXoXo........+o#o@...",
".XoXoXo@........o#o.....",
".oXoXo@o@o.....o#.......",
" XoXo@o@o+o+...#o...... ",
" .Xo@o@o+o+o#o......... ",
" .o@o@o+o+o#o#......... ",
"  .o@o+o+o#...........  ",
"   @o+o+o#o..........   ",
"    .o+.............    ",
"     ....o.........     ",
"      ............      ",
"         ......         "};
