/* XPM */
static char * Earth-0_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray5	m black	c #737373737373",
/* pixels */
"         ......         ",
"      ............      ",
"     ..............     ",
"    ................    ",
"   ..................   ",
"  ............X....o..  ",
" .........X.oX..oXoX..O ",
" ..+X..@X@X.XoXoXoXoXO. ",
" .+X+X@X@X....oXoXoXOX. ",
".+X+X+X@X......oXoXOXOX.",
".X+X+X+X+......XoXOXOXO.",
"..X+X+X+X......oXOXOXOX.",
"+.+.+..X+Xo....XOXOXOX#.",
".+X+X.X+.+X...X..OXOX#X.",
"+..X+X...Xo.....OXOX#X#.",
" ...X+..XoX...XOXOX#X#X ",
" ....X.......XOXOX#X#X. ",
" X...........O.OX#..X.. ",
"  .........X.XOX#X#X..  ",
"   ........XXOX#.#X#X   ",
"    ........O..X..#.    ",
"     ......O.#.#X#X     ",
"      ...XOX#X#X#X      ",
"         OX#X#X         "};
