/* XPM */
static char * Earth3D_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconColor4	m white	c green",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray8	m black	c #212121212121",
/* pixels */
"         .....X         ",
"      ..oXoXoXoXOX      ",
"     .XoXoXoXoXOXOX     ",
"    oXoXoXoXo..X.XOX    ",
"   oXoX+X+XoXOX.XO.@X   ",
"  .XoX+X+XoXOXOXOX.X@X  ",
" ..oX+X+XoXOXOXOX@X.X@. ",
" ..XoX+XoXOXOXO.@X@X.X@ ",
" ..oXoXoXOX...X@X.X...X ",
"....oXoXOX..............",
"..X.XoXOX....X..........",
"......OX......@X........",
"......XO.....@X@X.......",
".....X.X.....X..#X......",
".......O....X@X.........",
" ........X.....X.X$.... ",
" .......X@X@X#X..$X.... ",
" .........@X#X#X$X%...X ",
"  .........#X#X$..X...  ",
"   .........#X$X%XX..   ",
"    ........X$X%X&..    ",
"     .......$X%X..X     ",
"      .........&..      ",
"         ......         "};
