/* XPM */
static char * Earth+60_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray3	m white	c #adadadadadad",
/* pixels */
"         ......         ",
"      .XoXo.......      ",
"     X..XoXo.......     ",
"    ..oXoXoXX.......    ",
"   ...XoXoXoX........   ",
"  ...XOXOXoXoX........  ",
" X...OX..OX.Xo......... ",
" .....OX.XoXoXoX....... ",
" ....OX..O.o..Xo....... ",
"........................",
"......XO..X.....X+......",
".......XoX......+X......",
"...............+X+......",
"...............X+X@X....",
".....o........X+X@X#.X..",
" X.X.X.X$X....+X@X#X... ",
" oX.XoX$X$.+X+X@X#X#... ",
" .oX.X$X$X+X+X@X#X#X#.. ",
"  XoX.X$X+X+X@X#X#X#X.  ",
"   X$.$..X+X@X#X#X#X.   ",
"    X$..X+.@X#X#X#X#    ",
"     X+.+X@X#X#X#X.     ",
"      X+X@.#X#X#..      ",
"         X.....         "};
