/* XPM */
static char * Earth-150_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #0000FFFF0000",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	c #00000000FFFF",
"O	s iconGray1	m white	c #dededededede",
"+	s iconColor2	m white	c white",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray6	m black	c #636363636363",
/* pixels */
"         .X.X.X         ",
"      oo.X.X.X.X.o      ",
"     oo.X.X.ooo.X.X     ",
"    oX.XoX.o.X.o.X.X    ",
"   .X.X.O.X.X.X.X.ooo   ",
"  oX.X.O.O.X.o.ooooooo  ",
" oX.X.+.O.X.X.X.Xoooooo ",
" o.X.O.+.X.X.oooooooooo ",
" .X.O.O.X.ooooo.ooooooo ",
"oX.X.O.X.o.ooooooooooooo",
"o.X.X.X.Xooooo@.#.oooooo",
"oX.X.X.X.oooo@.@ooo#oooo",
"ooo.X.X.ooooo.oo#o#.oooo",
"oo.X.X.X.ooooo.#o#.$oooo",
"oooo.oX.Xooooooo#oo.$oo.",
" ooooooo..ooooo#.$.o.o. ",
" ooooo.o@oo.#.#.$.$.$oo ",
" ooooooooo.#.#.$.$.$.oo ",
"  oooooooooooo$.$.$.%o  ",
"   ooooooooooooo.$.%o   ",
"    oooooooooooooooo    ",
"     oooooooooooooo     ",
"      oooooooooooo      ",
"         oooooo         "};
