/* XPM */
static char * Earth+120_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconColor5	m black	c blue",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray6	m black	c #636363636363",
/* pixels */
"         .....X         ",
"      .........X..      ",
"     ..............     ",
"    ...o......OX+X+.    ",
"   O..o.o..@XOX.X+X#.   ",
"  OX.o.o....XX.X+X#X..  ",
" .XOX.o...X..+.+X#X#... ",
" XOXO.@...@.+.+X#X#X... ",
" OX.X.X.X.X+.+.#X#X.... ",
"OX.XOX@...+X.X..#X#.....",
"XO.OX.X....+X...X#......",
"OX.XOX+X........#X......",
"XOX.X+X+........X$......",
"OXOX+X+X.X.......X......",
"XOX+X+X+X......%........",
" X+.+X+X#X#X.X$X%...... ",
" .X+X+X#X#X#X$X........ ",
" ..X+X#X#X#X$X%.X...... ",
"  .+X#X#X#X$X%........  ",
"   .#X#X#X$X%X%......   ",
"    X#X#X$X%X%......    ",
"     .#X$X%X.X.....     ",
"      ..X%X%......      ",
"         ......         "};
