/* XPM */
static char * SDtEarth_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconColor4	m white	c green",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray8	m black	c #212121212121",
/* pixels */
"                     ......                     ",
"                ........XXXXoXoX                ",
"              .oXo.o......XoXoXoXX              ",
"            ..oXoXoXoXoXoXo.oXo.XXOX            ",
"          ...oXoXoXoXoXoXoXoXoXo.OXOXX          ",
"         ...oXoXoXoXoXoXo..XoXoXOXOXOXX         ",
"        .oXoXoXoXoXoXoXoXO.XXoX...XOXOXX        ",
"       .oXoXoXoXoXoXoXo.O..Xo..XOX.XOXOXO       ",
"      XoXoXoXoX+X+XoXoXoXXXoXOX..OX..OXOXO      ",
"     ..XoXoXoX+X+X+XoXoXoXoXOXOXOXO...XXOXO     ",
"    X.XoXoXoX+X+X+XoXoXoXoXOXOXOXOO...XOXOX.    ",
"    ..XXoXoX+XXX+X+XoXoXoXOXOXOXOXOXO.XXOXOX    ",
"   ..XXoXoX+XXX+X+XoXoXoXOXOXOXOXOXOO..XXOX@X   ",
"   X.XoXoXoX+X+X+XoXoXoXOXOXOXOX.XOXOX..XX@X@   ",
"  ...XXoXoX+X+X+XoXoXooOoOXOX.X.XOXOXOOO.XX@X@  ",
"  ......oXoXoX+XoXoXo..X...XOX.XO...XO.X@X@X@X  ",
" ......XXoXoXoXoXoXoXOO.X...XOOOOO..X..XX#.@X@@ ",
" .....XXoXoXoXoXoXoXO........X..........#.$.@X$ ",
" ......XXoXoXoXoXoXOO...............XX.#.$.$.$$ ",
" ......XoXoXoXoXoXOO....................#.$.$.$ ",
" ......XXoXoXoXoXO.X.X....X............#.$.$.$$ ",
".....X..oO.XoXoXOO...............X....#.$.$.$.$$",
"......X.Xo..XoXOX....................#.$.$.$.$.$",
"............XXOXO..........oXXoX@.....$.$.$.$.$$",
"............XOXO...........XXOX@X@...$.$.$.$.$.$",
"............XXOO...........XOX@X@X..#.$.$.$.$.$$",
".........XXO.XXO..........X.X@o@o@o#.$.$.$.$.$.$",
" ............XOXO..........X......#.$.$.$.$.$.$ ",
" ............XXOO........X.......#.$.$.$.$.$.$$ ",
" ...............O.......X...XXXX#.$.$.$.$.$.$.$ ",
" .................XX....X...X@.#X$X$.$X$.$.$.$$ ",
" ................XOXO....XX.XX#.$X$X$.$.$.$.$.$ ",
"  ..............XOXOXOXXX@X@X@.#X$X%X$X$.$.$.$  ",
"  ..............XXOXOX@X@X@X#.#.#X%X%X$.$.$.$$  ",
"   .............XOoOX@X@X@X%X#.#..X%X%.$.$.$$   ",
"   .................@X@X@X%X$X$X#X%X%X$.$.$.X   ",
"    .................@X@X$X$X$X%X%X%X&.$.$.$    ",
"    ..................#X$X$X$.%X.X%.&X$.$.$X    ",
"     ................#.$X$X$X%X%X%X&X$.$.$X     ",
"      ............#.#.$.$X$X%X%X%X&X&.$.$X      ",
"       ..........#.$.$.XX$X%X%X%X&X&.$X$$       ",
"        ......#.#.$.$.$X$X$X%X%X&X&.$.$$        ",
"         #.#.#.$.$.$.$.$X$X%X%X&X$.$XX$         ",
"          @$$.$.$.$.$.$.$X%X%X&X&.$X$$          ",
"            @$.$.$.$.$.$.$X%X&X&XX$$            ",
"              $$$.$.$.$.$.$.$.$.$$              ",
"                $$$$$$.$.$.$$$$$                ",
"                     $$$$$$                     "};
