/* XPM */
static char * Earth+180_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #0000FFFF0000",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	c #00000000FFFF",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
/* pixels */
"         .X.X.X         ",
"      .X.X.X.X.ooo      ",
"     .X.XoXoXoooooo     ",
"    oXoo.ooXoooooooo    ",
"   .X.XoX.X.Xoooooooo   ",
"  oo.X.X.X.o.ooooooooo  ",
" oo.ooO.OoXooooooooooo. ",
" o.X.O.O.O.ooooooo.oooo ",
" .X.O.O.O.ooo.+.oo@.ooo ",
"oX.X.O.Oooooo+.ooo.@.oo#",
"o.X.X.Xoo.ooo.@o@.o.#.#o",
"oX.X.X.X.oooo@.@.oo#o#o.",
"o.X.X.X.+oooooo.@.#.#.oo",
"oX.X.X.+.oooooo@.#.#.#.o",
"o.X.X.+.+oooooo.#.#.#.$o",
" o.X.+.+.@oooo.#.#.#.$o ",
" oX.+.+.@.@.o.#..oo.$oo ",
" .oo.+.@oo.@o#ooooooooo ",
"  oo+oooo.oooooooooooo  ",
"   oooooooooooooooooo   ",
"    oooooooooooooooo    ",
"     oooooooooooooo     ",
"      oooooooooooo      ",
"         oooooo         "};
