/* XPM */
static char * Earth+30_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #00000000FFFF",
"X	c #0000FFFF0000",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray5	m black	c #737373737373",
"$	s iconGray6	m black	c #636363636363",
/* pixels */
"         ......         ",
"      ............      ",
"     ..............     ",
"    ................    ",
"   .XoXo.............   ",
"  .XoXOXOX............  ",
" ..oXOXOXOXoXX......... ",
" ..XoXOXOXoXX..X.X..... ",
" X.o.OXOX.....X+....... ",
"X..Xo..X.......X+X.X....",
"....XoX.Xo.....+X@X@X@..",
"....oX.X..o.....@X@X@...",
"....X...XoX....@X@X@X#X.",
"......oXoX.....X@X@X#X#.",
".............X.@X@X#X#X.",
" .......+.....@X@X#X#X$ ",
" ..........@X@X@X#X#X$. ",
" ......X+X@X@X@X#X#X$X. ",
"  .......@.@X@X#X#X$X.  ",
"   ...@X@X@X@X#X#X$X$   ",
"    X@X@.@X@.#X.X$X.    ",
"     X@X@...#X#X#..     ",
"      .@X#X#X#X#..      ",
"         X#X#X#         "};
