/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * websearch_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor7	m white	c cyan",
"%	s iconColor1	m black	c black",
"&	s iconColor5	m black	c blue",
"*	s iconColor3	m black	c red",
"=	s iconColor6	m white	c yellow",
"-	s iconGray6	m black	c #636363636363",
";	s iconGray7	m black	c #424242424242",
":	s iconColor4	m white	c green",
/* pixels */
"                                                ",
" ......................................         ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
" .XXOoOXXXOoOoOXXXOoOoOXXXOoOXXXXXXXXXo         ",
" .XXXoXXoXXoXoXXoXXoXoXXoXXoXXXXXXXXXXo         ",
" .XXXoXooXo+XoXooXo+XoXooXo+XXXXXXXXXXo         ",
" .XXXoXooXoXXoXooXoXXoXooXoXXXXXXXXXXXo         ",
" .XXXoo+oo+XXoo+oo+XXoo+oo+XXXXXXXXXXXo         ",
" .XXXooXooXXXooXooXXXooXooXXXXXXXXXXXXo         ",
" .XXXoXXoXXXXoXXoXXXXoXXoXXXXXXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo         ",
" .XXXoooXooXXooooXXXXXooooooXXXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXXXooX@X@X@ooXXXXXXXXo         ",
" .XXXXXXXXXXXXXXXXoo##.#.#..##ooXXXXXXo         ",
" .XXXooooXoooXoXXoXX#........#XXoXXXXXo         ",
" .XXXXXXXXXXXXXXoXX.#..$..$...##XoXXXXo         ",
" .XXXXXXXXXXXXXXoX#..$.....$....#oXXXXo         ",
" .XXXoooXoooXXXoXX#..#.###..$...#@oXXXo         ",
" .XXXXXXXXXXXXXoXX###.#####.#....XoXXXo         ",
" .XXXXXXXXXXXXoXX#X#########.##..#XoXXo         ",
" .XXXooXooXooXoXX#############...#@oXXo         ",
" .XXXXXXXXXXXXoXXX###########....#XoXXo         ",
" .XXXXXXXXXXXXoXXX############..#X@oXXo         ",
" .XXXoooXooXXXoXXXX###########..#XXoXXo         ",
" .XXXXXXXXXXXXoXXX#X#############X@oXXo         ",
" .XXXXXXXXXXXXXoXXX#X###########XXo+oXo         ",
" .XXXXXXXXXXXXXoXXXXX#X##X#####XX@o++oo         ",
" .XXXXXXXXXXXXXXoXXX#$XX##X#X#X#@o++++o         ",
" .XXXXXXXXXXXXX%oXXXXX$XXX$XXXXXXo+&++o         ",
" .XXXXXXXXXXXX%X+oXXXXX$$XXXXXX@o#@+++o         ",
" .XXXXXXXXXXX%X+X.oo@XXXXXXXX@ooo+o*=+o         ",
" .XXXXXXXXXXX%++.@..ooX@X@X@ooXX-oO@*#+         ",
" .XXXXXXXXXX%X$X....X.oooooo$++$-o;*@*=+        ",
" .XXXXXXXXXX%+XXXX...X$XXXX$X++X-;o;*@*#+       ",
" .XXXXXXXXXX%XXX$.X.X.XXX@:X-XXX@-;o;*@*=+      ",
" .XXXXXXXXX-+-@@XX$@@XXX-@@X@@@@X+-;o;*@*#+     ",
" .XXXXXXXXXo+-@@XX$@@XXX@@@@X++++++-;o;*@*=+    ",
" .XXXXXXXXXo+++O+@@@@@@@X+++++++--X+-;o;*@*#+   ",
" .XXXXXXXXXo++X+++X++X++++++++-+;+&;--;o;*@*=+  ",
" .XXXXXXXXXo+++++++++++++$XX$++++----;-;o;*@*#+ ",
" .XXXXXXXXXo+@+$+X+X+-++-+--+++---;;&;o-;o;*@*O ",
" .XXXXXXXXXo+++++X$++$+++-&+++;---;;-;oO-;o;*@o ",
" .XXXXXXXXXo-++++++-+++;+$++;+--;;;;;;o O-;o;;o ",
" .ooooooooooooooooooooooooooooooooooooo  O-;oo  ",
"                                                "};
