/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * find_file_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor7	m white	c cyan",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor1	m black	c black",
"*	s iconColor6	m white	c yellow",
"=	s iconGray6	m black	c #636363636363",
"-	s iconGray7	m black	c #424242424242",
";	s iconColor3	m black	c red",
/* pixels */
"                                ",
"                                ",
"                                ",
"                  ...........   ",
"                 ..XXXXXXXXXoo  ",
"  ................XXXXXXXXXXXoo ",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOo",
".............................oOo",
".++++++++++++++++++++++++++++oOo",
".++++++++++++++ooooo+++++++++oOo",
".++++++++++++oo@+@+@oo+++++++oOo",
".+++++++++++o@#.....#@o++++++oOo",
".++++++++++o@+#.$.$..#@o+++++oOo",
".++++++++++o@#.$.$.$..#o+++++oOo",
".+++++++++o@+##.###....@o++++oOo",
".+++++++++o@#########..#o@+++oOo",
".+++++++++o@@#######...#o%+++oOo",
".+++++++++o@#+#######.#@o%+++oOo",
".+++++++++o@+#+########@o%+++oOo",
".++++++++++o@#+#####+#+o%+%++oOo",
".++++++++++o@+#$+#++##@o%%+++oOo",
".+++++++++++o@++$+$#+@&.%+%++oOo",
".++++++++++++oo@@@@@oo@&*%+++oOo",
".+++++++++++++%ooooo==-&=#%++oOo",
".++++++++++++++%+%%%%%=&&;*%+oOo",
".+++++++++++++++%+%+%+%=&&=#%oOo",
".OOOOOOOOOOOOOOOOOOOOOOO=&&;*%Oo",
" oooooooooooooooooooooooo=&&=#% ",
"                          =&&;*%",
"                           =&&=o",
"                            =&o-",
"                             ---"};
