/* XPM */
/*********************************************************************
*  Copyright (c) 1995,  Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtfontadmabout_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"96 96 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray4	m white	c #949494949494",
"+	s iconColor3	m black	c red",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray7	m black	c #424242424242",
"%	s iconGray5	m black	c #737373737373",
"&	s iconColor5	m black	c blue",
"*	s iconGray1	m white	c #dededededede",
"=	s iconGray8	m black	c #212121212121",
"-	s iconColor6	m white	c yellow",
/* pixels */
"                         .................................................                      ",
"                         .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo                      ",
"                         .XXXXXXXXXXOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo                      ",
"                         .XXXXXXXXXO+++++XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo                      ",
"                     .................................................XXXo                      ",
"                     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXo                      ",
"                     .XXXXXXXXXXOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXo                      ",
"                     .XXXXXXXXXO+++++XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXo                      ",
"                 .................................................XXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXO+++++XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXO++++++XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO+++@XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXXXXXXXXXXXX@OOXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXXXXXXXXXO#$$$$$#@XXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXOOOO++OOOOOOXXXXXXXXXXX@#$$$#$$$$$OXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXO++++++++++OXXXXXXXXXX@#$$$@X#$$$$$XXXXXXXXoXXXoXXXo                      ",
"                 .XXXXO++++++++++OXXXXXXXXX@$$$$%XX@$$$$$@XXXXXXXoXXXoXXXo                      ",
"                 .XXXXOOOO++OOOOOOXXXXXXXX@#$$$$@XXX#$$$$@XXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXXXX%$$$$%XXXX%$$$$XXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXXXO$$$$$@XXXX@$$$@XXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXXX#$$$$#XXXXXXO%@XXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXX@$$$$$%XXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXXX%$$$$$@XXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXX@$$$$$#XXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXX%$$$$$%XXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXXX#$$$$$@XXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXXXXXXX@$$$$$$XXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXX@OOOO%$$$$$#OOOOOXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXX%$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXX#$$$$$$$$$$$$$$$#XXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXO++OXXXX@OOO%$$$$$#OOOOO@XXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXXX%$$$$$OXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXXX#$$$$$@XXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXX@$$$$$#XXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXXO$$$$$%XXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXX%$$$$$@XXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXXX$$$$$$XXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXX@$$$$$%XXXXXXXXXXXXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXX%$$$$$OXXXXXO%%%%%%%%%%%%XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXX#$$$$$@XXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXX$$$$$#XXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXXO$$$$$%XXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXX%$$$$$@XXXXXX%&&&&%%%%%%%%XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXX#$$$$#XXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXX@$$$$$%XXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXXO$$$$$OXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXX%$$$$$XXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXX$$$$$%XXXXXXXX%&&&&OOOOOOOOXXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXX@$$$$$OXXXXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXXO$$$$$XXXXXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXX#$$$$%XXXXXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXXX$$$$$@XXXXXXXXX%&&&&&&&&&&&&XXXXXoXXXoXXXo                      ",
"                 .XXXXXXXXXXXXX@$$$$$XXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXX@%@XXXX%$$$$OXXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXXO$$#XXXX#$$$$@XXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXX$$$$OXX@$$$$OXXXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXO$$$$$@XO$$$%XXXXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXX@$$$$#X@$$$%XXXXXXXXXXXXX%&&&&XXXXXXXXXXXXXoXXXoXXXo                      ",
"                 .XXXXX$$$$$#$$$#XXXXXXXXXXXXXX%&&&&XXXXXXXXXXXX%%%%%ooooo                      ",
"                 .XXXXX@#$$$$$#OXXXXXXXXXXXXXXX%&&&&XXXXXXXXXX%%*****%=                         ",
"                 .XXXXXXXXOO@XXXXXXXXXXXXXXXXXX%&&&&XXXXXXXXX%******@Oo                         ",
"                #######################%XXXXXXX@OOOOXXXXXXX%%******@@o%                         ",
"              ##************************%XXXXXXXXXXXXXXXX%%*******@@O=                          ",
"            ##***************************%XXXXXXXXXXXXX%%*******@@@O=                           ",
"     %%    #*****************************$%XXXXXXXXXX%%********@@O==                            ",
"    %..%  #******************************o%XXXXXXXX%%*********@OO=%                             ",
"   %....% #***************@@@@@@@@@@@@@%=o%$$$#%%%%*********XOO==%                              ",
"  %......%@**************%$$$$$$$$$$$$$$$$ooo%*************@OO=%                                ",
" %........%@*************%==============******************OOO=                                  ",
"%..........%@******************************************XOOO==                                   ",
"=@*.........%@**************************************XX@OO==                                     ",
" =@*.........%XXX*******************************XXX@@@O==                                       ",
"  =@*.........%XXXX*********************X**XX@@@@@@O===                                         ",
"   =@*.........%@XXXXXXXXXXXXXXXXXXXXXXX@@@@@OOOO===%%                                          ",
"    =@*.........%@@@@@@@@@@@@@@@@@@@@@@@@@@@@O====%%                                            ",
"     =@*.........%OOOOOOOOOOOOOOOOOOOOOOOOOO==%%%%                                              ",
"      =@*.........%oo=oooooooooooooooooooooo%%%                                                 ",
"       =@*.........%%%%%%%%%%%%%%%%%%%%%%%%%                                                    ",
"        =@*.........%                                                                           ",
"         =@*.....@-@.%                                                                          ",
"          =@*...@---@.%                                                                         ",
"           =@*.@--+-+..%                                                                        ",
"            =@*.%+-+%**@%                                                                       ",
"             =@*.%+%**@=                                                                        ",
"              =@*.%**@=                                                                         ",
"               =@***@=                                                                          ",
"                =@*@=                                                                           ",
"                 =@=                                                                            ",
"                  =                                                                             ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
