/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * search_addr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray6	m black	c #636363636363",
"O	s iconColor5	m black	c blue",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor7	m white	c cyan",
"&	s iconColor1	m black	c black",
"*	s iconColor6	m white	c yellow",
"=	s iconGray7	m black	c #424242424242",
"-	s iconGray5	m black	c #737373737373",
";	s iconColor3	m black	c red",
/* pixels */
"  ............................  ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXo ",
" .XXXXXOOXXXXXX+XXXXXXXXXXXXXXo ",
" .XXXXOOOOXXXXooX@@@X@@ooXXXXXo ",
" .XXXXOOOOXXXXXX+XXXXXXXX+XXXXo ",
" .XXXXXOOXXXXXo@oX@@Xo@X@@@XXXo ",
" .XXXXOOOOXXXXXXXX+XX+XX+XXXXXo ",
" .XXXOOOOOOXXX@#####XXoXXXXXXXo ",
" .XXXOOOOOOXX##$+$+$##XXXXXXXXo ",
" .XXXOOOOOOX#$X.....X$#XXXXXXXo ",
" .XXXXXXXXX#$+X.%.%..X$#XXXXXXo ",
" .XXXXXXXXX#$X.%.%.%..X#$XXXXXo ",
" .XXXXXXXX#$+XX.XXX....$#$XXXXo ",
" .XXXXXXoo#$XXXXXXXXX..X#$+XXXo ",
" .XXXXXXo #$$XXXXXXX...X#$$XXXo ",
" .XXXXXXoo#$X+XXXXXXX.X$#$++XXo ",
" .XXXXXXXo#$+X+XXXXXXXX$#$$+XXo ",
"  oooooooo #$X+XXXXX+X+#oooooo  ",
"           #$+X%+X++XX$#        ",
"            #$++%+%X+$&.@       ",
"             ##$$$$$##$&*@      ",
"               #####oo=&oX@     ",
"                ---- -o&&;*@    ",
"                      -o&&oX@   ",
"                       -o&&;*@  ",
"                        -o&&oX@ ",
"                         -o&&;*@",
"                          -o&&o#",
"                           -o&#=",
"                            -==="};
