/* XPM */
/*********************************************************************
*  Copyright (c) 1995,  Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtfontadm_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconColor3	m black	c red",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray6	m black	c #636363636363",
"%	s iconColor5	m black	c blue",
"&	s iconGray1	m white	c #dededededede",
"*	s iconColor6	m white	c yellow",
/* pixels */
"              .........................         ",
"              .XXXXXXXXXXXXXXXXXXXXXXXo         ",
"           .........................XXo         ",
"           .XXXXXXXXXXXXXXXXXXXXXXXoXXo         ",
"        .........................XXoXXo         ",
"        .XXXXXXXXXXXXXXXXXXXXXXXoXXoXXo         ",
"        .XXXXO++@XXXXXXXXXXXXXXXoXXoXXo         ",
"        .XXXX+@OOXXXXXXXXXXXXXXXoXXoXXo         ",
"        .XXXX+@XXXXXXXX@###$OXXXoXXoXXo         ",
"        .XXX++++@XXXXX@##@##$XXXoXXoXXo         ",
"        .XXXX+@OOXXXX$##OX$#$XXXoXXoXXo         ",
"        .XXXX+@XXXXXO###OXO$OXXXoXXoXXo         ",
"        .XXXX+@XXXXX@##$XXXXXXXXoXXoXXo         ",
"        .XXXX+@XXXXX###@XXXXXXXXoXXoXXo         ",
"        .XXXX+@XX#########OXXXXXoXXoXXo         ",
"        .XXXX+@XXOO###$OOOXXXXXXoXXoXXo         ",
"        .XXXX+@XXX@###@XXXXXXXXXoXXoXXo         ",
"        .XXXXXXXXX$###OXXXXXXXXXoXXoXXo         ",
"        .XXXXXXXXO###$XXXXXXXXXXoXXoXXo         ",
"        .XXXXXXXX@###@XXXXXXXXXXoXXoXXo         ",
"        .XXXXXXXX$###OX%%%%%%%OXoXXoXXo         ",
"        .XXXXXXXO###$XX%%%%%%%OXoXXoXXo         ",
"        .XXXXXXX@###@XX%%OOOOOOXoXXoXXo         ",
"        .XXXXXXX$###OXX%%OXXXXXXoXXoXXo         ",
"        .XXXXXXO###$XXX%%OXXXXXXoXXoXXo         ",
"        .XXXXXX@###@XXX%%%%%%%OXoXXoXXo         ",
"        .X@$$XO$##$XXXX%%%%%%%OXoXXoXXo         ",
"        .X$##O@##$XXXXX%%OOOOOOXoXXoXXo         ",
"        .X$##@##$XXXXXX%%OXXXXXXoXXoXXo         ",
"        .X@$###@XXXXXXX%%OXXXXXXoXXoXXo         ",
"        .XXXXXXXXXXXXXX%%OXXXXXXoXXoXXo         ",
"        .XXXXXXXXXXXXXX%%OXXXX@@oXXoooo         ",
"        .XXXXXXXXXXXXXX%%OXX@@$$$XXo            ",
"        $$$$$$$$$$$$@XXXXX@@$$&&&$oo            ",
"      $$&&&&&&&&&&&&$@@@@@$$&&&OOo              ",
"  $$ $&&&&&&&&&&&&&&o$$$$$&&&OOoo               ",
" $..$&&&&&&&@ooooooo#oo&&&&OOoo                 ",
"$....$&&&&&&&&&&&&&&&&&&&OOoo                   ",
" o....$&&&&&&&&&&&&&&&&OOoo                     ",
"  o....$OOOOOOOOOOOOOOOoo                       ",
"   o....$oooooooooooooo                         ",
"    o....$                                      ",
"     o....$                                     ",
"      o.*+.o                                    ",
"       o$$.o                                    ",
"        o.o                                     ",
"         o                                      ",
"                                                "};
