/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * find_file_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray1	m white	c #dededededede",
"$	s iconColor7	m white	c cyan",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor3	m black	c red",
"*	s iconColor6	m white	c yellow",
"=	s iconGray6	m black	c #636363636363",
"-	s iconGray7	m black	c #424242424242",
/* pixels */
"                                                ",
"                          ................      ",
"                          ................      ",
"                         ...XXXXXXXXXXXXooo     ",
"     .....................XXXXXXXXXXXXXXXXooo   ",
"     .....................XXXXXXXXXXXXXXXXooo   ",
"     ..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo  ",
"  ........................................oOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++++++++++++++++++++OOoOOo  ",
"  .+++++++++++++++++++oooooo++++++++++++OOoOOo  ",
"  .+++++++++++++++++oo+@+@+@oo++++++++++OOoOOo  ",
"  .+++++++++++++++oo##.#.#..##oo++++++++OOoOOo  ",
"  .++++++++++++++o++#........#++o+++++++OOoOOo  ",
"  .+++++++++++++o++.#..$..$...##+o++++++OOoOOo  ",
"  .+++++++++++++o+#..$.....$....#o++++++OOoOOo  ",
"  .++++++++++++o++#..#.###..$...#@o+++++OOoOOo  ",
"  .++++++++++++o++###.#####.#....+o+++++OOoOOo  ",
"  .+++++++++++o++#+#########.##..#+o++++OOoOOo  ",
"  .+++++++++++o++#############...#@o++++OOoOOo  ",
"  .+++++++++++o+++###########....#+o++++OOoOOo  ",
"  .+++++++++++o+++############..#+@o++++OOoOOo  ",
"  .+++++++++++o++++###########..#++o++++OOoOOo  ",
"  .+++++++++++o+++#+#############+@o++++OOoOOo  ",
"  .++++++++++++o+++#+###########++o+++++OOoOOo  ",
"  .++++++++++++o+++++#+##+#####++@o+++++OOoOOo  ",
"  .+++++++++++++o+++#$++##+#+#+#@o++++++OOoOOo  ",
"  .+++++++++++++o+++++$+++$++++++oOOOOOOOOoOOo  ",
"  .OOOOOOOOOOOOOOo+++++$$++++++@o#++%ooooooooo  ",
"  oooooooooooooooooo@++++++++@ooo%o&*%ooooooo   ",
"                    oo+@+@+@oo  =oO@&#%         ",
"                      oooooo    =o-&@&*%        ",
"                                =-o-&@&#%       ",
"                                 =-o-&@&*%      ",
"                                  =-o-&@&#%     ",
"                                   =-o-&@&*%    ",
"                                    =-o-&@&#%   ",
"                                     =-o-&@&*%  ",
"                                      =-o-&@&#% ",
"                                       =-o-&@&O ",
"                                        =-o-&@o ",
"                                         =-o--o ",
"                                          =-oo  ",
"                                                "};
