/* XPM */
/*********************************************************************
*  Copyright (c) 1995,  Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtfontadm_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconGray5	m black	c #737373737373",
"#	s iconColor3	m black	c red",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray8	m black	c #212121212121",
"&	s iconColor5	m black	c blue",
"*	s iconGray1	m white	c #dededededede",
"=	s iconColor1	m black	c black",
"-	s iconColor6	m white	c yellow",
/* pixels */
"          .................     ",
"        .................Xo     ",
"      .................XoXo     ",
"      .OOO+@OOOOOOOOOOoXoXo     ",
"      .OOO##OOOOOO+OOOoXoXo     ",
"      .OO+#+OOOOO$$o+OoXoXo     ",
"      .OO###OOOXo@+%$OoXoXo     ",
"      .OO+#+OO+o%XO@+OoXoXo     ",
"      .OO+#OOOX%o+OOOOoXoXo     ",
"      .OO+#O+$ooo$@OOOoXoXo     ",
"      .OO+#OOOoo+OOOOOoXoXo     ",
"      .OOOOOO$ooOOOOOOoXoXo     ",
"      .OOOOOO$%@OOOOOOoXoXo     ",
"      .OOOOOXo%+OOOOOOoXoXo     ",
"      .OOOOOX%$O+&&&OOoXoXo     ",
"      .OOOOOoo$O+&++OOoXoXo     ",
"      .OOOOOoo+O+&OOOOoXoXo     ",
"      .O@oO$%$OO+&&&OOoXoXo     ",
"      .OooXo$OOO+&++OOoXoXo     ",
"      .OX$$XOOOO+&OOOXoXoXo     ",
"      .OOOOOOOOO+&OOX$$$oXo     ",
"  @ X$$$$$$$$$$XOXO$$**+$==     ",
" @+@$+********X$$$$**++==       ",
"@..@X+***XoooooXO**++==         ",
"o...@X+**********++==           ",
" o...@=++++++++++==             ",
"  o...@%=========               ",
"   o...@=                       ",
"    o-#.=                       ",
"     o.=                        ",
"      =                         ",
"                                "};
