/* XPM */
static char * SDtFindProcess_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor3	m black	c red",
"o	s iconColor8	m black	c magenta",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray7	m black	c #424242424242",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconColor2	m white	c white",
"$	s iconColor5	m black	c blue",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor4	m white	c green",
"*	s iconGray6	m black	c #636363636363",
/* pixels */
"               ..               ",
"            .. .. ..            ",
"            .X.XX.X.            ",
"             .X..X.             ",
"           ..X....X..           ",
"       ..  ..X....X..           ",
"    .. .. .. .X..X.             ",
"    .o.oo.o..X.XX.X.            ",
"     .o..o. .. .. ..            ",
"   ..o....o..  ..               ",
"   ..o....o..                   ",
"     .o..o.                     ",
"    .o.oo.o.   O+++++O          ",
"    .. .. ....++OOOOO++         ",
"       .. . .+O@#@#@#OO+        ",
"         .$.$+@#######O+        ",
"          .$+O%%%#%%###O+       ",
"        ..$.+O@%%%%#%%#O+       ",
"    ..  ..$.+O%%%%%%%##O+       ",
" .. .. .. .$+O@%%%%%%%#O+       ",
" .&.&&.&..$.+O%%%%%%%%#O+       ",
"  .&..&.  . .+@%%%%%%%@+O       ",
"..&....&..  .+O@%@%@%@+++       ",
"..&....&..    ++OOOOO++XX+      ",
"  .&..&.       O+++++O*@XX+     ",
" .&.&&.&.              *@XX+    ",
" .. .. ..              +*@XX+   ",
"    ..                  +*@XX+  ",
"                         +*@XX+ ",
"                          +*@XX+",
"                           +*@X+",
"                            +*++"};
