/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * websearch_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 16 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray6	m black	c #636363636363",
"+	s iconColor5	m black	c blue",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor7	m white	c cyan",
"&	s iconGray4	m white	c #949494949494",
"*	s iconGray7	m black	c #424242424242",
"=	s iconColor3	m black	c red",
"-	s iconColor6	m white	c yellow",
";	s iconColor1	m black	c black",
":	s iconColor4	m white	c green",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XOoOXXoOoOXXoOoOXXoOXXXo.......",
" XXoXoOoXoXoOoXoXoOoXXXXo.......",
" XXooooOXooooOXooooOXXXXo.......",
" XXoOoOXXoOoOXXoOoOXXXXXo.......",
" XXoXoXXXoXoXXXoXoXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXoooooXXXXo.......",
" XXoX+@+@X+XXooX#X#XooXXo.......",
" XXXXXXXXXXXo$#     #XoXo.......",
" XXOooXo@XXo$X# % %  #Xo&.......",
" XXXXXXXXXXoX# % % %  Xoo.......",
" XXOooXOXXo$X## ###    Xo.......",
" XXXXXXXXXo$#########  #o.......",
" XXXooXoXXo$X#######   #o.......",
" XXXXXXXXXo$#X####### #Xo.......",
" XXOoXooXXo$X#X########Xo.......",
" XXXXXXXXXXoX#X####X##Xoo.......",
" XXXXXXXXXXo$X%X#XX###$o&.......",
" XXXXXXXXO**oX#%X%##X$$ &.......",
" XXXXXXX*X&X#ooXXXXXooo=-&......",
" XXXXXXX*#X# #Xooooo&O;;O#&.....",
" XXXXXX*XX ###:%X%&&:$O;;=-&....",
" XXXXXX*XXX#:XXX%X&O:&%O;;O#&...",
" XXXXX*X#X#XX%XX&&&%&:XoO;;=-&..",
" XXXXX*&+%+:%X&&&&%&:O%o.O;;O#&.",
" XXXXX*&&X&&&&X&&%&%OXOo..O;;=-&",
" XXXXX*&+&XXX&&%X&%+O+@o...O;;Oo",
" XXXXX*&&+&&&&XO*%&%X@Oo....O;o*",
" ooooooooooooooooooooooo.....**."};
