/* XPM */
static char * Gears_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor3	m black	c red",
"o	s iconColor8	m black	c magenta",
"O	s iconColor5	m black	c blue",
"+	s iconColor4	m white	c green",
/* pixels */
"                                                ",
"                                                ",
"                                .               ",
"                               .X.              ",
"                           .   .X.   .          ",
"                          .X.. .X. ..X.         ",
"                           .XX.XXX.XX.          ",
"                           .XXXXXXXXX.          ",
"                            .XX...XX.           ",
"                    .    ...XX.....XX...        ",
"                   .o.  .XXXXX.....XXXXX.       ",
"               .   .o.   ...XX.....XX...        ",
"              .o.. .o. ..o. .XX...XX.           ",
"               .oo.ooo.oo. .XXXXXXXXX.          ",
"               .ooooooooo. .XX.XXX.XX.          ",
"                .oo...oo. .X.. .X. ..X.         ",
"             ...oo.....oo...   .X.   .          ",
"            .ooooo.....ooooo.  .X.              ",
"             ...oo.....oo...    .               ",
"                .oo...oo.                       ",
"               .ooooooooo.                      ",
"               .oo.ooo.oo.  .                   ",
"              .o.. .o. ..o..O.                  ",
"               .   .o. . . .O.   .              ",
"                   .o..O.. .O. ..O.             ",
"                    .  .OO.OOO.OO.              ",
"                       .OOOOOOOOO.              ",
"                        .OO...OO.               ",
"                     ...OO.....OO...            ",
"               .    .OOOOO.....OOOOO.           ",
"              .+.    ...OO.....OO...            ",
"          .   .+.   .   .OO...OO.               ",
"         .+.. .+. ..+. .OOOOOOOOO.              ",
"          .++.+++.++.  .OO.OOO.OO.              ",
"          .+++++++++. .O.. .O. ..O.             ",
"           .++...++.   .   .O.   .              ",
"        ...++.....++...    .O.                  ",
"       .+++++.....+++++.    .                   ",
"        ...++.....++...                         ",
"           .++...++.                            ",
"          .+++++++++.                           ",
"          .++.+++.++.                           ",
"         .+.. .+. ..+.                          ",
"          .   .+.   .                           ",
"              .+.                               ",
"               .                                ",
"                                                ",
"                                                "};
