/* XPM */
static char * Gears_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor3	m black	c red",
"o	s iconColor8	m black	c magenta",
"O	s iconColor5	m black	c blue",
"+	s iconColor4	m white	c green",
/* pixels */
"                                ",
"                                ",
"                     ..         ",
"                  .. .. ..      ",
"                  .X.XX.X.      ",
"                   .X..X.       ",
"                 ..X....X..     ",
"             ..  ..X.......     ",
"          .. .. .  .X..X.       ",
"          .o.oo.o..X.XX.X.      ",
"           .o..o. .. .. ..      ",
"         ..o....o..  ..         ",
"         ..o....o..             ",
"           .o..o.               ",
"          .o.oo.o.              ",
"          .. .. ....            ",
"             .. . .. ..         ",
"               .O.OO.O.         ",
"                .O..O.          ",
"              ..O....O..        ",
"          ..  ..O....O..        ",
"       .. .. .. .O..O.          ",
"       .+.++.+..O.OO.O.         ",
"        .+..+.  . .. ..         ",
"      ..+....+..  ..            ",
"      ..+....+..                ",
"        .+..+.                  ",
"       .+.++.+.                 ",
"       .. .. ..                 ",
"          ..                    ",
"                                ",
"                                "};
