/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * host_object_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray5	m black	c #737373737373",
"#	s iconColor7	m white	c cyan",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray7	m black	c #424242424242",
"&	s iconColor5	m black	c blue",
"*	s iconColor8	m black	c magenta",
"=	s iconGray4	m white	c #949494949494",
"-	s iconColor4	m white	c green",
";	s iconColor1	m black	c black",
/* pixels */
"   .........................X   ",
"  .ooooooooooooooooooooooooooX  ",
"  .oOOOOOOOOOOOOOOOOOOOOOOOOoX  ",
"  .oOXXXXXXXXXXXXXXXXXXXXXX.oX  ",
"  .oOXOOOOOOOOOOOOOOOOOOOOX.oX  ",
"  .oOXO+++++++++OOOOOOOOOOX.oX  ",
"  .oOXO+@@@@@@@+XOOOOOOOOOX.oX  ",
"  .oOXO+#.#.#.#+XOOOOOOOOOX.oX  ",
"  .oOXO+.#.#.#.+XOOOOOOOOOX.oX  ",
"  .oOXO+#.#.#$$$$$$$$$$$$OX.oX  ",
"  .oOXO+.#.#.$$$$$$$$$$$$OX.oX  ",
"  .oOXO++++++$..........$XX.oX  ",
"  .oOXOOXXXXX$.%.%.%.%..$XX.oX  ",
"  .oOXOOOOOOO$..........$XX.oX  ",
"  .oOXOOOOOOO$.%.%.%....$XX.oX  ",
"  .oOXOOOOOOO$..........$XX.oX  ",
"  .oOXOOOOOOO$$$$$$$$$$$$XX.oX  ",
"  .oOXOOOOOOOOXXXXXXXXXXXXX.oX  ",
"  .oOXXXXXXXXXXXXXXXXXXXXXX.oX  ",
"  .oO.......................oX  ",
"  .ooooooooooooooooooooooooooX  ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"        @@OOO@@OOOOOOOO         ",
"        XXXXXXXXXXXXXXX         ",
"..............................$ ",
".oooooooooooooooooooooooooooooXO",
".oo&ooo$ooooooooooooooooooooooXO",
".o&*&o&=&=ooooooooo==o===oo-ooXO",
".oo&oooooooooooooooooooooooo=oXO",
".oooooooooooooooooooooooooooooXO",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO",
" XXXXXOOOOOOOOOOOOOOOOOOOXXXX;% "};
