/* XPM */
static char * hjava_t_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"16 16 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconColor1	m black	c black",
"+	s iconColor4	m white	c green",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor7	m white	c cyan",
"%	s iconColor5	m black	c blue",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray5	m black	c #737373737373",
"=	s iconGray8	m black	c #212121212121",
/* pixels */
"      ..XXXXXX  ",
"    ..oXOOOOO X ",
"  XXXoXO+@@#O XO",
"XXOOOOXOooo###O ",
"XO .@oXO$o%#OO  ",
"XO .$+oXOo##.O  ",
" XO.@o@#XO##%O  ",
"  XO.@@.XO#.O   ",
"    O.@.XO..O   ",
"   X....OOO&X   ",
"   #&XXXX&&&&O  ",
"   O*#&&&*#.=O  ",
"    O.**#@.=O   ",
"  X&OO...O==    ",
"  #X&&&&&**##.  ",
"  ##OOOOOOOOO   "};
