/* XPM */
/*********************************************************************
*  Copyright (c) 1999, 2000 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * hotkey_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray4	m white	c #949494949494",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor1	m black	c black",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                     .Xo              oXX.      ",
"                    .ooX..............Xoo.      ",
"                   .oOOOOoOOoOoO+O+O+OO+X@#     ",
"                   .Oo$$$OO.$OO+$+O+OO+X@@#     ",
"                  .oO$oO$OO$.o$@@$.OOO+@..@#    ",
"                 .oo$$$$$O.$oOo$o+O%O+X@..@#    ",
"                .Oo$oOOO$O$.Oo$oO$+O+X@....@#   ",
"               .oo$oOOOO$o$oO.$$$+OO+@.....@#   ",
"              .XOOOOoOOOOOoO+O+%+OO%@@......@#  ",
"             .XoOOOOOOOOO+%+OOO+%++X@......@@#  ",
"             ....o%%%%%%%%%%%%%%o...@........@# ",
"             .XoX................XoX@....@.@.@# ",
"            o.ooooXoXoXoXoXoXoXooooo.@....@.@@@#",
"            .Xoooooooooooooooooooooo.@.@...@.## ",
"            .ooooooooooooooooooooooo.@..@.@.@@# ",
"            .XooooooooooooooooooooooX.@..@.#@#  ",
"            .oooooXoooooXoooooXooooXo.@.@.@@#   ",
"           XXXoXoooooXoooooXXXXXoXooXX@@@@#@#   ",
"          XoXXXXXXXXXXXXXXXXo%+.XooXoX@@.@@#    ",
"         XoO%O%%O%%O%%+%+%+%%+%o@XXoXX.@@@#     ",
"         XOO%o$$$$$%%+%+%+%++oXX@XoXXo.@#@#     ",
"        Xo%o@$.%%%o$+%+%+%%%+oXXX@XXXX.@@#      ",
"       XoOo$$%%%+%O%%+%+%+%+oXXXX@XXXXX@##      ",
"      XOO%$$%O%O%%%%+%+%+%++XXXXXX#######       ",
"     XoO%%$$%%%%@$%+%+%+%%+XXXXXXX@             ",
"    XoOO%Oo$$$$@o%+%+%+%%+%.XXXXXX.#            ",
"   XXo%%%%O%O%%+%+%%%++++X.XXXXXX.X#            ",
"   XXXXoo%++++++++++++oXXX.XXXXXXX.@#           ",
"   XoooXXXXXXXXXXXXXXXXooo.XXXX.X.X.#           ",
"  oXOOOooooooooooooooOOOOO.XXX.X.@.@.#          ",
"  XoOOOOOOOOOOOOOOOOOOOOOO..X.XX..@.#           ",
"  XoOOOOOOOOOOOOOOOOOOOOOOX@XX.@.@.@#           ",
"  XoOOOOOOOOOOOOOOOOOOOOOOX@.X..@.@#            ",
" oXOOOOOoOOOOOoOOOOOoOOOOoOX@.@@.@#             ",
" XoOOoOOOOOoOOOOOoOOOOOoOOoX@@.@.@#             ",
" XoOoOOoOOoOOoOOoOOoOOoOOoOo@.@.@#              ",
" XooOooOooOooOooOooOooOooOoo.@.@#               ",
"oXoOooOooOooOooOooOooOooOooO.@@.#               ",
"X.oooooooooooooooooooooooooo.@.#                ",
"Xoooooooooooooooooooooooooooo@@#                ",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##                 ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
