/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * host_object_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray8	m black	c #212121212121",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray4	m white	c #949494949494",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor7	m white	c cyan",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconColor5	m black	c blue",
"=	s iconColor8	m black	c magenta",
"-	s iconColor4	m white	c green",
";	s iconColor1	m black	c black",
/* pixels */
"                                                ",
"                                                ",
"      ...................................X      ",
"     .ooooooooooooooooooooooooooooooooooooX     ",
"     .ooooooooooooooooooooooooooooooooooooX     ",
"     .ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ooX     ",
"     .ooOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.ooX     ",
"     .ooOX@@@@@@@@@@@@@@@@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@@@@@@@@@@@@@@@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@############@@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@#@@@@@@@@@@#$@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@#@@@@@@@@@@#$@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@#%.%.%.%.%.#$@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@#.%.%.%.%.%#$@@@@@@@@@@@@@X.ooX     ",
"     .ooOX@@#%.%.%.%&&&&&&&&&&&&&&&&@@X.ooX     ",
"     .ooOX@@#.%.%.%.&&&&&&&&&&&&&&&&$@X.ooX     ",
"     .ooOX@@#%.%.%.%&&&&&&&&&&&&&&&&$@X.ooX     ",
"     .ooOX@@########&..............&X@X.ooX     ",
"     .ooOX@@@$$$$$$$&..XX.X.XX.....&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&..............&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&..X.XX.X.X....&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&..............&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&..XX.XX.X.....&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&..............&X@X.ooX     ",
"     .ooOX@@@@@@@@@@&&&&&&&&&&&&&&&&X@X.ooX     ",
"     .ooOX@@@@@@@@@@@XXXXXXXXXXXXXXXX@X.ooX     ",
"     .ooOX@@@@@@@@@@@@@@@@@@@@@@@@@@@@X.ooX     ",
"     .ooOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.ooX     ",
"     .oo+...............................ooX     ",
"     .ooooooooooooooooooooooooooooooooooooX     ",
"     .ooooooooooooooooooooooooooooooooooooX     ",
"      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      ",
"               @OOOOOOOOOOOOOOOO                ",
"             @@@$$$$$$$$$$$$$$OOOO              ",
"             XXXXXXXXXXXXXXXXXXXXX              ",
"  ..........................................&   ",
"  .oooooooooooooooooooooooooooooooooooooooooXO  ",
"  .oooooooooooooooooooooooooooooooooooooooooXO  ",
"  .ooo*oooo@oooooooooooooooooo&&&&&&&&ooooooXO  ",
"  .oo*=**o**+*+ooooooooooooooo&O&O&O&&oo-&ooXO  ",
"  .ooo*ooooooooooooooooooooooo&&&&&&&&oo&+ooXO  ",
"  .oooooooooooooooooooooooooooooooooooooooooXO  ",
"  .oooooooooooooooooooooooooooooooooooooooooXO  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO  ",
"   XXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXX;$$   ",
"   $$$$$$$                          $$$$$$$$    ",
"                                                ",
"                                                "};
