/* XPM */
static char * hjava_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconColor1	m black	c black",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray4	m white	c #949494949494",
"+	s iconColor7	m white	c cyan",
"@	s iconColor2	m white	c white",
"#	s iconColor4	m white	c green",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray6	m black	c #636363636363",
"&	s iconColor5	m black	c blue",
"*	s iconGray5	m black	c #737373737373",
"=	s iconGray8	m black	c #212121212121",
/* pixels */
"                    .XXXXXXXXX.                 ",
"                  XXoOOooOO+O@@@@@@@@@@         ",
"                XXoo@@@o#o@@@@XXXXXXXO@@@       ",
"               XOo@@@@@@@@@@XXo+OO$X XXX@@      ",
"              XOO@@@@@@@@@@X$$ooO$OOX    @@     ",
"             X@@@@@@@@@@@@X%o+o+O+%+OX    @     ",
"           @@@@@@@@@@@@@@Xo+o%+oO%$%%%X    @    ",
"         @@@@OO@$@@@@@@@XOoooooO%#%%%%X    @X   ",
"       @@@XXO+o@@@@@@@@@X@@+OO+OOO+%..%X   @X   ",
"      @@XX XOoooo@@@o@@X$O+oOOoO+OO%..%X  @X    ",
"     @@X  .O%oo+@o@o@@@X$#o%oooo%OO%OO%X. @     ",
"     @X   XO%$$oo+$$o@@X$$ooooOO+OO%%.%.X@X     ",
"    @@X   XO%$$oo+$$@@.$$$ooooOoOO%%..&.XX      ",
"    @X    XO%+OoOooo@@X+o+oOOOOOO.O.%%%.X       ",
"    @X    XOOOOooo#+@@XO%OOo%OOOO@@@@@..X       ",
"    @X    X%OOOo+ooo@@XOOOO+OOO@@@XXXX%.X       ",
"    @X    XO$O+Oo@XOO@@%O%%OOO@@XX.&.%..X       ",
"    @X    XOOOOOo@XO+O@@%&OOOO@X%..%....X       ",
"     @    X%OOOOO$@OO.OO@@O.O%@X........X       ",
"     @    X%OOOOO+$@O..OO@@O%%@@.&..&..XX       ",
"      @   ..%&&O&#.@$OOOOO@@X%&@X.....XX.       ",
"       @ooOX.OO%%%+%@X$%%.%@X%.@@X.X.XXX        ",
"         ..X%%%%%&%%@X%%..O@X...@X...XXX        ",
"            X%%%O%O.@X%%%%@X%.%%@XX.XXX         ",
"            X&%%%&.%@X....@X%%&@@X.XXXX         ",
"             X%%%%.&@X.%.@X%...@X.XXXX          ",
"              X%..%@XX..%@X..&@@XXXXX           ",
"               X&%%@X...@X..X@@XXXXX            ",
"             @@OXX@XX.%@X.X.@@XXXXX             ",
"           @@*****@XX.@X.X.@@XXXX               ",
"          @@@*****@X.@XXXX@@XX.O%$$$@%          ",
"          $@@@@******@XOOOOOO$$@%%%%@$%=        ",
"          $$$$$@@@@@@@@@@@@@$$$=%===$O%=        ",
"           $$$$$$$$$$$$$$$$$$*$====OO%==        ",
"           ***$$$$$$$$$$$$$$%*%%==OO%%==        ",
"           *%****$$$$$$$$%%%%%%==OO%%==         ",
"            %%*************%...==O%===          ",
"            .%%%**********%%.X==%====           ",
"             .%%%%*****%%%....=X===             ",
"             X..%%%%%%%%.....==X=               ",
"       $@@@$$XXX...........===X%                ",
"     $@@...%%XXXXX......====XXX.XXX.            ",
"     @@......%XXXXXXXXXXXXXXX..%%..XX.          ",
"     $@@$%......XXXXXXXXXXXX......$XXX          ",
"     %%$@@@@$$..................$XXXX.          ",
"       %XXXXX$$$$$$$$$%%%%%%%%%XXXXX.           ",
"          XXXXXXXXXXXXXXXXXXXXXXXXX             ",
"           %%XXXXXXXXXXXXXXXXXX%                "};
