/* XPM */
static char * ins_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s topShadowColor	m white	c #bdbdbdbdbdbd",
"X	s iconGray6	m black	c #636363636363",
"o	s iconGray5	m black	c #737373737373",
"O	s iconColor7	m white	c cyan",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconColor1	m black	c black",
"$	s iconGray1	m white	c #dededededede",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor2	m white	c white",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconGray7	m black	c #424242424242",
"-	c #00000000FFFF",
";	s iconColor6	m white	c yellow",
":	c #0000FFFF0000",
/* pixels */
"          ..........X           ",
"          .oooooooooX           ",
"        ...oOOOOOOOoXXX         ",
"       .ooooOOOOOOOooooX        ",
"       .+OOOOOOOOOOOO@+X        ",
"        .#$O$O$O$O$O$+X         ",
"     .....+@O@O@O@O@+XXXXX      ",
"    .%XXXX&+%O%O%O%+XXXXX*X     ",
"    .X%%%%%&+oOoOo+%%%%%%=X     ",
"    .X%%%%%%&+oOo+%%%%%%%=X     ",
"    .X%%#++#=&+o+++++++o%=X     ",
"    .X%%#---+;;++;+----$%=X     ",
"    .X%%+-o-+;;;;;+-o-o$%=X     ",
"    .X%%#-+++;;;;;++++o$%=X     ",
"    .X%%#+$;$;$;$;$;$+o$%=X     ",
"    .X%%+-+o;@;@;@;%+=o$%=X     ",
"    .X%%#--+o;%;*;%+=-o$%=X     ",
"    .X%%#-X-+X;%;X+X-Xo$%=X     ",
"    .X%%#--X-+X;o+X-X-o$%=X     ",
"    .X%%+-X-X-+=+X-X-Xo$%=X     ",
"    .X%%+oooooo+ooooooo$%=X     ",
"    .X%%%$$$$$$$$$$$$$$$%=X     ",
"    .X%%%%%%%%%%%%%%%%%%%=X     ",
"    .%ooXXXXXXXXXXXXXXXXo%X     ",
"     ...#++++++++++++++...      ",
"    .%XXXXXXXXXXXXXXXXXXX%X     ",
"    .X%%%%%%%%%%%%%%%%%%%=X     ",
"    .X%%%%%%%%%%%%%%%%:X%=X     ",
"    .X%%%%%%%%%%%%%%%%XX%=X     ",
"    .X%%%%%%%%%%%%%%%%%%%=X     ",
"    .+++++++++++++++++++++X     ",
"    .++++++         ++++++X     "};
