/* XPM */
static char * ins_gif_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s iconGray1	m white	c #dededededede",
".	s iconGray2	m white	c #bdbdbdbdbdbd",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray6	m black	c #636363636363",
"+	s iconColor7	m white	c cyan",
"@	s iconGray4	m white	c #949494949494",
"#	s iconColor2	m white	c white",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor1	m black	c black",
"&	c #00000000FFFF",
"*	s iconColor6	m white	c yellow",
"=	c #0000FFFF0000",
/* pixels */
"                .X.X.X.X.X.X.X.oO               ",
"                .X+++++++++++++oO               ",
"                .X+++++++++++++oO               ",
"            .....X+++++++++++++oOOOOOOO         ",
"           .XXXXXX+++++++++++++XXXXXXXO         ",
"           .o+++++++++++++++++++++++ooO         ",
"            .o+ + + + + + + + + + +ooO          ",
"             .o+.+.+.+.+.+.+.+.+.+ooO           ",
"              .o+@+@+@+@+@+@+@+@+ooO            ",
"        ........o+X+X+X+X+X+X+X+ooOOOOOOO       ",
"       .@OOOOOOO#o+X+X+X+X+X+X+ooOOOOOOO@O      ",
"       .O@@@@@@@@#o+O+O+O+O+O+oo@@@@@@@@$O      ",
"       .O@@@@@@@@@#o+O+O+O+O+oo@@@@@@@@@$O      ",
"       .O@@@@@@@@@@#o+O+O+O+oo@@@@@@@@@@$O      ",
"       .O@@@%%%%%%%%#o+O+O+oo%%%%%%%@@@@$O      ",
"       .O@@@%$$$$$$$$#o+O+oo$$$$$$$$@@@@$O      ",
"       .O@@@%$&&&&&o**#$+oo**o&&&&&& @@@$O      ",
"       .O@@@%$&X&X&o***#oo***o&X&X&X @@@$O      ",
"       .O@@@%$&&X&Xo****#****oX&X&XX @@@$O      ",
"       .O@@@%$&ooooo*********ooooo&X @@@$O      ",
"       .O@@@%$&o*****************oXX @@@$O      ",
"       .O@@@%$&Xo* * * * * * * *oX&X @@@$O      ",
"       .O@@@%$&&Xo*.*.*.*.*.*.*oX&XX @@@$O      ",
"       .O@@@%$&X&Xo*@*@*@*@*@*oX&X&X @@@$O      ",
"       .O@@@%$&&X&Xo*X*X*X*X*oX&X&XX @@@$O      ",
"       .O@@@%$&X&X&Xo*X*X*X*oX&X&X&X @@@$O      ",
"       .O@@@%$&&X&X&Xo*O*O*oX&X&X&XX @@@$O      ",
"       .O@@@%$&X&X&X&Xo*O*oX&X&X&X&X @@@$O      ",
"       .O@@@%$&&X&X&X&Xo*oX&X&X&X&XX @@@$O      ",
"       .O@@@%$&X&X&X&X&XoX&X&X&X&X&X @@@$O      ",
"       .O@@@%$&XXXXXXXXXXXXXXXXXXXXX @@@$O      ",
"       .O@@@@@                       @@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$OO      ",
"        OOOOoooooooooooooooooooooooooOOOO       ",
"        ....ooooooooooooooooooooooooo....       ",
"       .@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@=O@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@OO@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .O@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@$O      ",
"       .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O      ",
"       .ooooooooo%%%%%%%%%%%%%%%oooooooooO      ",
"       .%%%%%%%%%%              %%%%%%%%%O      "};
