/* XPM */
static char * music_l_pm[] = {
"49 48 6 1",
" 	c #C0C0C0C0C0C0",
".	c #808080808080",
"X	c #FFFFFFFFFFFF",
"o	c #FFFFFFFF0000",
"O	c #000000000000",
"+	c #808080800000",
"          ..............                         ",
"         .XXXXXXXXXXXXXX.                        ",
"         .XXXXXXXXXXXXXX.                        ",
"       ..X.. oo oo oo oo ..                      ",
"      .XX OOO  o  o  o  o  .                     ",
"      .XX OOO  o  o  o  o  .                     ",
"    ..   OOOO               ..................OO ",
"    ..X  O   ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOO",
"    ..X  O   ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOO",
"    ..X  OXXXOO oo oo oo oo oo oo oo oo oo oo ++O",
"    ..XOO XX OOo  o  o  o  o  o  o  o  o  o  o++O",
"    ..XOO XX OOo  o  o  o  o  o  o  o  o  o  o++O",
"    ..XOO XXOOO oo oo oo oo oo oo oo oo oo oo ++O",
"    ..X.. ..O..o  o  o  o  o  o  o  o  o  o  o++O",
"    ..X.. ..O..o  o  o  o  o  o  o  o  o  o  o++O",
"    ..X  OOOOoo oo oo oo oo oo oo oo oo oo oo ++O",
"    ..X..OOOO  o  o  o  o  o  o  o  o  o  o  o++O",
"    ..X..OOOO  o  o  o  o  o  o  o  o  o  o  o++O",
"    ..XOOOOO oo oo oo oo oo oo oo oo oo oo oo ++O",
"    ..OOOO  o  o  o  o  o  o  o  o  o  o  o  o++O",
"    ..OOOO  o  o  o  o  o  o  o  o  o  o  o  o++O",
"    OOOOOO   oo oo oo oo oo oo oo oo oo oo oo ++O",
"   .OOO  X..o  o  o  o  o  o  o  o  o  o  o  o++O",
"   .OOO  X..o  o  o  o  o  o  o  o  o  o  o  o++O",
"   OOO XXXOO.   oo oo oo oo oo oo oo oo oo oo ++O",
"   OOOX  OOOOOOO  o  o  o  o  o  o  o  o  o  o++O",
"   OOOX  OOOOOOO  o  o  o  o  o  o  o  o  o  o++O",
" OOOXXXOOOOOOOOO.. oo oo oo oo oo oo oo oo oo ++O",
" OOOXX OO    XXOOOo  o  o  o  o  o  o  o  o  o++O",
" OOOXX OO    XXOOOo  o  o  o  o  o  o  o  o  o++O",
"   OXXXOOXXX XX OO oo oo oo oo oo oo oo oo oo ++O",
"   OXXXOOXXX.XX OOo  o  o  o  o  o  o  o  o  o++O",
"   OXXXOOXXX.XX OOo  o  o  o  o  o  o  o  o  o++O",
"    ..X  OXX.XXOOO oo oo oo oo oo oo oo oo oo ++O",
"    OO.XXXXX.OOO++++++++++++++++++++++++++++++++O",
"    OO.XXXXX.OOO++++++++++++++++++++++++++++++++O",
"       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO ",
"             OO                                  ",
"             OO                                  ",
"             OO                                  ",
"       OO.   OO                                  ",
"       OO.   OO                                  ",
"      OOOO   OO                                  ",
"      OOOO   OO                                  ",
"      OOOO   OO                                  ",
"      OOO    OO                                  ",
"       ..OOO.                                    ",
"       ..OOO.                                    "};
