/* XPM */
static char * music_m_pm[] = {
"33 32 6 1",
" 	c #C0C0C0C0C0C0",
".	c #808080808080",
"X	c #FFFFFFFFFFFF",
"o	c #FFFFFFFF0000",
"O	c #000000000000",
"+	c #808080800000",
"       .........                 ",
"      .XXXXXXXXX.                ",
"     .X. o o o o .               ",
"    .X OO o o o o .              ",
"   .  OOO          ............O ",
"   .X O  .XXXXXXXXXXXXXXXXXXXXXOO",
"   .X OXXO o o o o o o o o o o +O",
"   .XO X Oo o o o o o o o o o o+O",
"   .XO XOO o o o o o o o o o o +O",
"   .X. .O.o o o o o o o o o o o+O",
"   .X OOOo o o o o o o o o o o +O",
"   .X.OOO o o o o o o o o o o o+O",
"   .XOOO o o o o o o o o o o o +O",
"   .OOO o o o o o o o o o o o o+O",
"   OOOO  o o o o o o o o o o o +O",
"  .OO X.o o o o o o o o o o o o+O",
"  OO XXO.  o o o o o o o o o o +O",
"  OOX OOOOO o o o o o o o o o o+O",
" OOXXOOOOOO. o o o o o o o o o +O",
" OOX O   XOOo o o o o o o o o o+O",
"  OXXOXX X O o o o o o o o o o +O",
"  OXXOXX.X Oo o o o o o o o o o+O",
"   .X OX.XOO o o o o o o o o o +O",
"   O.XXX.OO+++++++++++++++++++++O",
"     OOOOOOOOOOOOOOOOOOOOOOOOOOO ",
"         O                       ",
"         O                       ",
"     O.  O                       ",
"    OOO  O                       ",
"    OOO  O                       ",
"    OO   O                       ",
"     .OO.                        "};
