/* XPM */
static char * music_t_pm[] = {
"16 16 5 1",
" 	c #C0C0C0C0C0C0",
".	c #FFFFFFFFFFFF",
"X	c #000000000000",
"o	c #808080808080",
"O	c #808080800000",
"   .....        ",
"  .X            ",
" o  o..........X",
" oX.X          O",
" oooo          O",
" ooX           O",
" oX            O",
" X o           O",
" X XX          O",
"X.X .X         O",
" .X..X         O",
" X..XOOOOOOOOOOO",
"    X           ",
"  X X           ",
"  X X           ",
"  oX            "};
