/* XPM */
static char * DtdotJava_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconColor5	m black	c blue",
"+	s iconColor7	m white	c cyan",
"@	s iconGray6	m black	c #636363636363",
"#	s iconGray4	m white	c #949494949494",
"$	s iconColor4	m white	c green",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray5	m black	c #737373737373",
"=	s iconGray1	m white	c #dededededede",
"-	s iconGray8	m black	c #212121212121",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXX  oXooXXXo.......",
" XXXXXXXXXXXXXX oXXXXXXXo.......",
" XXXXXXXXXXXXXXoXXXXXXXXo.......",
" XXXX   XXXXXX oXXXXXXXXo.......",
" XX  ooXXXXXXX oXXXXXXOXo.......",
" X oXXXXXXXXXXo+XXXX@O+Xo.......",
" X oXXXXXXXXXXo#XXXX$XXXo.......",
"  oXXXXX+XXXX o#XXX$@+XXo.......",
"  oXXXXXX#XXX o+XXX@XXXXo.......",
"  oXXXXX#XXXXX oXXX@ XXXo.......",
"  oXXXXXX#XXXX o#X+ oXXXo.......",
" X XXXXXX+#XXX# oXXo@XXXo.......",
" X oX%XXX# oXXX oXXo%XXXo.......",
" XX &&oXX+ oXX+@ XXo@XXXo.......",
" XXXoooXX%$ XXX@ XX oXXXo.......",
" XXXXXXoXX%XXXX o%% oXXXo.......",
" XXXXXXo%%# XXX oO% oXXXo.......",
" XXXXXXXooO o% o@% o%oXXo.......",
" XXXXXX     o  o& oooXXXo.......",
" XXXX  *** o* o* o&@   @o.......",
" XXXX&   *** o* o*= &&@&o.......",
" XXXXX&&&        =&@-#&@o.......",
" XXXXX**&&&&&&&&&&&*#@@-o.......",
" XXXXXX***********%o@@-Xo.......",
" XXXXXX%@@****@@%%oo--XXo.......",
" XXXXXXo%%@@@@@%%ooo@XXXo.......",
" XX   ooo%%%%%%%-oo@@o-Xo.......",
" X &%%%%oooo---oo-%@@%-oo.......",
" X@&   &&&@@@@@@@@%%ooooo.......",
" XX@ooo-----oooooooooooXo.......",
" oooooooooooooooooooooooo......."};
