/* XPM */
static char * DtStart_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconColor5	m black	c blue",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray7	m black	c #424242424242",
"@	s iconColor2	m white	c white",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor1	m black	c black",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"    .......                     ",
"   .XXXXXXX.                    ",
"  .XXoXoXoXO.                   ",
" .XOXOXOXOXO+.................  ",
" .XoXoXoXoXO+@@@@@@@@@@@@@@@@@. ",
" .XOXOXOXOXO+##################.",
" .Xo.###XoXO+XXXX@@XXXXXXX@@XXX.",
" .XO#OOOXOXO+$$$$$$$$$$$$$$$###.",
" .Xo#OO XoXO+XXXXXXXXXXXXXXXXO% ",
" .XO#O  XOXO+XX@@@X@@@@@XX@OO%  ",
" .Xo#OO XoXO+XX@##@@@###@@O#%   ",
" .XO#O  XOXO+X@####@##%%###%    ",
" .XoXXXXXoXO+@##%%###% %%%%     ",
" .XOXOXOXOXO###%  %%%           ",
" .XoXoXoXoXO#%%                 ",
" .XOXOXOXOXO#%                  ",
"  .oXoXoXoXO#%                  ",
"   %########%                   ",
"    %%%%%%%%                    ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
