/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_mgr_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray1	m white	c #dededededede",
"+	s iconColor1	m black	c black",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor6	m white	c yellow",
"&	s iconColor2	m white	c white",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor7	m white	c cyan",
"-	s iconColor3	m black	c red",
";	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"             .............                      ",
"            .XXXoOOOOOOOoX.                     ",
"            .XXXoOOOOO+OoXX.                    ",
"            .XXXoOOOOO+OoXX.                    ",
"            .XXXoOOOOO+OXXX.                    ",
"        oooooooXXXXXXXXX............            ",
"      oo@OOOO@#oXXXXXXX.oX.XoOOOOo$X+           ",
"     o@%OOOOOOO@oXXXXX.XoX.XoOOOOo$Xo+          ",
"    o@&O%OOOOO&@@o@@@@.XoX.XXooooo$Xo+          ",
"****o=&&O%OOO%&O@o@@@@.XoXX$$$$$$$$Xo+          ",
"***o@O=O&@XX@&OO@#o@@@.XoXXXXXXXXXXXo+          ",
"***oOOO=@#&&X@OO@@o@@@.XoXXXXXXXXXXXo+          ",
"***oOOOOX&XX&oOO@@o@@@.XoX........XXo+          ",
"*$*oOOOOX&XX&oOO@@o@@@.XoX.&&-;;;;$Xo+          ",
"*$*oOOOO@X&&X@%O@@oXXX.XoXo+++++++$Xo+          ",
"*$OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO         ",
"*$O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.         ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.         ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.         ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.         ",
"**O$$$$$$$$$$&&&&&&&&&&&&&&&*$$$$$$$$$.X        ",
"**O$$$$$$$$$$&%=%=%=%=%=%=%&*$$$$$$$$$.XX       ",
"*$O$$$$$$$$$$&=%=%=%=%=%=%=&*$$$$$$$$$.XXX      ",
"*$O$$$$$$$$$$&%=%=%=%=%=%=%&*$$$$$$$$$.*XXX     ",
"*$O$$$$$$$$$$&.............&*$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$&.............&*$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$&.************&*$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$&#############&*$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$&&&&&&&&&&&&&&&*$$$$$$$$$.**XX     ",
"**O$$$$$$$$$$$***************$$$$$$$$$.**XX     ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"**O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"*$O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
" $O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
" $O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"  O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"  O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"  O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.**XX     ",
"  O....................................**XX     ",
"      XXX********************************XX     ",
"       XXX*******************************XX     ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     ",
"         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     "};
