/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * rmdisk_w_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray7	m black	c #424242424242",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray4	m white	c #949494949494",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor7	m white	c cyan",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor2	m white	c white",
"*	s iconColor6	m white	c yellow",
"=	s iconColor4	m white	c green",
"-	s iconColor8	m black	c magenta",
";	s iconColor3	m black	c red",
/* pixels */
" .............................. ",
".XXXXXXXXoooOO+++++OoooXXXXXXXX@",
".XXoXXXooOO++++++++OOOOooXXXoXX@",
".Xo@oXoOO+++++++++OOOO+++oXo@oX@",
".XXoXoOO++#.++++++OOO$%+++oXoXX@",
".XXXoOO+O+.##o++++OO@#+++++oXXX@",
".XXoO++OOO+#&&#++OO@#@++++++oXX@",
".X.oO++++O+o&#+o+O@#@++++++++oX@",
"..oO++++++O+#X**X@#@+++++++++oX@",
".oO=+++++++O+#X*@#@+$+++++++++o@",
".o==%+++++++O+o@#@X$++++++++++o@",
".O+%==++++++.+@#@**o++++++++++X@",
".OO$$$==+++.O@#@oX**o++++++++++@",
".OO++%$$$+++@#@%%#X*.o+++++++++@",
".OOOOO+%$$+@#@OooO#X-;o++++++++@",
".OOOOOOOOO+#@%oXXo%#.-.++++++++@",
".O+++OOOO+o%O%oXXo%%#oO+OOO+++O@",
".++++++++OoO%%OooO%O%.++%+OOOOO@",
".++++++++++.O%%%%%O%o++$$$%++OO@",
".++++++++++oOO%O%O%Oo+++==$$$%O@",
".X++++++++++o.O%O%.o++++++==%$X@",
".o++++++oooooooooooooooo+++%==o@",
".o+++++o++++++++O%O+++++O+++=+o@",
".Xo++++o+++++++++OO+++++O++++oX@",
".Xo++++o++++++++O+O+++++O++++oX@",
".XXo+++o+++++++++O%O++++O+++oXX@",
".XXXo++o+++++++++OO%++++O++oXXX@",
".XXoXo+o+++++++++OO%O+++O+oXoXX@",
".Xo@oXoo++++++++++OOOO++OoXo@oX@",
".XXoXXXoo++++++++OOO%O+oOXXXoXX@",
".XXXXXXoXooo++++++O+oooXOXXXXXX@",
" @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ "};
