/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * slice_editor_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray2	m white	c #bdbdbdbdbdbd",
"$	s iconColor7	m white	c cyan",
"%	s iconColor2	m white	c white",
"&	s iconColor4	m white	c green",
"*	s iconColor6	m white	c yellow",
"=	s iconColor5	m black	c blue",
"-	s iconColor3	m black	c red",
";	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"    ...............             ",
"   .XXoO++++++@+OXX@            ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++++OXXX@           ",
"   .XXoO++++++++OXXX@           ",
"   .XXOOOOOOOOOOXXXX@           ",
"   .XXXXXXXXXXXXXXXX@           ",
"   .XXXXXXXXXXXX..............  ",
"   .XX#########.OXOXXO+++++OoX@ ",
"   .XX#XOOOOOOO.OXOXXO+++++OoXO@",
"   @@XOOo##@++#OOXOXXOOOOOOOoXO@",
"  .o$@#####@++++$OoooooooooooXO@",
" .o$%$@####@+++$%#OXXXXXXXXXXXO@",
" O$+$%$@###@++$%++#XXXXXXXXXXXO@",
".$o$o$+$@##@+$%++&+OOOOOOOOOXXO@",
".O.o$o$+$@XXX%+&&**#O@@@@@@@oXO@",
" OO...o$oX%+%X&**+++O======@oXO@",
"  OOOO..@%+X+%X+++++O====-=@oXO@",
"  .XXOOOO+O+X+X+++++O@@@@@@@oXO@",
"  .XXXXXO%+O+%X+++++O%%%%%%%oXO@",
"  OXXXO@%O%+%X++++++O%%%%%%%oXO@",
"  X.@.%%%@OOO%$$+++#X%%%%%%%oXO@",
"  .@%%%**@X+*%%+$$+O%%%%%%%%oXO@",
" @%%****OXX++*+%++#XooooooooXXO@",
" O%*****@X+++*+###OOOOOOOOOOOOO@",
" ;@%***OXX#######O@@@@@@@@@@@@@ ",
" ;;@***@X######OX               ",
"  ;;@*@XOOOOOOX                 ",
"   ;;@O;                        ",
"    ;;;;                        "};
