/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * zip_w_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconGray7	m black	c #424242424242",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray1	m white	c #dededededede",
"+	s iconColor1	m black	c black",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray8	m black	c #212121212121",
"$	s iconColor2	m white	c white",
"%	s iconColor6	m white	c yellow",
"&	s iconColor5	m black	c blue",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor8	m black	c magenta",
"-	s iconColor3	m black	c red",
/* pixels */
"                                ",
"     ......................     ",
"   ..XoXooXOOOOOOOOOOOOOX.o++   ",
"  .ooXoXooXOOOOOOOOOOOOOX.oXo+  ",
" .oooXoXooXOOOOOOOOOOOOOX.oXoX+ ",
" .oooXoXooXOOOOOOOOOOOOOX.oXoX+ ",
" .oooXoXoooXXXXXXXXXXXXXX.oXoX+ ",
" .oooXoo..................oXoX+ ",
" .oooXoooo@@oooooooooooooooXoX+ ",
" .oooXooo@#X@@oooooo@@oooooXoX+ ",
" .oooXooo@X##+@oooo@+#@ooooXoX+ ",
" .oooXoooo@#$$#@oo@+##@ooooXoX+ ",
" .oooXoooo@X$#@#@@###@oooooXoX+ ",
" .oooXooXXo@+o%%#+#+@oXXXooXoX+ ",
" .oooXoX++++++o%+#+X+++++.oXoX+ ",
" .oooXoX+$$$$+X+#+o&&&&&+.oXoX+ ",
" .oooXoX+$++OO+#+%%o&&&&+.oXoX+ ",
" .oooXoX+$$$$+#+oX%%o&&&+.oXoX+ ",
" .oooXoX+###+#+$$+o%*o+++.oXoX+ ",
" .oooXoX$$$+#+$$$$+o=-X$$.oXoX+ ",
" .oooXoX$$$#+$$$$$$+*=*$$.oXoX+ ",
" .oooXoX$$$$OO....OO+X.O..oXoX+ ",
" .oooXoX$$$$$$$$$$$$$$$$$.oXoX+ ",
" .oooXoX$$$$..............oXoX+ ",
" .oooXoX$$$$$$$$$$$$$$$$$.oXoX+ ",
" .oooXoX$$$$..............oXoX+ ",
" .oooXoX$$$$$$$$$$$$$$$$$.oXoX+ ",
" .oooXoX$$$$$$$$$$$$$---$.oXoX+ ",
" .oooXoX$$$$$$$$$$$$$$$$$.oXoX+ ",
" .oooXoo.................ooXoX+ ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX+ ",
"  ++++++++++++++++++++++++++++  "};
