/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * floppy_w_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor2	m white	c white",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor6	m white	c yellow",
"=	s iconColor8	m black	c magenta",
"-	s iconColor3	m black	c red",
/* pixels */
"                                ",
"                                ",
"                                ",
"  ............................  ",
" .XXXXoOOOOOOOOOOOOOOOOOO+XXXX@ ",
" .XXXXoOOOOOOOOOOOOOOOOOO+XXXX@ ",
" .XXXXoOOO#oOOOOOOOOOOOOO+XXXX@ ",
" .XXXXoOOOo##$OOOOOO@#OOO+XXXX@ ",
" .XXXXoOOOO#%%#OOOO@#@OOO+XXXX@ ",
" .XXXXoOOOO$%#&$OO@#@OOOO+XXXX@ ",
" .XXXXoOOOOO@X**X@#@OOOOO+XXXX@ ",
" .XXXXoOOOOOO@&*@#@OOOOOO+XXXX@ ",
" .XXXXoOOOOOOO$@#@XOOOOOO+XXXX@ ",
" .XXXXoOOOOOOO@#@**$OOOOO+XXXX@ ",
" .XXXXoOOOOOO@#@$&**$OOOO+XXXX@ ",
" .XXXXoOOOOO@#@OO@X*o$OOO+XXXX@ ",
" .XXXXoOOOO@#@OOOO@X=-$OO+XXXX@ ",
" .XXXXoOOOO#@OOOOOO@o=oOO+XXXX@ ",
" .XXXXoOOOOOOOOOOOOO@o&OO+XXXX@ ",
" .XXXXX++++++++++++++++++XXXXX@ ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@ ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@ ",
" .XXXXXXX$$$$$$$$$$$$$$$$$XXXX@ ",
" .XXXXXX$.............$XX+XXXX@ ",
" .XXXXXX$.@@@.........$XX+XXXX@ ",
" .XXXXXX$.@&&.........$XX+XXXX@ ",
" .XXXXXX$.@&&.........$XX+XXXX@ ",
" .XXXXXX$.@&&.........$XX+XXXX@ ",
" .XXXXXX$.@&&.........$XX+XXXX@ ",
"  .XXXXX$.............$XX+XXXX@ ",
"   .XXXX$.............$XX+XXXX@ ",
"    .@@@@@@@@@@@@@@@@@@@@@@@@@  "};
