/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_properties_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray2	m white	c #bdbdbdbdbdbd",
"$	s iconColor2	m white	c white",
"%	s iconColor6	m white	c yellow",
"&	s iconColor4	m white	c green",
"*	s iconColor7	m white	c cyan",
"=	s iconColor3	m black	c red",
"-	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                                ",
"    ...............             ",
"   .XXoO++++++@+OXX@            ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++++OXXX@           ",
"   .XXoO++++++++OXXX@           ",
"   .XXOOOOOOOOOOXXXX@           ",
"   .XXXXXXXXXXXXXXXX@           ",
"   .XXXXXXXXXXXX..............  ",
"   .XXooooooooo.OXOXXO+++++OoX@ ",
"   .XXo#######.XOXOXXO+++++OoXO@",
"   .XXOOOOOOX#.XOXOXXOOOOOOOoXO@",
"   .OO#+$+++#OXXOXoooooooooooXO@",
"   O%++&$++++*#OOXXXXXXXXXXXXXO@",
"  O#$%++&++++*+oOXXXXXXXXXXXXXO@",
" X#++$%+&$++*+$ooOOOOOOOOOOOXXO@",
" O+*++$%%&+**$+ooO@@@@@@@@@@oXO@",
"X#%%**+$XXX*$$++oo==@------@oXO@",
"O+**%%*X$+$X+++oooO=@----=-@oXO@",
"O++$**X$+X+$X+oooO@@@@OO@@@@oXO@",
"O+++++X+X+O+Xooo@------@$$$$oXO@",
"O+++++X$+O+$Xoo@---$$---@$$$oXO@",
"O++++++X$+$XooO----$$----X$$oXO@",
"X#+++**$XXX+oo@----------O$$oXO@",
" O+**+$$%+++oo@---#$#----@ooXXO@",
" X#++$+%++++oo@----$$----@OOOOO@",
"  O###+%++++ooO----$$----@O@@@@ ",
"   O########ooo@---#$$--@       ",
"    XO######oOX @------@        ",
"      XOOOOOX    O@@@@O         "};
