/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_protection_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconColor2	m white	c white",
"&	s iconColor6	m white	c yellow",
"*	s iconColor4	m white	c green",
"=	s iconColor7	m white	c cyan",
"-	s iconColor3	m black	c red",
";	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"     ..........................                 ",
"    .XXXXoXXO+++++++++++++OXXXX@                ",
"    .XXXXoXXO+++++++++++++OXXXXX@               ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++@@@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++++++OXXXXXX@              ",
"    .XXXXOOOOOOOOOOOOOOOOOXXXXXXX@              ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@              ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@              ",
"    .XXXXXoooooooooo$$......................    ",
"    .XXXXo$$$$$$$$$$..OXOXXO+++++++++++++OoX@@  ",
"    .XXXXo$$$$$$$$$.XXOXOXXO+++++++++++++OoXOX@ ",
"    .XXXXo$$XOOOOOOOXXOXOXXO+++++++++++++OoXOXO@",
"    .XXXXOOX$$$$$$$$XOOXOXXO+++++++++++++OoXOXO@",
"    .XXXO+$+++++++++++$OOXXXOOOOOOOOOOOOOOoXOXO@",
"    .XO%%++%++++++++++++$OoooooooooooooooooXOXO@",
"    .O&*%++%++++++++++=++$OXXXXXXXXXXXXXXXXXOXO@",
"    O%+&*%%+%&++++++++=+%+$OXXXXXXXXXXXXXXXXOXO@",
"   #%=%%+**%+%+++++++=+%%+$$OXXXXXXXXXXXXXXXOXO@",
"  #=&%=%&++*%%&++++++=+%+++$$OXXXXXXXXXXXXXXOXO@",
"  #$=&%=%&&+*%%+++++=+%++++$$OXXXXXXXXXXXXXXOXO@",
" #++$=&%=%%&+*%%+++==%++++++$#OOOOOOOOOOOOXXOXO@",
" #&+++=&%==%&$XXXX$=%%++++++$$O@@@@@@@@@@@oXOXO@",
" #+&&++=&%%=XX+%+%XO++++++++$$O-@;;;;;;;;@oXOXO@",
"#+===&&+=&&X%+%+%+%%X+++++++$$X-@;;;;;;;;@oXOXO@",
"#+%%%===&&+X+%+++++%O$+++++++$$&&&&;;;;-;@oXOXO@",
"#++++%%===X+%++XX+++%X+++++++$&OOOO&@@@@@@oXOXO@",
"#+++++++++X%++X%%O+%+O+++++++&O....O&%%%%%oXOXO@",
"#+++++++++X+%+X%%O++%O++++++&..&&&&..&%%%%oXOXO@",
"#+++++++++X%+++OO++%+O+=%%++&..&oo&..&oooooXOXO@",
"#+++++++++$X%+++++%+X$&===%%&..&%%&..&%%%%oXOXO@",
"#+++++==+%+O%%+%+%+%O+=+&&==&..&&&&..&oooooXOXO@",
" #++==&%%%++XO%+%+XO+%&=++&&..........&%%%oXOXO@",
" #+=++%%++&&=$XOOO$+%=%&=$+&..........&ooooXOXO@",
" X++%%+++&&++++++++$&%=%&=+&..........&%%%oXOXO@",
"  O+%+++&&+++++++%%*+&%=%&=&..........&--%oXOXO@",
"  O$+++++++++++++&%%*+&%=%&&..........&%%%oXOXO@",
"   O$++&++++++++++%+%*+$%=$&..........&oooXXOXO@",
"    O$$+=+++++++++&%+%*&+$$&..........&OOOOOOOO@",
"     O$$$+++++++++++%+%*$$O&..........&@@@@@@@@ ",
"      O$$$$$++++++++%$$$#O &..........&         ",
"       OX$$$$$$$$$$$$$XOO  &&&&&&&&&&&&         ",
"         XOX$$$$$$$$XOO                         ",
"            XOOOOOOX                            "};
