/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * dvd_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconColor4	m white	c green",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray8	m black	c #212121212121",
"%	s iconColor1	m black	c black",
/* pixels */
"            ........            ",
"         ...XXXXXXXX...         ",
"       ..oXooooooXXXXXX..       ",
"      .XoooooooooXXXXO++X.      ",
"     .XXXoooooooooXXo++XXX.     ",
"    .XXXXoooooooooXXo+XXXoX.    ",
"   .ooXXXXoooooooXXXO+XXooXX@   ",
"  .ooooXXXooooooooXo+XXooooXX@  ",
"  .XooooXXXooooooXoO+XoooooXX#  ",
" .XXXooooXXoooooooX++oooooooX.@ ",
" .ooXXXoooXXoX@@@@X+OoooooooXX# ",
" .ooooXXXooX@@oOoO@#ooooooooXX# ",
".oooooooXXX@OoOoOoOO@oooooooXX@.",
".oooooooooX@oOoooooO#XoooooooXX@",
".ooooooooo@oOoo@@oooO@oooooooXX#",
".ooooooooo@Ooo@OO#oOo#oooooooXX#",
".ooooooooo@oOo@OO#ooO#oooooooXX#",
".ooooooooo@Oooo##ooOo#oooooooXX#",
".ooooXXXXXX@OoooooOo@XoooooooXX#",
".XXXXXXoO++#@@@@@@@@@@@@@@@@@@@@",
" .XXooO+++Xo@OooOOoOOOOOoOooOOO$",
" .XO+++XXXoo@o%%oo%ooooo%o%%ooo$",
" @X++XXXXooo@o%o%oo%ooo%oo%o%oo$",
"  #+XXXXoooo@o%oo%o%ooo%oo%oo%o$",
"  #XXXXooooo@o%oo%oo%o%ooo%oo%o$",
"   #XXoooooo@o%oo%oo%o%ooo%oo%o$",
"    #XXooooo@o%o%oooo%oooo%o%oo$",
"     #XXXooo@o%%ooooo%oooo%%ooo$",
"      #XXXXX@Oooooooooooooooooo$",
"       #@XXX@$$$$$$$$$$$$$$$$$$$",
"         @#@XXXXXXXX@##         ",
"            @######@            "};
