/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_format_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 17 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor6	m white	c yellow",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray2	m white	c #bdbdbdbdbdbd",
"*	s iconColor2	m white	c white",
"=	s iconColor8	m black	c magenta",
"-	s iconColor7	m white	c cyan",
";	s iconColor3	m black	c red",
":	s iconColor5	m black	c blue",
"?	s iconColor4	m white	c green",
/* pixels */
"                                ",
"                                ",
"    ...............             ",
"   .XXoO++++++@+OXX@            ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++@+OXXX@           ",
"   .XXoO++++++++OXXX@ ####OOO@  ",
"   .XXoO++++++++OXXX@.+$$o$%O   ",
"   .XXOOOOOOOOOOXXXX.+$$o$%O    ",
"   .XXXXXXXXXXXXXXX.+$$o$%O     ",
"   .XXXXXXXXXXXX...+$$o$%O....  ",
"   .XXoooooooooOX.+$$o$%O++OoX@ ",
"   .XXo&&&&&&&OX.+$$o$%O+++OoXO@",
"   .XXOOOOOOO&O.+$$o$%OOOOOOoXO@",
"   .XX*&+++++o.##$o$%OoooooooXO@",
"   O****&++++#+&##$%OXXXXXXXXXO@",
"  O******&++#+&&%#OOXXXXXXXXXXO@",
" X&*******+%=#&%%OOOOOOOOOOOXXO@",
" O+-*****+%=&=O%OO@@@@@@@@@@oXO@",
"X&$$-****+=&=;=OO&;;@::::::@oXO@",
"O+--$$****O=;O;O&&O;@::::;:@oXO@",
"O++*--X****O=;O+&&O@@@@@@@@@oXO@",
"O+++++X+X***OO++&&O*********oXO@",
"O+++++X*+X***+$*&&O*********oXO@",
"O++++++X*+*X*+-$&&O*********oXO@",
"X&+++--*XXX+$*+-&&X*********oXO@",
" O+--+**$+*?+$*&&OooooooooooXXO@",
" X&++*+$+++*?+&&&OOOOOOOOOOOOOO@",
"  O&&&+$+++*?&&&O@@@@@@@@@@@@@@ ",
"   O&&&&&&&&&&&O                ",
"    XO&&&&&&&OX                 ",
"      XOOOOOX                   "};
