/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * slice_editor_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconColor7	m white	c cyan",
"&	s iconColor2	m white	c white",
"*	s iconColor4	m white	c green",
"=	s iconColor6	m white	c yellow",
"-	s iconGray6	m black	c #636363636363",
";	s iconColor5	m black	c blue",
":	s iconColor3	m black	c red",
/* pixels */
"                                                ",
"                                                ",
"   ..........................                   ",
"  .XXXXoXXO+++++++++++++OXXXX@                  ",
"  .XXXXoXXO+++++++++++++OXXXXX@                 ",
"  .XXXXoXXO+++++++++##@+OXXXXXX@                ",
"  .XXXXoXXO+++++++++##@+OXXXXXX@                ",
"  .XXXXoXXO+++++++++##@+OXXXXXX@                ",
"  .XXXXoXXO+++++++++##@+OXXXXXX@                ",
"  .XXXXoXXO+++++++++@@@+OXXXXXX@                ",
"  .XXXXoXXO+++++++++++++OXXXXXX@                ",
"  .XXXXOOOOOOOOOOOOOOOOOXXXXXXX@                ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@                ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXX@                ",
"  .XXXXXoooooooooo$$......................      ",
"  .XXXXo$$$$$OOOOOOOOXOXXO+++++++++++++OoX@@    ",
"  .XXXXo$$OOX$$$@$$$$#OOXO+++++++++++++OoXOX@   ",
"  .XXXXoOO$$$$$$@++++++$OO+++++++++++++OoXOXO@  ",
"  .XXXXO$$$$$$$$@++++++++$O++++++++++++OoXOXO@  ",
"  .X@@O$$$$$$$$$@++++++%++$OOOOOOOOOOOOOoXOXO@  ",
"  .@&%@o$$$$$$$$@++++++%+&+$OooooooooooooXOXO@  ",
"  @&%&%@o$$$$$$$@+++++%+&&+$$OXXXXXXXXXXXXOXO@  ",
" .&%+%&%@o$$$$$$@+++++%+&++&$$OXXXXXXXXXXXOXO@  ",
" O%+%$%&%@o$$$$$@++++%+&++&&$$OXXXXXXXXXXXOXO@  ",
".%+%$%$%+%@o$$$$@+++%%&++&&**$#OXXXXXXXXXXOXO@  ",
"@&%o%$%$%+%@o$$XXXX$%&&++&*==$$OXXXXXXXXXXOXO@  ",
"@@X%o%o%$%+%@OX&++&XO++&&*=++$$OOOOOOOOOXXOXO@  ",
"O..@-o%o%o%+X$&+&&+&&X+**=+++$$XO@@@@@@@oXOXO@  ",
"OOOO..@-o%o%O&++++++&O*=++++++$$O;;;;;;@oXOXO@  ",
" .-OOOO..@--&+++XX+++&X+++++++$$O;;;;;;@oXOXO@  ",
" .XXX-OOOO.@+&+O+&O+&+O+++++++$$O;;;;:;@oXOXO@  ",
" .XXXXXXXOO@&++O++O++&O+++++++$$O@@@@@@@oXOXO@  ",
" OXXXXXX-@.O+&++OO++&+O+%&&+++$$O&&&&&&&oXOXO@  ",
" OXXXX-@O&&&X+&++++&+X$=%%%&&+$$O&&&&&&&oXOXO@  ",
" OXX-@O&&&&&O&+&++&+&O+%+==%%%$$-ooooooooXOXO@  ",
" XO@O&&&&&===OX+&&+XO+&=%++==+$X#&&&&&&&oXOXO@  ",
" @.&&&&&=====$@OOOO$+&%&=%$++=$-oooooooooXOXO@  ",
"@&&&&&=======XO#++++$=&%&=%+$$#O&&&&&&&&oXOXO@  ",
"O+&&========$@##++&&*+=&%&=%$$OooooooooooXOXO@  ",
"#-&=========XO#+++=&&*+=&%&=$#O&&&&&&&&&oXOXO@  ",
"#O+&=======$@##++++&+&*+$&%$$O&&&&&&:::&oXOXO@  ",
" #@&&======XO#+++++=+++*++$$O&&&&&&&&&&&oXOXO@  ",
" ##@&&====$@##++++++++++$$$OooooooooooooXXOXO@  ",
"  ##@&====XO#+++++++++$$$#OOOOOOOOOOOOOOOOOOO@  ",
"   ##@&==$@##$$$$$$$$$$XOO@@@@@@@@@@@@@@@@@@@   ",
"    ##@@=X@OX$$$$$$$$XOO                        ",
"     ###@@## XOOOOOOX                           ",
"       ####                                     "};
