/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * cd_w_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor2	m white	c white",
"+	s iconColor6	m white	c yellow",
"@	s iconColor4	m white	c green",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray6	m black	c #636363636363",
"%	s iconColor7	m white	c cyan",
"&	s iconGray7	m black	c #424242424242",
"*	s iconColor1	m black	c black",
"=	s iconGray5	m black	c #737373737373",
"-	s iconColor8	m black	c magenta",
";	s iconColor3	m black	c red",
/* pixels */
"            ........            ",
"         ...XXXXXXXX...         ",
"       ..oXoooooooooooX..       ",
"      .OOooOooooooooooooX.      ",
"     .+@Oo#$oooooooooo%ooX.     ",
"    .Oo+@O$##&oooooo*#%oOoX.    ",
"   .O%OOo@@#OO#oooo*#*oOOoXX=   ",
"  .%+O%O+oo&O#.&oo*#*%oOoooXX=  ",
"  .X%+O%O++o*=++=*#*%oOooooXX&  ",
" .ooX%+O%OO+o*.+*#*%%OooooooX.= ",
" .+ooo%+O%%O+X&*#*=%OOooooooXX& ",
" .o++oo%+OO%==*#*++&ooooooooXX& ",
".o%%%++o%++=O*#*&.++&oooooooXX=.",
".oOOO%%%++o=*#*oo*=+$&oooooooXX=",
".ooooOO%%%=*#*o==o*=-;&ooooooXX&",
".ooooooooo=#*o=OO&o*$-$ooooooXX&",
".ooooooooo=oOo=OO&oo*$.ooooooXX&",
".ooooooooo=Oooo&&ooOo&o%OOoooXX&",
".oooooooooX=OoooooOo=X+%%%OOoXX&",
".ooooo%%oOo&OOoOoOoO&o%o++%%%XX$",
" .oo%%+OOOoo=&OoOo=&oO+%oo++oX=.",
" .o%ooOOoo++%X=&&&XoO%O+%Xoo+X$ ",
" =ooOOooo++ooooooooX+O%O+%oXX.& ",
"  &oOooo++oooooooOO@o+O%O+%XX&  ",
"  &Xooooooooooooo+OO@o+O%O+X.&  ",
"   &Xoo+ooooooooooOoO@oXO%XX&   ",
"    &XXo%ooooooooo+OoO@+oXX&    ",
"     &XXXoooooooooooOoO@XX&     ",
"      &XXXXXooooooooOXXX.&      ",
"       &=XXXXXXXXXXXXX=&&       ",
"         =&=XXXXXXXX=&&         ",
"            =&&&&&&=            "};
