/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * jaz_w_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor1	m black	c black",
"@	s iconGray8	m black	c #212121212121",
"#	s iconColor2	m white	c white",
"$	s iconColor3	m black	c red",
"%	s iconColor4	m white	c green",
"&	s iconColor6	m white	c yellow",
"*	s iconGray1	m white	c #dededededede",
"=	s iconGray3	m white	c #adadadadadad",
"-	s iconColor8	m black	c magenta",
/* pixels */
"        .XooooooooooooX.        ",
"     OOOOOOOOOOOOOOOOOOOO++     ",
"   OoOOOOOooooooooooooOOOOO++   ",
"  OOOOOooo@@@@@@@@@@@@oooOOOO+  ",
" oOOOoo+@@OOOOOOOOOOOOOOOooOOO+ ",
" oOOo+@OOOOOOOOOOOOOOOOOOOOoO@+ ",
" oOo@OOOOXXXXXXXXXXXXXXOOOOOo@+ ",
" oOo@OOXX++++++++++++++XXOOOo@+ ",
" oOo@OX++###O$$+%O%O%O%++XOOo@+ ",
" oOo@OX+##@oO$$+o%O%%%O%+XOOo@+ ",
" oOo@OX+##o@@+$+%O%%+@%O+XOOo@+ ",
" oOo@OX+###@##@@%%%+@+%%+XOOo@+ ",
" oOo@OX+++@O#@.@OO@@+O@++XOOo@+ ",
" oOo@OX#####+X&&@+@+#####XOOo@+ ",
" oOo@OX######+X&+@+######XOOo@+ ",
" oOo@OX#######O+@+X######XOOo@+ ",
" oOo@OX#####**+@+&&O**===XOOo@+ ",
" oOo@OX######+@+XO&&O####XOOo@+ ",
" oOo@OX#####+@+##+X&oO**=XOOo@+ ",
" oOo@OX####+@+####+X-$O##XOOo@+ ",
" oOo@OX####@+**==**+o-O*=XOOo@+ ",
" oOo@OX#############+O=##XOOo@+ ",
" oOo@OX#####=======****==XOOo@+ ",
" oOo@OX##################XOOo@+ ",
" oOo@OX*################*XOOo@+ ",
" oOo@OOX=*####$$$$$###*=XOOOo@+ ",
" oOo@OOOXX=*########*=XXOOOOo@+ ",
" oOo@OOOOOXXXXXXXXXXXXOOOOOOo@+ ",
" oOo@OOOOOOOOOOOOOOOOOOOOOOOo@+ ",
" oOo@OOOOOOOOOOOOOOOOOOOOOOOo@+ ",
" o@o@@@@@@@@@@@@@@@@@@@@@@@+o@+ ",
"  ++++++++++++++++++++++++++++  "};
