/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * jaz_rw_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor1	m black	c black",
"@	s iconGray8	m black	c #212121212121",
"#	s iconColor2	m white	c white",
"$	s iconColor3	m black	c red",
"%	s iconColor4	m white	c green",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconColor6	m white	c yellow",
"=	s iconGray1	m white	c #dededededede",
/* pixels */
"        .XooooooooooooX.        ",
"     oooOOOOOOOOOOOOOOOOO++     ",
"   ooOOOOOooooooooooooOOOOO++   ",
"  oOOOOooo@@@@@@@@@@@@oooOOOO+  ",
" oOOOoo+@@OOOOOOOOOOOOOOOooOOO+ ",
" oOOo+@@OOOOOOOOOOOOOOOOOOOoO@+ ",
" oOo@@OOOXXXXXXXXXXXXXXOOOOOo@+ ",
" oOo@OOXX++++++++++++++XXOOOo@+ ",
" oOo@OX++###+$$+%@%@%@%++XOOo@+ ",
" oOo@OX+####+$$+@%@%@%@%+XOOo@+ ",
" oOo@OX+#++#+$$+%@%@%@%@+XOOo@+ ",
" oOo@OX+####+$$+@%@%@$$%+XOOo@+ ",
" oOo@OX++++++++++++++++++XOOo@+ ",
" oOo@OX##################XOOo@+ ",
" oOo@OX##################XOOo@+ ",
" oOo@OX##################XOOo@+ ",
" oOo@OX#####&&&&&&&&&&&&&XOOo@+ ",
" oOo@OX##############****XOOo@+ ",
" oOo@OX#####&&&&&&&&*O@@O*OOo@+ ",
" oOo@OX############*@@**@@*Oo@+ ",
" oOo@OX#####&&&&&&&*@@**@@*Oo@+ ",
" oOo@OX############*@@**@@*Oo@+ ",
" oOo@OX#####&&&&&&*@@@@@@@@*o@+ ",
" oOo@OX###########*@@@@@@@@*o@+ ",
" oOo@OX=##########*@@@@@@@@*o@+ ",
" oOo@OOX&=####$$$$*@@@@@@@@*o@+ ",
" oOo@OOOXX&=######*@@@@@@@@*o@+ ",
" oOo@OOOOOXXXXXXXX*@@@@@@@@*o@+ ",
" oOo@OOOOOOOOOOOOO*@@@@@@@@*o@+ ",
" oOo@OOOOOOOOOOOOO**********o@+ ",
" o@o@@@@@@@@@@@@@@@@@@@@@@@Oo@+ ",
"  +o++++++++++++++++++++++++o+  "};
