/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_format_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 17 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray8	m black	c #212121212121",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray1	m white	c #dededededede",
"@	s iconColor1	m black	c black",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray6	m black	c #636363636363",
"%	s iconColor2	m white	c white",
"&	s iconColor6	m white	c yellow",
"*	s iconGray2	m white	c #bdbdbdbdbdbd",
"=	s iconColor7	m white	c cyan",
"-	s iconColor8	m black	c magenta",
";	s iconColor3	m black	c red",
":	s iconColor5	m black	c blue",
"?	s iconColor4	m white	c green",
/* pixels */
"                                                ",
"     ..........................                 ",
"    .XXXXoXXO+++++++++++++OXXXX@                ",
"    .XXXXoXXO+++++++++++++OXXXXX@               ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++##@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++@@@+OXXXXXX@              ",
"    .XXXXoXXO+++++++++++++OXXXXXX@#########$$$$@",
"    .XXXXOOOOOOOOOOOOOOOOOXXXXXXX#%%+&&&&&$&$&@ ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXX#%%+&&&&&$&$&@  ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXX#%%+&&&&&$&$&@   ",
"    .XXXXXoooooooooo**........#%%+&&&&&$&$&@    ",
"    .XXXXo**********..OXOXXOo#%%+&&&&&$&$&@X@@  ",
"    .XXXXo*********.XXOXOXXO#+%+&&&&&$&$&@oXOX@ ",
"    .XXXXo**XOOOOOOOXXOXOXX#*#+&&&&&$&$&.OoXOXO@",
"    .XXXXOOX********XOOXOX%%#*$*&&&$&$&.+OoXOXO@",
"    .XXXO%++++++++++++*OO%%+*$*$*&$&$&.OOOoXOXO@",
"    .XXX%%%+++++++++++++%%+**#$*$#&$&.oooooXOXO@",
"    .X%%%%%%++++++++++=%%+**###$*$#&.XXXXXXXOXO@",
"    O%%%%%%%%+++++++++%%+**#####$*$OXXXXXXXXOXO@",
"   #%%%%%%%%%%+++++++#%+**######$$OXXXXXXXXXOXO@",
"  #=&%%%%%%%%%%+++++#*#**######$$OXXXXXXXXXXOXO@",
"  #*=&%%%%%%%%%%+++%-#*$######$$OXXXXXXXXXXXOXO@",
" #++*=&%%%%%%%%%%+%-+-$*$####$$OOOOOOOOOOOXXOXO@",
" #&+++=&%%%%%%%%+%-+-;-$*$##$$O@@@@@@@@@@@oXOXO@",
" #+&&++=&%%%%%%%+-+-;-;-$*$$$OO;@::::::::@oXOXO@",
"#+===&&+=&&%%%%%+;-;-;-O;$o$O*X;@::::::::@oXOXO@",
"#+%%%===&&+X%%%%%#;-;-O;O;$O+**O@::::::;:@oXOXO@",
"#++++%%===X++%%%%%#;-O;O;OO++**O@@@@@@@@@@oXOXO@",
"#+++++++++X%++%%%%%#;;O;OO+++**O%%%%%%%%%%oXOXO@",
"#+++++++++X+%+X%%%%%#;;OO++++**O%%%%%%%%%%oXOXO@",
"#+++++++++X%+++O%%%%%OOO%%+++**OoooooooooooXOXO@",
"#+++++++++*X%++++%%%%%&===%%+**O%%%%%%%%%%oXOXO@",
"#+++++==+%+O%%+%++%%%+=+&&===**$oooooooooooXOXO@",
" #++==&%%%++XO%+%+XO+%&=++&&+*X#%%%%%%%%%%oXOXO@",
" #+=++%%++&&=*XOOO*+%=%&=*++&*$ooooooooooooXOXO@",
" X++%%+++&&++++++++*&%=%&=+**#O%%%%%%%%%%%oXOXO@",
"  O+%+++&&+++++++%%?+&%=%&=**O%%%%%%%%;;;%oXOXO@",
"  O*+++++++++++++&%%?+&%=%&*#O%%%%%%%%%%%%oXOXO@",
"   O*++&++++++++++%+%?+*%=**OoooooooooooooXXOXO@",
"    O**+=+++++++++&%+%?&+**OOOOOOOOOOOOOOOOOOOO@",
"     O***+++++++++++%+%?**O@@@@@@@@@@@@@@@@@@@@ ",
"      O*****++++++++%***#O                      ",
"       OX*************XOO                       ",
"         XOX********XOO                         ",
"            XOOOOOOX                            "};
