/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * jaz_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor1	m black	c black",
"@	s iconGray8	m black	c #212121212121",
"#	s iconColor2	m white	c white",
"$	s iconColor3	m black	c red",
"%	s iconColor4	m white	c green",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray1	m white	c #dededededede",
/* pixels */
"        .XooooooooooooX.        ",
"     oooOOOOOOOOOOOOOOOOO++     ",
"   ooOOOOOoooooooooooOOOOOO++   ",
"  oOOOOooo@@@@@@@@@@@oooOOOOO+  ",
" oOOOoo@@@OOOOOOOOOOOOOOooOOOO+ ",
" oOOo@@@OOOOOOOOOOOOOOOOOOoOO@+ ",
" oOo@@OOOXXXXXXXXXXXXXXOOOOoO@+ ",
" oOo@OOXX++++++++++++++XXOOoO@+ ",
" oOo@OX++###+$$+%@%@%@%++XOoO@+ ",
" oOo@OX+####+$$+@%@%@%@%+XOoO@+ ",
" oOo@OX+#++#+$$+%@%@%@%@+XOoO@+ ",
" oOo@OX+####+$$+@%@%@$$%+XOoO@+ ",
" oOo@OX++++++++++++++++++XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX#####&&&&&&&&&&&&&XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX#####&&&&&&&&&&&&&XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX#####&&&&&&&&&&&&&XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX#####&&&&&&&&&&&&&XOoO@+ ",
" oOo@OX##################XOoO@+ ",
" oOo@OX*################*XOoO@+ ",
" oOo@OOX&*####$$$$$###*&XOOoO@+ ",
" oOo@OOOXX&*########*&XXOOOoO@+ ",
" oOo@OOOOOXXXXXXXXXXXXOOOOOoO@+ ",
" oOo@OOOOOOOOOOOOOOOOOOOOOOoO@+ ",
" oOo@OOOOOOOOOOOOOOOOOOOOOOoO@+ ",
" o@o@@@@@@@@@@@@@@@@@@@@@@@o@@+ ",
"  +o+++++++++++++++++++++++o++  "};
