/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * zip_rw_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray3	m white	c #adadadadadad",
"X	s iconGray7	m black	c #424242424242",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray1	m white	c #dededededede",
"+	s iconColor1	m black	c black",
"@	s iconColor2	m white	c white",
"#	s iconColor3	m black	c red",
"$	s iconColor5	m black	c blue",
"%	s iconColor6	m white	c yellow",
"&	s iconGray8	m black	c #212121212121",
/* pixels */
"                                ",
"     ......................     ",
"   ..XoXooXOOOOOOOOOOOOOX.o++   ",
"  .ooXoXooXOOOOOOOOOOOOOX.oXo+  ",
" .oooXoXooXOOOOOOOOOOOOOX.oXoX+ ",
" .oooXoXooXOOOOOOOOOOOOOX.oXoX+ ",
" .oooXoXoooXXXXXXXXXXXXXX.oXoX+ ",
" .oooXoo..................oXoX+ ",
" .oooXoooooooooooooooooooooXoX+ ",
" .oooXoooooooooooooooooooooXoX+ ",
" .oooXoooooooooooooooooooooXoX+ ",
" .oooXoooooooooooooooooooooXoX+ ",
" .oooXoooooooooooooooooooooXoX+ ",
" .oooXooXXXXXXXXXXXXXXXXXooXoX+ ",
" .oooXoX+++++++++++++++++.oXoX+ ",
" .oooXoX+@@@@+#+$$$$$$$$+.oXoX+ ",
" .oooXoX+@++@+#+$$$$$$$$+.oXoX+ ",
" .oooXoX+@@@@+#+$$$$$%%%%.oXoX+ ",
" .oooXoX++++++++++++%X&&X%oXoX+ ",
" .oooXoX@@@@@@@@@@@%&&%%&&%XoX+ ",
" .oooXoX@@@@@@@@@@@%&&%%&&%XoX+ ",
" .oooXoX@@@@.......%&&%%&&%XoX+ ",
" .oooXoX@@@@@@@@@@%&&&&&&&&%oX+ ",
" .oooXoX@@@@......%&&&&&&&&%oX+ ",
" .oooXoX@@@@@@@@@@%&&&&&&&&%oX+ ",
" .oooXoX@@@@......%&&&&&&&&%oX+ ",
" .oooXoX@@@@@@@@@@%&&&&&&&&%oX+ ",
" .oooXoX@@@@@@@@@@%&&&&&&&&%oX+ ",
" .oooXoX@@@@@@@@@@%&&&&&&&&%oX+ ",
" .oooXoo..........%%%%%%%%%%oX+ ",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX+ ",
"  ++++++++++++++++++++++++++++  "};
