/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char * media_mgr_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray7	m black	c #424242424242",
"X	s iconGray8	m black	c #212121212121",
"o	s iconColor1	m black	c black",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray6	m black	c #636363636363",
"#	s iconColor4	m white	c green",
"$	s iconColor2	m white	c white",
"%	s iconColor6	m white	c yellow",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconColor7	m white	c cyan",
"=	s iconGray2	m white	c #bdbdbdbdbdbd",
"-	s iconColor3	m black	c red",
";	s iconColor5	m black	c blue",
":	s iconGray4	m white	c #949494949494",
/* pixels */
"         .XooooX.               ",
"         XO.++.+.o              ",
"         oO.++.+.Oo             ",
"     OO.XoO.....Ooooooo         ",
"    @#$++XOOOOOOo.OO++@o        ",
"   @%+#++&X++++oO.OO++@Oo       ",
"@@.+$%#$+*&O+++oO......Oo       ",
"@@.*+$O.*=&.+++oO&&&&&&Oo       ",
"@@.+**..++&.+++oOOo-o;;Oo       ",
"@:.&++%#%&&.+++oOOo-o;;Oo       ",
"@:++++++++++++++++++++++++      ",
"@:+&&&&&&&&&&&&&&&&&&&&&&X      ",
"@@+&&&&&&&&&&&&&&&&&&&&&&X      ",
"@@+&&&&&&$$$$$$$$$$&&&&&&X      ",
"@@+&&&&&&$*%*%*%*%$@&&&&&XOO    ",
"@:+&&&&&&$%*%*%*%*$@&&&&&XOO    ",
"@:+&&&&&&$XXXXXXXX$@&&&&&X@OO   ",
"@:+&&&&&&$OOOOOOOO$@&&&&&X@@O   ",
"@:+&&&&&&$$$$$$$$$$@&&&&&X@@O   ",
"@:+&&&&&&&@@@@@@@@@@&&&&&X@@O   ",
"@@+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"@@+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"@@+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"@:+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"@:+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"O:+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
" :+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
" :+&&&&&&&&&&&&&&&&&&&&&&X@@O   ",
"  +XXXXXXXXXXXXXXXXXXXXXXX@@O   ",
"    OO@@@@@@@@@@@@@@@@@@@@@@O   ",
"      O@@@@@@@@@@@@@@@@@@@@@O   ",
"      OOOOOOOOOOOOOOOOOOOOOOO   "};
