/* XPM */
/****************************************************************
*  Copyright (c) 1996 Sun Microsystems, Inc.
*  All Rights Reserved
*****************************************************************/
static char * SDtnetsc_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 11 1 0 0",
/* colors */
" 	s iconGray8	m black	c #212121212121",
".	s iconGray7	m black	c #424242424242",
"X	s iconGray6	m black	c #636363636363",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconColor2	m white	c white",
"#	s iconColor7	m white	c cyan",
"$	s iconColor1	m black	c black",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconColor5	m black	c blue",
/* pixels */
"                                                ",
"                       .   .  .                 ",
"            .  . . . .  ..  .  .. .             ",
"        . .  ..   .   . . .....  . . .          ",
"       . . ... ...  . .. ... . ...... ... .     ",
"    . . . .. .. . .. . ... ..... . . .. .. . .  ",
".  .. .. . ...... .. ..... .......... ... ..... ",
" .. ... ... . .........X..X..X ... .... .... ...",
".. . . ... ..XX X. X.XXX X.X.X.X.XX.X... . .. . ",
" ...........X.XX.XXX.X.XXX.XXX..XX.XX.XX........",
". ......X.XX.X.XXX XXXXXXXXXXXXXXX XXX.X.X.X.. .",
".....X.X.X.XX.XXXXoXoXXooooXoXoXXXXXXXXXX.X.X...",
"..X.X.XXXXXXXXXoXoXoXOO++oOoXoXoXoXXXXXXXXXX.X.X",
".X.X.XXXXXXXoXoXoXoXO++@#@oOXXoXoXoXoXoXXXXXXX..",
"X.XXXXXoXXXoXoXoXoXXO+#Oo#@oXoXoXoXoXoXoXoXXXXXX",
"XXXXXXoXXooooXoooooo+@+Ooo@o$ ooooXoooXooXoXXXXX",
"XXXXooXoXXoXoooooooXO@+O o#%$$&ooXoXoXooXooXoXXo",
"XXXXXoXoooooooooOooX+@+O o+o&  oooooooXoooXoXooo",
"XooXooooXoooooOooOooO@OO o@o$$$ooOoooooOoooooXoX",
"oXXXooOooooOoooOoooOO@+O #+o$  OoooOoooooooooooO",
"oXoooooooOoooO#o#OooO+@o ++X$  oo#oooOoooOoooooo",
"oooooooOooo#oooOoOo#o+@O @+&$ &#OoOO#ooOoooOoooO",
"XOoooOoooOOoO#OoO#OOoO@O @O$$ ooO#oOOOoooOoooOoo",
"OoOOoooO#Oo#oOO#OOo#o+@+ @%$$ o#OoO#OoO#OooOooOO",
"@+oo#OooO#OOO#O#O#OOo+@O @+X& OoO#oOo#oOoOoooOo+",
"@+OXOo#O#O#O#O#O#o#OO@@O #+X X#O#O#o#o#o#oOoOo@@",
"#@+ XOOOO#O#O#o#o#o#++@O +@oooo#o#O#O#O#O#o#o+@#",
"O@@o&X#O#O#O#o#o++@@@@@OO+@@@++o#o#o#O#O#OooO@@+",
" #@+$ X#O#o#o+@@@@+X X   XXXXO@@@+o#o#o#OoO#+@#X",
"X +@%$ O#o+o@@+OX X X X X XXXXXoO+@+oo#o#Oo+@@X ",
"OX @@%oXo++@+OX  X X X X XXXoXoXXXO+@+o#oo+@@X o",
"@+X @@+oo+@O    X X X X X XoOoXoXXOoO@+oo+@@X O+",
"o++X #@@@+oX X X X X X XXXXOXOooooXOXo+@+@#X O+%",
" o@OXo+@OX  X X X X XXXooOXoXXXOXoOooooO@#X O@%X",
"$&o@OoOOX  X X X X XXXXOXXXXOXooOOoXooooOXoO++&$",
"$$ +@+O   X X X XXXXoO%OoO+OOXooOOXoXOooooO@+X$$",
"$$ +@+   X X X XXO++++++o@@+++OOoOOOOOoooooO+ $$",
"$ o++o  X X X OO++oXo+@Oo++oXo%++OoOOXOooXoO@o $",
"$$++O  X X XXO++o&$&X++Oo++o$$ o++OOXOoXoooo++o$",
" o@O  X X oXo@@%X$$$o++OX++o $$&o@@OoXOoOoXoo@% ",
"X++X X XOXOXO+@+%$$ o++OXO+o$$XX+@++oOOOOXoooO+o",
"o@O X XXXoO+OO+@++$ o++OXO@o X%@@+OoOOOoXOoooo@%",
"++ X XXXOO+@+X O#@% X++OXO@X&+@@+OOO+@OOOXOoooO+",
"@OX X ooX+++@OXOO#@o %@Oo++oo+@+OOO#+++oOOoOoo#+",
"+X X oXoO+XX++OXO+@%oo@Oo@%X%@@XOXO@%X++O#OoOoo#",
"O X XXXo+% &o@+ Xo#@%o@Oo@%o@@OXoO@+$$o@OoOOooO#",
" X XoXoO+X$$ %@# XO@@+++o@@+@OOoO@XX$$X+OO#oOoo#",
"X XXooOO+ $ & o++ XX@@@#O#@@OOO++oX$$& o@ooO#OOO"};
