/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * SDtPerf_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #636363636363",
"X	s topShadowColor	m white	c #bdbdbdbdbdbd",
"o	s iconColor3	m black	c red",
"O	s iconColor5	m black	c blue",
"+	s iconColor4	m white	c green",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"   ..................      ..................   ",
"   .                X      .                X   ",
"   .                X      .                X   ",
"   .                X      .                X   ",
"   .                X      .                X   ",
"   .                X      .ooooooooooooooooX   ",
"   .                X      .ooooooooooooooooX   ",
"   .                X      .ooooooooooooooooX   ",
"   .                X      .ooooooooooooooooX   ",
"   .                X      .ooooooooooooooooX   ",
"   .ooooooooooooooooX      .ooooooooooooooooX   ",
"   .ooooooooooooooooX      .ooooooooooooooooX   ",
"   .ooooooooooooooooX      .ooooooooooooooooX   ",
"   .ooooooooooooooooX      .O+O+O+O+O+O+O+O+X   ",
"   .ooooooooooooooooX      .+O+O+O+O+O+O+O+OX   ",
"   .ooooooooooooooooX      .O+O+O+O+O+O+O+O+X   ",
"   .ooooooooooooooooX      .+O+O+O+O+O+O+O+OX   ",
"   .ooooooooooooooooX      .O+O+O+O+O+O+O+O+X   ",
"   .ooooooooooooooooX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .OOOOOOOOOOOOOOOOX      .+O+O+O+O+O+O+O+OX   ",
"   .OOOOOOOOOOOOOOOOX      .O+O+O+O+O+O+O+O+X   ",
"   .XXXXXXXXXXXXXXXXX      .XXXXXXXXXXXXXXXXX   ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
