/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * dial_phone_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray7	m black	c #424242424242",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor1	m black	c black",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"    ...X.X.X.X.X.X.X.X.X..oO+   ",
"   ..X.....................O@#  ",
"  X.X..ooooX.$oooooX.$OOo..o%$# ",
"  .X..oOO%@X.$@@@@@X.$@OOo..O$# ",
"  .X.oO%###X.######X.##@OOo.O$# ",
"  ...oO%##............#@OOo.O$# ",
"   ##### .%ooooooooooX.#######  ",
"        .%.X%..X%..X%.X.@       ",
"       .%..%&..%&..%&..X.@      ",
"      ..%..............X..+     ",
"      ..%..X%..X%..X%..X..&     ",
"      ..%..%&..%&..%&..X..&     ",
"      ..%..............X..&     ",
"      ..%..X%..X%..X%..X..&     ",
"      ..%..%&..%&..%&..X..&     ",
"      ...XXXXXXXXXXXXXX...&     ",
"      ....................&     ",
"      .o%%%%%%%%%%%%%%%%%@&     ",
"      .oO%%%%%%%%%%%%%%%@@&     ",
"      .o%%%%%%%%%%%%%%%%%@&     ",
"      .oO%%%%%%%%%%%%%%%@@&     ",
"       ##################&      ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "};
