/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * sdtpcmemvol_48_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconColor5	m black	c blue",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray7	m black	c #424242424242",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"  .............................................X",
" ..ooooooooooooooooooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.oooo....................................ooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@.........@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@.########O@@@@@XooooO",
".o.oooo.@@@@@@@@@@.........##########O@@@@XooooO",
".o.oooo.@@@@@@@@..ooooooooo##########OO@@@XooooO",
".o.oooo.@@@@@@@......................$$+@@XooooO",
".+.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".+.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".+.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".o.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".o.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".o.oooo.@@@@@@@.ooooooooooooooooooooo$$+@@XooooO",
".+.oooo.XXXXXXX.ooooooooooooooooooooo$$+XXXooooO",
".+.oooooooooooo.ooooooooooooooooooooo$$+oooooooO",
".+.oooooooooooo.ooooooooooooooooooooo$$+oooooooO",
".o.oooooooooooo.ooooooooooooooooooooo$$+oooooooO",
".o%OOOOOOOOOOOO.ooooooooooooooooooooo$$+OOOOOOO%",
".$OOOOOOOOOOOOO.ooooooooooooooooooooo$$+OOOOOO% ",
"               .ooooooooooooooooooooo$$+        ",
"               .$$$$$$$$$$$$$$$$$$$$$OO+        ",
"                +++++++++++++++++++++++         ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
