/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtcdromvol_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconColor6	m white	c yellow",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray8	m black	c #212121212121",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor4	m white	c green",
"%	s iconGray7	m black	c #424242424242",
"&	s iconColor7	m white	c cyan",
"*	s iconGray5	m black	c #737373737373",
"=	s iconColor8	m black	c magenta",
/* pixels */
"           .........X           ",
"        ....oooooooX...X        ",
"      ..oooO+++++++++oX..       ",
"     ..o..@#+++.+++.++++X.      ",
"    ..oO$.#@@%++++++%%&++o+     ",
"   ..o.+O$.@..@+++.%%%&+.+o#    ",
"  ..o.&..+$%.@X%.+%%%&+..++o#   ",
"  .&&O.&.O+$@*OO%%%%+&+.++++X*  ",
" ..o+&O.&.O+$@*O%%%+&+.++++++*  ",
" .Oo+o&O.&.O+$#%%%%&&.+++++++X* ",
"..oO+++&O.&.Oo%%%OO%..+.++.++o# ",
"..o+OO++&O.&*%%%**OO%+++++++++* ",
".o+&&&OO+&O*%%%.+@*O#%++++++++X*",
".o+...&&&Oo%%%....@*==%+.+++++o*",
".o++++..&&*%%.+**+.@#=#+++.+++o*",
".o++++++++*+..*oo*.+@#++++++++o*",
".o++.+++++*.+.*oo*..+*++++++++o*",
".o+++++.++*+..+**+.+.*+&..++++o*",
".o++.+++++o*+.....+.*oO&&&..++o*",
".X+++++&&++*o+.+.+.+*+&+OO&&&+X*",
"X.+++&&O..++**+.+.**+.O&++OO++* ",
" .o+&++..+OO&o****o+.&.O&o++Oo* ",
" .X++..+++O++++++++oO.&.O&+o+X* ",
" X.++.+++O+++++++..$+O.&.O&++*  ",
"  .X+++++++++.+++O..$+O.&.O+X*  ",
"   .o+++O+++++++++.+.$+o.&.o*   ",
"    +o+O+&++++++++O.+.$O+.o*    ",
"     *o+&+++.++.++++.+.$Oo*     ",
"      *X++++++++++++.+.+X*      ",
"       **X+++++++++++oX**       ",
"         ***XooooooX***         ",
"            ********            "};
