/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtejctfloppy_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray3	m white	c #adadadadadad",
"o	s iconGray7	m black	c #424242424242",
"O	s iconColor1	m black	c black",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor7	m white	c cyan",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
"&	s iconColor8	m black	c magenta",
"*	s iconGray4	m white	c #949494949494",
"=	s iconGray8	m black	c #212121212121",
/* pixels */
"      ..........................",
" XXXXo..........................",
" XXXO+@@@@@@@@@@@@@@@@@@@@@.....",
" XXXO++++++++++++++++++++++O....",
" XXXO++++++++++++++++++++++O....",
" XXXO+++++++++++++++  +++++O....",
" XXXO+++++++######## $ ####O....",
" XXXO++++++X%%%%%%%% &$ %%%O....",
" XXXO+oo+++X%%%%%%%% $&$ %%O....",
" XXXO+@@o++X%%%%%%%% &$&$ %O....",
" XXXO+O@o++X%%%%%%%% $&$&$ O....",
" XXXO+*@o++X%%%%     &$&$&$ ....",
" XXXO+*@o++X%%%% $&$&$&$&$&$ ...",
" XXXO+@@o++X%%%% &$&$&$&$&$&$ ..",
" XXXO+@@o++X%%%% $&$&$&$&$&$&$ .",
" XXXO+@@o++X%%%% &$&$&$&$&$&$&$ ",
" XXXO+@@o++X%%%% $&$&$&$&$&$&$&O",
" XXXO+@@o++X%%%% &$&$&$&$&$&$&O.",
" XXXO+@@o++X%%%% $&$&$&$&$&$&O..",
" XXXO+@@o++X%%%% &$&$&$&$&$&O...",
" XXXO+@@o++X%%%% === $&$&$&O....",
" XXXO+@@o++X%%%%%%%% &$&$&O+....",
" XXXO+ooo++X%%%%%%%% $&$&O%O....",
" XXXO+++o++X%%%%%%%% &$&O%%O....",
" XXXO+++o++X%%%%%%%% $&O%%%O....",
" XXXO+XXo+++XXXXXXXX &OXXXXO....",
" XXXO+++++++++++++++ O+++++O....",
" XXXO++++++++++++++++++++++O....",
" XXXO++++++++++++++++++++++O....",
" XXXO+OOOOOOOOOOOOOOOOOOOOO.....",
" XXXXO..........................",
"XOOOOO.........................."};
