/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwpdosfloppy_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray8	m black	c #212121212121",
"%	s iconColor2	m white	c white",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor6	m white	c yellow",
"=	s iconColor8	m black	c magenta",
/* pixels */
"                                ",
"                                ",
"                                ",
" ..........................     ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoO###OOOO###OOO###O+XXX@    ",
".XXXoO#OO#OO#OOO#O#OOO#+XXX@    ",
".XXXoO#OOO#O#OOO#O#OOOO+XXX@    ",
".XXXoO#OOO#O#OOO#OO###O+XXX@    ",
".XXXoO#OOO#O#OOO#OOOOO#+XXX@    ",
".XXXoO#OO#OO#OOO#O#OOO#+XXX@    ",
".XXXoO###OOOO###OOO###O+XXX@    ",
".XXXoOOO$oOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOo$$#OOOOOO##OOO+XXX@    ",
".XXXoOOOO$%%$OOOO###OOO+XXX@    ",
".XXXoOOOO#%$&#OO###OOOO+XXX@    ",
".XXXoOOOOO$X**####OOOOO+XXX@    ",
".XXXoOOOOOO$X*###OOOOOO+XXX@    ",
".XXXoOOOOOOOo####OOOOOO+XXX@    ",
".XXXX+++++++###**#+++++XXXX@    ",
".XXXXXXXXXX###XX**#XXXXXXXX@    ",
".XXXXXXXXX###XX$X*o#XXXXXXX@    ",
".XXXXXX#########$X==####XXX@    ",
".XXXXX#..##......$o=oXX+XXX@    ",
".XXXXX#.@&&.......$o#XX+XXX@    ",
".XXXXX#.@&&.........#XX+XXX@    ",
".XXXXX#.@&&.........#XX+XXX@    ",
".XXXXX#.@&&.........#XX+XXX@    ",
".XXXXX#.@&&.........#XX+XXX@    ",
" .XXXX#.............#XX+XXX@    ",
"  .XXX#.............#XX+XXX@    ",
"   .@@@@@@@@@@@@@@@@@@@@@@@     "};
