/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwppcmemvol_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconColor5	m black	c blue",
"$	s iconGray6	m black	c #636363636363",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray5	m black	c #737373737373",
"*	s iconColor6	m white	c yellow",
"=	s iconGray2	m white	c #bdbdbdbdbdbd",
"-	s iconColor3	m black	c red",
";	s iconColor8	m black	c magenta",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"  .............................................X",
" ..ooooooooooooooooooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.oooo....................................ooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@.........@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@.########O@@@@@XooooO",
".o.oooo.@@@@@@@@@@.........##########O@@@@XooooO",
".o.oooo.@@@@@@@@..oO$oooooo##########OO@@@XooooO",
".o.oooo.@@@@@@@....$Oo%@..........%%.&&+@@XooooO",
".+.oooo.@@@@@@@.ooo&Oo.&&oooooooo%%%%&&+@@XooooO",
".+.oooo.@@@@@@@.ooooOX...%oooooo%%%%%&&+@@XooooO",
".+.oooo.@@@@@@@.oooo%%@.**%oooo%%%%%o&&+@@XooooO",
".o.oooo.@@@@@@@.ooooo%&=***%oo%%%%%oo&&+@@XooooO",
".o.oooo.@@@@@@@.ooooooO&=***$%%%%%ooo&&+@@XooooO",
".o.oooo.@@@@@@@.oooooooO&=**%%%%%oooo&&+@@XooooO",
".+.oooo.XXXXXXX.ooooooooO&=%%%%%ooooo&&+XXXooooO",
".+.oooooooooooo.ooooooooo$%%%%%$ooooo&&+oooooooO",
".+.oooooooooooo.ooooooooo%%%%%**%oooo&&+oooooooO",
".o.oooooooooooo.oooooooo%%%%%=***%ooo&&+oooooooO",
".o%OOOOOOOOOOOO.ooooooo%%%%%$&=***%oo&&+OOOOOOO%",
".&OOOOOOOOOOOOO.oooooo%%%%%ooO&=**&%&&&+OOOOOO% ",
"               .ooooo%%%%%ooooO&=&..%&&+        ",
"               .&&&&%%%%%&&&&&&O&=.-;%O+        ",
"                +++%%%%%$++++++$O&-;-%+         ",
"                                 O$-;%          ",
"                                  OOO           ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
