/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwpdosfloppy_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray4	m white	c #949494949494",
"%	s iconGray8	m black	c #212121212121",
"&	s iconColor2	m white	c white",
"*	s iconColor6	m white	c yellow",
"=	s iconColor3	m black	c red",
"-	s iconColor8	m black	c magenta",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"    ........................................    ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOO#####$OOOOo###oOOOO#####O++XXXXX@   ",
"   .XXXXXoOO#$OOO#$OOo$OOO$oOO#$OOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#OO#OOOOO#OO#$OOOO#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$O#$$OOOO++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OO####$O++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OOOOO$#$++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OOOOOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#OO#OOOOO#OO#OOOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO#$OOo$OOO$oOO#$OO$$#++XXXXX@   ",
"   .XXXXXoOO#####$OOOOo###oOOOO#####O++XXXXX@   ",
"   .XXXXXoOOOOO%o+OOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOo%O#OOOOOOOOOOO##OOOOO++XXXXX@   ",
"   .XXXXXoOOOOO$%O&XXOOOOOOOO####OOOO++XXXXX@   ",
"   .XXXXXoOOOOOO%$&&&#OOOOOO#####OOOO++XXXXX@   ",
"   .XXXXXoOOOOOO##.&**#OOOO#####OOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOO#XO***#OO#####OOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOO%XO***o#####OOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOO%XO**#####OOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOO%XO#####OOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOo#####oOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOO#####**#OOOOOOOO++XXXXX@   ",
"   .XXXXXX++++++++++#####O***#+++++++XXXXXXX@   ",
"   .XXXXXXXXXXXXXXX#####oXO***#XXXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXXX#####XX%XO**X#XXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXX#####XXXX%XOX&&#XXXXXXXXXXX@   ",
"   .XXXXXXXXX##o#####o#####%XO&=-#o####XXXXX@   ",
"   .XXXXXXXX#..#####........%X=-=#XXX$$XXXXX@   ",
"   .XXXXXXXX#...###..........%o=-#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@oo##.........%%%oXXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"    .XXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"     .XXXXXX#....................#XXX$$XXXXX@   ",
"      .XXXXX#....................#XXX$$XXXXX@   ",
"       .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    ",
"                                                ",
"                                                "};
