/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtopencdrom_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray6	m black	c #636363636363",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor6	m white	c yellow",
"&	s iconGray5	m black	c #737373737373",
"*	s iconColor7	m white	c cyan",
"=	s iconColor4	m white	c green",
/* pixels */
"               ......           ",
"    ...........XXXXXXo.O        ",
"   .OOOOOOOOOOXXXXXXXXo..       ",
"   .OOOOOOOOOOOOOOOOOOOoO.      ",
"   .OOOOOOOOOOOOOOOOOOOo+@+     ",
"   .OOOOOOOOOOOOOOOOOOOo.+@#    ",
"  ..OOOOOOOO...................o",
"  ..OOOOOOO.$$$$$$$$$$$$$$$$$$o ",
" ...OOOOOO.$$$$$$$$$$$$$$$$$$o  ",
" .%.OOOOO.$$$$$$$$$$$$$$$$$$oO& ",
"..@.OOOO.$$$$$$$$$$$$$$$$$$o+@# ",
"..@.OOO.$$$$$$$$$$$$$$$$$$o+++& ",
".@+.OO.$$$$$$$$$$$$$$$$$$o++++O&",
".@+.O.$$$$$$$$$$$$$$$$$$o+++++@&",
".@+..$$$$$$$$$$$$$$$$$$o++.+++@&",
".@++ooooooooooooooooooo+++++++@&",
".@++.+++++&.+.&@@&..+&++++++++@&",
".@+++++.++&+..+&&+.+.&+*..++++@&",
".@++.+++++@&+.....+.&@%***..++@&",
".O+++++**++&@+.+.+.+&+*+%%***+O&",
"O.+++**%..++&&+.+.&&+.%*++%%++& ",
" .@+*++..+%%*@&&&&@+.*.%*@++%@& ",
" .O++..+++%++++++++@%.*.%*+@+O& ",
" O.++.+++%+++++++..=+%.*.%*++&  ",
"  .O+++++++++.+++%..=+%.*.%+O&  ",
"   .@+++%+++++++++.+.=+@.*.@&   ",
"    +@+%+*++++++++%.+.=%+.@&    ",
"     &@+*+++.++.++++.+.=%@&     ",
"      &O++++++++++++.+.+O&      ",
"       &&O+++++++++++@O&&       ",
"         &&&O@@@@@@O&&&         ",
"            &&&&&&&&            "};
