/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtfmtpcmem_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconColor6	m white	c yellow",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray4	m white	c #949494949494",
"#	s iconColor1	m black	c black",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconGray8	m black	c #212121212121",
"&	s iconGray7	m black	c #424242424242",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconColor3	m black	c red",
"-	s iconColor5	m black	c blue",
/* pixels */
"                                ",
"                  ............  ",
"                 ...XoooooOo+o  ",
"                @X.XoooooOoOo#  ",
"               @$@XoooooOoOo%   ",
"              ..@$O$oooOoOo%    ",
"             ..X$O$O$oOoOo%     ",
"            ..X$$@O$O@oOo%      ",
"           ..X$$@@@O$O@o%       ",
"          ..X$$@@@@@O$O&        ",
"  .......@.X$$@@@@@@OO&........@",
" ..*****@$@$$@@@@@@OO&*********%",
".*.****X=@$O@@@@@@OO&**********%",
".#.**.X=X=O$O@@@@OO&.........**%",
".#.**X=X=X=O$O@@OO&XXXXXXXXX@**%",
".*.**XX=X===O$OOO&XXXXXXXXXX@**%",
".*.**==X===&=O*O&XXXXXXXXXXX@**%",
".#.**.====&=&=O&XXXXXXXXXXXX@**%",
".#.**.X==&=&=&&XXX.......XXX@**%",
".*.**.XX==&=&&....------%XXX@**%",
".*.**.XXX==&&****--------%XX@**%",
".#.**.XXXX&&.............+#X@**%",
".#.**.XXXX.*************++#X@**%",
".*.**.XXXX.*************++#X@**%",
".*.**.@@@@.*************++#@@**%",
".#.*******.*************++#****%",
".#.*******.*************++#****%",
".*&%%%%%%%.*************++#%%%%&",
".&%%%%%%%%.*************++#%%%& ",
"          .*************++#     ",
"          .++++++++++++++%#     ",
"           ###############      "};
