/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwpfloppyvol_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray7	m black	c #424242424242",
"%	s iconGray4	m white	c #949494949494",
"&	s iconColor2	m white	c white",
"*	s iconColor6	m white	c yellow",
"=	s iconColor3	m black	c red",
"-	s iconColor8	m black	c magenta",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"    ........................................    ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOO#o+OOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOo#+$OOOOOOOOOOO$$OOOOO++XXXXX@   ",
"   .XXXXXoOOOOO%#+&XXOOOOOOOO$$$$OOOO++XXXXX@   ",
"   .XXXXXoOOOOOO#%&&&$OOOOOO$$$$$OOOO++XXXXX@   ",
"   .XXXXXoOOOOOO$$.&**$OOOO$$$$$OOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOO$XO***$OO$$$$$OOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOO#XO***o$$$$$OOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOO#XO**$$$$$OOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOO#XO$$$$$OOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOo$$$$$oOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOO$$$$$**$OOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOO$$$$$O***$OOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOO$$$$$oXO***$OOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOO$$$$$OO#XO**X$OOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOO$$$$$OOOO#XOX&&$OOOO++XXXXX@   ",
"   .XXXXXoOOOOOO$$$$$OOOOOO#XO&=-$OOO++XXXXX@   ",
"   .XXXXXoOOOOOO$$$$OOOOOOOO#X=-=$OOO++XXXXX@   ",
"   .XXXXXoOOOOOOO$$OOOOOOOOOO#o=-$OOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOO###OOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXX+++++++++++++++++++++++++++XXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX@   ",
"   .XXXXXXXX$....................$XXX%%XXXXX@   ",
"   .XXXXXXXX$....................$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@$$$$............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"   .XXXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"    .XXXXXXX$...@%%%%............$XXX%%XXXXX@   ",
"     .XXXXXX$....................$XXX%%XXXXX@   ",
"      .XXXXX$....................$XXX%%XXXXX@   ",
"       .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    ",
"                                                ",
"                                                "};
