/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtopenpcmem_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor5	m black	c blue",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray4	m white	c #949494949494",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconColor1	m black	c black",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconGray7	m black	c #424242424242",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"               ......           ",
"    ...........XXXXXXo          ",
"   .OOOOOOOOOOXXXXXXXXo         ",
"   .OOOOOOOOOOOOOOOOOOOo        ",
"  +.OOOOOOOOOOOOOOOOOOOo.......O",
" .+.OOOOOOOOOOOOOOOOOOOo@@@@@@@o",
".@+.OOOOOOOO...................o",
".#+.OOOOOOO.@@@@@@@@@@@@@@@@@@oo",
".#+.OOOOOO.@@@@@@@@@@@@@@@@@@o@o",
".@+.OOOOO.@@@@@@@@@@@@@@@@@@o@@o",
".@+.OOOO.@@@@@@@@@@@@@@@@@@oO@@o",
".#+.OOO.@@@@@@@@@@@@@@@@@@o$O@@o",
".#+.OO.@@@@@@@@@@@@@@@@@@o$+O@@o",
".@+.O.@@@@@@@@@@@@@@@@@@o$++O@@o",
".@+..@@@@@@@@@@@@@@@@@@o$+++O@@o",
".#+@ooooooooooooooooooo$++++O@@o",
".#+@@.++++++++++++++++++++++O@@o",
".@+@@.++++++++++++++++++++++O@@o",
".@+@@.OOOOOOOOOOOOOOOOOOOOOOO@@o",
".#+@@@@@@@@@@@@@@@@@@@@@@@@@@@@o",
".#+@@@@@@@@@@@@@@@@@@@@@@@@@@@@o",
".@%oooooooooooooooooooooooooooo%",
".%oooooooooooooooooooooooooooo% "};
