/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * sdtcdrvol_48_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconColor7	m white	c cyan",
"+	s iconColor6	m white	c yellow",
"@	s iconColor4	m white	c green",
"#	s iconGray4	m white	c #949494949494",
"$	s iconGray5	m black	c #737373737373",
/* pixels */
"                   ..........                   ",
"                ...XXXXXXXXXX...                ",
"             ...XXXooooooooooXXX...             ",
"            .XXXooooooooooooooooXXX.            ",
"          ..XooooooooooooooooooooooX..          ",
"         .XXo..oooooooooooo.ooooooOoXX.         ",
"        .Xo.++.ooooooo.oooooooooo.OoooX.        ",
"       .X@o.o+..oooooooooooooooooOoo..oX#       ",
"      .Xo.@..o+..ooooooooo.ooooooOo..o.oX$      ",
"     .Xo++o@..++..ooooooooooooooOoo.ooo+.X$     ",
"    .XoOO++o@o.o+.ooooo.ooooooo.Oo.oo++o..X$    ",
"    .X..OOo+o@..o..ooooooooooooOo..o++o..oX$    ",
"   .Xo+.oOOo+.@..o.ooooooooooo.O..o++o..oooX$   ",
"  .Xooo+..oOO+o@....ooooooooooOo.o++o.ooooooX$  ",
"  .XO..oo+..OO++@.+.ooooooooo.O.o++..oooooooX$  ",
"  .X+O...oo..OO+.@oXX$$$$$$XXO..++..ooooooooX$  ",
" .Xoo+++...o+..O+o$$$.o.o.o$$$.o+..oooooo.oooX$ ",
" .Xoooo+++O..++.oo$o.o.o.o.o.$o+.ooooooooooooX$ ",
" .Xooooooo++...o$$o.o.o.o.o.o.$$oooooooooooooX$ ",
".Xo.ooooOoo++o.O$o.o.o.o.o.o.o.$XoooooooooooooX$",
".Xooo...oOOOO++X$.o.o.......o.o$Xooooo.oooooooX$",
".Xooooo....ooOO$.o.o.o$$$$o..o.o$oooooooooooooX$",
".Xoooooooo...oO$o.o..$XXXX$.o.o.$oooooooooo.ooX$",
".Xooooooooooo.o$.o.o.$XXXX$..o.o$oooooooooooooX$",
".Xooooooooooooo$o.o..$XXXX$.o.o.$oooooo.ooooooX$",
".Xooooooooooooo$.o.o.$XXXX$..o.o$oooooooooooooX$",
".Xoooo.oooooooo$o.o..o$$$$o.o.o.$.ooooooooooooX$",
".Xoooooooo.ooooX$o.o.......o.o.$XO...oooooooooX$",
".XoooooooooooooX$.o.o.o.o.o.o.o$X+OO...oooooooX$",
" .Xoooooooooooo.$$.o.o.o.o.o.o$$Oo++oO...ooooX$ ",
" .Xooooooooooo.oOo$.o.o.o.o.o$ooO...++oOO..ooX$ ",
" .Xooooo.oooo..Oo.$$$o.o.o.$$$o++OO..+++oOO.oX$ ",
"  .Xoooooooo..O..ooXX$$$$$$XX@..++OO..o+++oOX$  ",
"  .Xoooooo...O..oo+Oooooooooo.@..o++OO..o++oX$  ",
"  .Xooooo..OO..ooo+oooooooooo..@..o++OO...ooX$  ",
"   .Xooo..OO..ooo+oooooooooooo.@@..o++oOO..X$   ",
"    .X...OO...oo++oooooooooooo..@@..o++oOOX$    ",
"    .X.oOoo..ooo+ooooo.oooooooo.+@@..o++ooX$    ",
"     .XOoo...oo+o.ooooooooooooo..o@@..o+oX$     ",
"      .Xo.o.oo++.ooooooooooooooo.+o@o..oX$      ",
"       #Xo.ooo+o.ooo.ooooooooooo..+o@o.X$       ",
"        $Xooo+o.Ooooooooooooo.ooo..o@@X$        ",
"         $XXo+oOoooooooooooooooooo.+XX$         ",
"          $$XooOoooooooo.ooooooooo.X$$          ",
"            $XXXooooooooooooooooXXX$            ",
"             $$$XXXooooooooooXXX$$$             ",
"                $$$XXXXXXXXXX$$$                ",
"                   $$$$$$$$$$                   "};
