/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtfloppyvol_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray4	m white	c #949494949494",
/* pixels */
"                                ",
"                                ",
"                                ",
" ..........................     ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXX++++++++++++++++++XXXX@    ",
".XXXXXXXXXXXXXXXXXXXXXXXXXX@    ",
".XXXXXXXXXXXXXXXXXXXXXXXXXX@    ",
".XXXXXX#################XXX@    ",
".XXXXX#.............#XX+XXX@    ",
".XXXXX#.@@@.........#XX+XXX@    ",
".XXXXX#.@$$.........#XX+XXX@    ",
".XXXXX#.@$$.........#XX+XXX@    ",
".XXXXX#.@$$.........#XX+XXX@    ",
".XXXXX#.@$$.........#XX+XXX@    ",
" .XXXX#.............#XX+XXX@    ",
"  .XXX#.............#XX+XXX@    ",
"   .@@@@@@@@@@@@@@@@@@@@@@@     "};
