/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtejctcdrom_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconColor1	m black	c black",
"#	s iconGray5	m black	c #737373737373",
"$	s iconColor6	m white	c yellow",
"%	s iconGray1	m white	c #dededededede",
"&	s iconColor4	m white	c green",
"*	s iconColor7	m white	c cyan",
"=	s iconGray6	m black	c #636363636363",
"-	s iconColor8	m black	c magenta",
";	s iconGray8	m black	c #212121212121",
/* pixels */
"      .....         X...........",
" ooooO..    +++++++X   X........",
" ooo@#  +++$%%%%%%%%%+X  .......",
" ooo@# +  % %%% %%% %%%%X ......",
" ooo@#+$& % %%%%%%%%%%*%%+%.....",
" ooo@# %$& % $%%%% %  *% %+=....",
" ooo@#*  %& % %% %%% *   %%+=...",
" ooo@# * $%&  $%%%%% -* %%%%X#..",
" ooo@#$ * $%&  %%%%% *-* %%%%#..",
" ooo@#*$ * $%&  %%%* -*-* %%%X#.",
" ooo@#%*$ * $+####+* *-*-* %%+=.",
" ooo@#%%*$ *## %     -*-*-* %%#.",
" ooo@#$$%*$#% %  *-*-*-*-*-* %X#",
" ooo@#***$+# %   -*-*-*-*-*-* +#",
" ooo@#  **# % %# *-*-*-*-*-*-* #",
" ooo@#%%%%#%  #+ -*-*-*-*-*-*-* ",
" ooo@#%%%%# % #+ *-*-*-*-*-*-*-@",
" ooo@#% %%#%  %# -*-*-*-*-*-*-@#",
" ooo@#%%%%+#%    *-*-*-*-*-*-@+#",
" ooo@#%**%%#+% % -*-*-*-*-*-@%X#",
" ooo@#*$  %%##%  ;;; *-*-*-@%%#.",
" ooo@#%  %$$*+####+% -*-*-@%$+#.",
" ooo@# %%%$%%%%%%%%+ *-*-@%+%X#.",
" ooo@#%%%$%%%%%%%  & -*-@$*%%#..",
" ooo@#%%%%%%% %%%$   *-@* $%X#..",
" ooo@#%%$%%%%%%%%% % -@+ * +#...",
" ooo@#%$%*%%%%%%%%$  @&$% +#....",
" ooo@#+%*%%% %% %%%% % &$+#.....",
" ooo@##X%%%%%%%%%%%% % %X#......",
" ooo@#.##X%%%%%%%%%%%+X##.......",
" oooo#...###X++++++X###.........",
"o@@@@@......########............"};
