/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtcdromvol_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray8	m black	c #212121212121",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconGray7	m black	c #424242424242",
"$	s iconColor7	m white	c cyan",
"%	s iconColor6	m white	c yellow",
"&	s iconGray4	m white	c #949494949494",
"*	s iconGray5	m black	c #737373737373",
"=	s iconColor4	m white	c green",
"-	s iconColor3	m black	c red",
";	s iconColor8	m black	c magenta",
/* pixels */
"                   ..........                   ",
"                ...XXXXXXXXXX...                ",
"             ...XXXooooooooooXXX...             ",
"            .XXXooooooooooooooooXXX.            ",
"          ..XooO+@oooooooooooooooooX..          ",
"         .XXo..+O@#oooooooo.oo##oo$oXX.         ",
"        .Xo.%%.@O@.&*o.oooooo####o$oooX.        ",
"       .X=o.o%..O&...#oooooo#####$oo..oX*       ",
"      .Xo.=..o%.##o.%%#ooo.#####o$o..o.oX*      ",
"     .Xo%%o=..%%.#*X%%%#oo#####o$oo.ooo%.X*     ",
"    .Xo$$%%o=o.o%.O*X%%%+#####o.$o.oo%%o..X*    ",
"    .X..$$o%o=..o..O*X%%#####oo$o..o%%o..oX*    ",
"   .Xo%.o$$o%.=..o.oO*X#####oo.$..o%%o..oooX*   ",
"  .Xooo%..o$$%o=....o+#####+oo$o.o%%o.ooooooX*  ",
"  .X$..oo%..$$%%=.%.o#####%%#.$.o%%..oooooooX*  ",
"  .X%$...oo..$$%.=oX#####X%%%#..%%..ooooooooX*  ",
" .Xoo%%%...o%..$%oX#####+*X%%%#o%..oooooo.oooX* ",
" .Xoooo%%%$..%%.oo#####o.O*X%%*#.ooooooooooooX* ",
" .Xooooooo%%...oX#####o.o.O*X*..#ooooooooooooX* ",
".Xo.oooo$oo%%o.$#####o.o.o.O*X.-;#ooooooooooooX*",
".Xooo...o$$$$%%#####o.......O*-;-#oooo.oooooooX*",
".Xooooo....oo$$X###o.o****o..O+-;#ooooooooooooX*",
".Xoooooooo...o$*o#o..*XXXX*.o.OOOoooooooooo.ooX*",
".Xooooooooooo.o*.o.o.*XXXX*..o.o*oooooooooooooX*",
".Xooooooooooooo*o.o..*XXXX*.o.o.*oooooo.ooooooX*",
".Xooooooooooooo*.o.o.*XXXX*..o.o*oooooooooooooX*",
".Xoooo.oooooooo*o.o..o****o.o.o.*.ooooooooooooX*",
".Xoooooooo.ooooX*o.o.......o.o.*X$...oooooooooX*",
".XoooooooooooooX*.o.o.o.o.o.o.o*X%$$...oooooooX*",
" .Xoooooooooooo.**.o.o.o.o.o.o**$o%%o$...ooooX* ",
" .Xooooooooooo.o$o*.o.o.o.o.o*oo$...%%o$$..ooX* ",
" .Xooooo.oooo..$o.***o.o.o.***o%%$$..%%%o$$.oX* ",
"  .Xoooooooo..$..ooXX******XX=..%%$$..o%%%o$X*  ",
"  .Xoooooo...$..oo%$ooooooooo.=..o%%$$..o%%oX*  ",
"  .Xooooo..$$..ooo%oooooooooo..=..o%%$$...ooX*  ",
"   .Xooo..$$..ooo%oooooooooooo.==..o%%o$$..X*   ",
"    .X...$$...oo%%oooooooooooo..==..o%%o$$X*    ",
"    .X.o$oo..ooo%ooooo.oooooooo.%==..o%%ooX*    ",
"     .X$oo...oo%o.ooooooooooooo..o==..o%oX*     ",
"      .Xo.o.oo%%.ooooooooooooooo.%o=o..oX*      ",
"       *Xo.ooo%o.ooo.ooooooooooo..%o=o.X*       ",
"        *Xooo%o.$oooooooooooo.ooo..o==X*        ",
"         *XXo%o$oooooooooooooooooo.%XX*         ",
"          **Xoo$oooooooo.ooooooooo.X**          ",
"            *XXXooooooooooooooooXXX*            ",
"             ***XXXooooooooooXXX***             ",
"                ***XXXXXXXXXX***                ",
"                   **********                   "};
