/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtpcmemvol_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconColor5	m black	c blue",
"$	s iconGray5	m black	c #737373737373",
"%	s iconGray7	m black	c #424242424242",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"  .............................X",
" ..ooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooO",
".+.oo........................ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".+.oo.@@@@@@@@@@@@.......@@@XooO",
".o.oo.@@@@@@......######O@@@XooO",
".o.oo.@@@@@.ooooo########O@@XooO",
".+.oo.@@@@...............$+@XooO",
".+.oo.@@@@.ooooooooooooo$$+@XooO",
".o.oo.@@@@.ooooooooooooo$$+@XooO",
".o.oo.XXXX.ooooooooooooo$$+XXooO",
".+.ooooooo.ooooooooooooo$$+ooooO",
".+.ooooooo.ooooooooooooo$$+ooooO",
".o%OOOOOOO.ooooooooooooo$$+OOOO%",
".%OOOOOOOO.ooooooooooooo$$+OOO% ",
"          .ooooooooooooo$$+     ",
"          .$$$$$$$$$$$$$$O+     ",
"           +++++++++++++++      "};
