/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtdosfloppy_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray4	m white	c #949494949494",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"    ........................................    ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOO#####$OOOOo###oOOOO#####O++XXXXX@   ",
"   .XXXXXoOO#$OOO#$OOo$OOO$oOO#$OOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#OO#OOOOO#OO#$OOOO#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$O#$$OOOO++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OO####$O++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OOOOO$#$++XXXXX@   ",
"   .XXXXXoOO#$OOO$#O$#OOOOO#$OOOOOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO$#OO#OOOOO#OO#OOOO$#++XXXXX@   ",
"   .XXXXXoOO#$OOO#$OOo$OOO$oOO#$OO$$#++XXXXX@   ",
"   .XXXXXoOO#####$OOOOo###oOOOO#####O++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOOOOOO++XXXXX@   ",
"   .XXXXXX+++++++++++++++++++++++++++XXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@   ",
"   .XXXXXXXXX##########################XXXXX@   ",
"   .XXXXXXXX#....................#XXX$$XXXXX@   ",
"   .XXXXXXXX#....................#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@####............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"   .XXXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"    .XXXXXXX#...@$$$$............#XXX$$XXXXX@   ",
"     .XXXXXX#....................#XXX$$XXXXX@   ",
"      .XXXXX#....................#XXX$$XXXXX@   ",
"       .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    ",
"                                                ",
"                                                "};
