/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * Fpopenfloppy_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray5	m black	c #737373737373",
"+	s iconColor1	m black	c black",
"@	s iconColor2	m white	c white",
"#	s iconColor5	m black	c blue",
"$	s iconGray8	m black	c #212121212121",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray7	m black	c #424242424242",
/* pixels */
"                                                ",
" ..........................................     ",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo    ",
".XOOOOO.oooooooooooooooooooooooooooooOOOOO+o    ",
".XOOOOO.oooooooooooooooo@@@@@@@@@ooooOOOOO+o    ",
".XOOOOO.ooooooooooooooo@#########$oooOOOOO+o    ",
".XOOOO@@@@@@@@@@@@@@@@@###########$ooOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%#############$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%$oOOOOO+o    ",
".XOOO@%%%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
".XOOO@%%%%%%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$",
".XOOO@%%%%%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$ ",
".XOOO@%%%%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$  ",
".XOOO@%%%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$   ",
".XOOO@%%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$    ",
".XOOO@%%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$o    ",
".XOOO@%%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$%o    ",
".XOOO@%%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$O+o    ",
".XOOO@%%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$OO+o    ",
".XOOO@%%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$OOO+o    ",
".XOOO@%@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$OOOO+o    ",
".XOOO@@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$OOOOO+o    ",
".XOOO@&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$OOOOOO+o    ",
".XOOOO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$OOOOOOO+o    ",
".XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o    ",
".XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o    ",
".XOOOOOOOOO**************************OOOOO+o    ",
".XOOOOOOOO*XXXXXXXXXXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXXXXXXXXXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+****XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
".XOOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
" .XOOOOOOO*XXX+%%%%XXXXXXXXXXXX*OOO%%OOOOO+o    ",
"  .XOOOOOO*XXXXXXXXXXXXXXXXXXXX*OOO%%OOOOO+o    ",
"   .XOOOOO*XXXXXXXXXXXXXXXXXXXX*OOO%%OOOOO+o    ",
"    .X++++++++++++++++++++++++++++++++++++o     ",
"     .oooooooooooooooooooooooooooooooooooo      ",
"                                                ",
"                                                "};
