/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwppcmemvol_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor5	m black	c blue",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray5	m black	c #737373737373",
"*	s iconColor6	m white	c yellow",
"=	s iconColor8	m black	c magenta",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"  .............................X",
" ..ooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooO",
".+.oo........................ooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".o.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".+.oo.@@@@@@@@@@@@@@@@@@@@@@XooO",
".+.oo.@@@@@@@@@@@@.......@@@XooO",
".o.oo.@@@@@@O#....$$$$$$O@@@XooO",
".o.oo.@@@@@.#OO%o$$$$$%%$O@@XooO",
".+.oo.@@@@...O..O....%%%.&+@XooO",
".+.oo.@@@@.oo%.OX%oo%%%o&&+@XooO",
".o.oo.@@@@.oooO&**&%%%oo&&+@XooO",
".o.oo.XXXX.ooooO&*%%%ooo&&+XXooO",
".+.ooooooo.ooooo#%%%&ooo&&+ooooO",
".+.ooooooo.ooooo%%%**%oo&&+ooooO",
".o%OOOOOOO.oooo%%%&&**%o&&+OOOO%",
".%OOOOOOOO.ooo%%%ooO&*#%&&+OOO% ",
"          .oo%%%ooooO&==%&+     ",
"          .&&%%&&&&&&O#=#O+     ",
"           +++++++++++O#++      "};
