/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtwpfloppyvol_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor1	m black	c black",
"#	s iconGray8	m black	c #212121212121",
"$	s iconGray7	m black	c #424242424242",
"%	s iconColor2	m white	c white",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor6	m white	c yellow",
"=	s iconColor8	m black	c magenta",
/* pixels */
"                                ",
"                                ",
"                                ",
" ..........................     ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXoOOO#oOOOOOOOOOOOOO+XXX@    ",
".XXXoOOOo##$OOOOOO$$OOO+XXX@    ",
".XXXoOOOO#%%#OOOO$$$OOO+XXX@    ",
".XXXoOOOO$%#&$OO$$$OOOO+XXX@    ",
".XXXoOOOOO#X**X$$$OOOOO+XXX@    ",
".XXXoOOOOOO#X*$$$OOOOOO+XXX@    ",
".XXXoOOOOOOOo$$$XOOOOOO+XXX@    ",
".XXXoOOOOOOO$$$**$OOOOO+XXX@    ",
".XXXoOOOOOO$$$XX**$OOOO+XXX@    ",
".XXXoOOOOO$$$OO#X*o$OOO+XXX@    ",
".XXXoOOOO$$$OOOO#X==$OO+XXX@    ",
".XXXoOOOO$$OOOOOO#o=oOO+XXX@    ",
".XXXoOOOOOOOOOOOOO#oOOO+XXX@    ",
".XXXoOOOOOOOOOOOOOOOOOO+XXX@    ",
".XXXX++++++++++++++++++XXXX@    ",
".XXXXXXXXXXXXXXXXXXXXXXXXXX@    ",
".XXXXXXXXXXXXXXXXXXXXXXXXXX@    ",
".XXXXXX$$$$$$$$$$$$$$$$$XXX@    ",
".XXXXX$.............$XX+XXX@    ",
".XXXXX$.@@@.........$XX+XXX@    ",
".XXXXX$.@&&.........$XX+XXX@    ",
".XXXXX$.@&&.........$XX+XXX@    ",
".XXXXX$.@&&.........$XX+XXX@    ",
".XXXXX$.@&&.........$XX+XXX@    ",
" .XXXX$.............$XX+XXX@    ",
"  .XXX$.............$XX+XXX@    ",
"   .@@@@@@@@@@@@@@@@@@@@@@@     "};
