/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * SDtfmtfloppy_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray6	m black	c #636363636363",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconColor2	m white	c white",
"@	s iconColor6	m white	c yellow",
"#	s iconGray4	m white	c #949494949494",
"$	s iconColor1	m black	c black",
"%	s iconGray8	m black	c #212121212121",
"&	s iconGray3	m white	c #adadadadadad",
"*	s iconGray7	m black	c #424242424242",
"=	s iconColor3	m black	c red",
/* pixels */
"                                ",
"                                ",
"                                ",
" ..........................     ",
".XXXoOOOOOOOOOOO+++.@@@@@o@o    ",
".XXXoOOOOOOOOOO+++.@@@@@o@o#    ",
".XXXoOOOOOOOOO#.+.@@@@@o@o@$    ",
".XXXoOOOOOOOO#O#.@@@@@o@o@%$    ",
".XXXoOOOOOOO++#OoO@@@o@o@%X$    ",
".XXXoOOOOOO++.OoOoO@o@o@%XX$    ",
".XXXoOOOOO++.OO#oOo#@o@%XXX$    ",
".XXXoOOOO++.OO###oOo#@%&XXX$    ",
".XXXoOOO++.OO#####oOo*O&XXX$    ",
".XXXoOO#+.OO######oo*OO&XXX$    ",
".XXXoO#O#OO######oo*OOO&XXX$    ",
".XXXo.=#Oo######oo*OOOO&XXX$    ",
".XXX.=.=oOo####oo*OOOOO&XXX$    ",
".XX.=.=.=oOo##oo*OOOOOO&XXX$    ",
".XX..=.===oOooo*OOOOOOO&XXX$    ",
".XX==.===*=o&o*&&&&&&&&XXXX$    ",
".XXX====*=*=o*XXXXXXXXXXXXX$    ",
".XXXX==*=*=**XXXXXXXXXXXXXX$    ",
".XXXXX==*=**o***********XXX$    ",
".XXXXXo==**.........*XX&XXX$    ",
".XXXXX*.**O.........*XX&XXX$    ",
".XXXXX*.#O#.........*XX&XXX$    ",
".XXXXX*.$##.........*XX&XXX$    ",
".XXXXX*.$##.........*XX&XXX$    ",
".XXXXX*.$##.........*XX&XXX$    ",
" .XXXX*.............*XX&XXX$    ",
"  .XXX*.............*XX&XXX$    ",
"   .$$$$$$$$$$$$$$$$$$$$$$$     "};
