/* XPM */
/*********************************************************************
*  (c) Copyright 1996 Sun Microsystems, Inc.
**********************************************************************/
static char * sdtpccard_48_xpm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray8	m black	c #212121212121",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #dededededede",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"  .............................................X",
" ..ooooooooooooooooooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.oooo....................................ooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".o.oooo.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@XooooO",
".+.oooo.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooooO",
".+.ooooooooooooooooooooooooooooooooooooooooooooO",
".+.ooooooooooooooooooooooooooooooooooooooooooooO",
".o.ooooooooooooooooooooooooooooooooooooooooooooO",
".o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#",
".$OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO# ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
