/* XPM */
static char * SDtSpace_t_pm[] = {
"16 16 4 1",
" 	c #000000000000",
".	c #6D6D6D6D5555",
"X	c #B6B6B6B6AAAA",
"o	c #9292B6B6AAAA",
"                ",
"  ........   X  ",
"  ........   X  ",
"  ........   X  ",
"  XXXXXXXXXXXX  ",
"                ",
"  ooo        X  ",
"  ooo        X  ",
"  ooo        X  ",
"  XXXXXXXXXXXX  ",
"                ",
"  ooooooooo  X  ",
"  ooooooooo  X  ",
"  ooooooooo  X  ",
"  XXXXXXXXXXXX  ",
"                "};
