/* XPM */
static char * Shred_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconColor3	m black	c red",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray7	m black	c #424242424242",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray4	m white	c #949494949494",
/* pixels */
"   .........................    ",
"   .XXXXXXXXXXXXXXXXXXXXXXXo    ",
"   .XXXXXXXX.......XXXXXXXXo    ",
"   .XXXXXXXX.OOOOOOXXXXXXXXo    ",
"   .XXXXXXXX.OOOOOOXXXXXXXXo    ",
"   .XXXooXoX.OOOOOOXXooXXXXo    ",
"   .XXXXXXXX.OOOOOOXXXXXXXXo    ",
"   .XXXX.....OOOOOO....XXXXo    ",
"   .XX++XOOOOOOOOOOOOOXoXXXo    ",
"   .XXXXXXOOOOOOOOOOOXXXXXXo    ",
"   .XXooXoXOOOOOOOOOXooXXXXo    ",
"   .XXXXXXXXOOOOOOOXXXXXXXXo    ",
"   .XXoooXooXOOOOOXoXoo@@XXo    ",
"   .XXXXXXXXXXOOOXXXXXXXXXXo    ",
"oooooooooooooooOoooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooo",
"                                ",
"   .X XXX XXX XXX XXX XXX Xo    ",
"   .X XXX XXX XXX XXX XXX Xo    ",
"   .X Xoo @@X ooX XX@ @oX Xo    ",
"   .X XXX XXX XXX XXX XXX Xo    ",
"   .X o#@ Xo@ Xoo XX@ @oX Xo    ",
"   .# XXX XXX XXX XXX XXX Xo    ",
"    $ @X# #@# #@X @#o oXX Xo    ",
"      XX% XXX XXX XXX #XX #o    ",
"      #oX #Xo X## X#X ##X #o    ",
"      XX# X#X #XX #$X X#X Xo    ",
"      #X# ##$ X#  X#$ #$  $     ",
"      #XX #X# $   #XX X#        ",
"      oo  o o o     o o         "};
