/* XPM */
/*********************************************************************
*  Copyright (c) 1996 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * estar_off_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 6 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconColor3	m black	c red",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s iconGray8	m black	c #212121212121",
/* pixels */
"                   .........                    ",
"               ....XXXXXXXXX....                ",
"             ..XXXXXXXXXXXXXXXXX..              ",
"           ..XXXXXXXXXXXXXXXXXXXXX..            ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXX.           ",
"         .XXXXXXXXXXooOOOooXXXXXXXXXX.          ",
"        .XXXXXXXooOOOOOOOOOOOooXXXXXXX.         ",
"       .XXXXXXooOOOOOOOOOOOOOOOooXXXXXX.        ",
"      .XXXXXoOOOOOOOOOOOOOOOOOOOOooXXXXX.       ",
"     .XXXXXXoOOOOOOOOOOOOOOOOOOOOOOoXXXXX.      ",
"    .XXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOoXXXXX.     ",
"   .XXXXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOoXXXXX.    ",
"   .XXXXoXXXXXXOOOOOOOOOOOOOOOOOOOOOOOoXXXX.    ",
"  .XXXXXoOXXXXXXOOOOOOOOOOOOOOO+++OOOOoXXXXX.   ",
"  .XXXXoOOOXXXXXXOOOOOOOOOOOOO.+++OOOOOoXXXX.   ",
" .XXXXXoOOOOXXXXXXOOOO++++++++++++OOOOOoXXXXX.  ",
" .XXXXoOOOOOOXXXXXXOO+++++++++++++OOOOOOoXXXX.  ",
" .XXXXoOOOOOOOXXXXXX++++++++++++++++++++oXXXX.  ",
" .XXXXOOOOOOOOOXXXXXX+++++++++++++++++++OXXXX.  ",
".XXXXXOOOOOOOOO.XXXXXX++++++++++++OOOOOOOXXXXX. ",
".XXXXoOOOOOOOo+++XXXXXX+++++++++++OOOOOOOoXXXX. ",
".XXXXoOOOOOO++++++XXXXXX++++++++++OOOOOOOoXXXX. ",
".XXXXOOOOOO++++++++XXXXXX+++++++++OOOOOOOOXXXX. ",
".XXXXOOOOO++++++++++XXXXXX++++++++OOOOOOOOXXXX. ",
".XXXXOOOO.+++++++++++XXXXXX+++++++OOOOOOOOXXXX. ",
".XXXXoOOO++++++++oO.++XXXXXX++++++++++++OoXXXX. ",
".XXXXoOO+++++++OOOOO+++XXXXXX+++++++++++OoXXXX. ",
".XXXXXO+++++++OOOOOOO+++XXXXXX++++OOOOOOOXXXXX. ",
" .XXXXO++++++.OOOOOOOO+++XXXXXX+++OOOOOOOXXXX.  ",
"  XXXXO++++++OOOOOOOOOOOOOXXXXXX++OOOOOOoXXXX.  ",
" .XXXXoo++++OOOOOOOOOOOOOOOXXXXXX+OOOOOOoXXXX.  ",
" .XXXXXO+++OOOOOOOOOOOOOOOOOXXXXXXOOOOOoXXXXX.  ",
"  .XXXXoO+.OOOOOOOOOOOOOOOOOOXXXXXXOOOOoXXXX.   ",
"  .XXXXXOOOOOOOOOOOOOOOOOOOOOOXXXXXXOOOXXXXX.   ",
"   .XXXXoOOOOOOOOOOOOOOOOOOOOOOXXXXXXooXXXX.    ",
"   .XXXXXoOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXX.    ",
"    .XXXXXoOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXX.     ",
"     .XXXXXoOOOOOOOOOOOOOOOOOOOOOOXXXXXXX.      ",
"      .XXXXXooOOOOOOOOOOOOOOOOOOOooXXXXX.       ",
"       .XXXXXXooOOOOOOOOOOOOOOOooXXXXXX.        ",
"        .XXXXXXXooOOOOOOOOOOOooXXXXXXX.         ",
"         .XXXXXXXXXXooOOOooXXXXXXXXXX.          ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXX.           ",
"            .XXXXXXXXXXXXXXXXXXXXX.             ",
"              .XXXXXXXXXXXXXXXXX.               ",
"                  .XXXXXXXXX.                   ",
"                                                ",
"                                                "};
