/* XPM */
static char * SDtSpace_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	c #686875757E7E",
"X	s selectColor	m white	c #737373737373",
"o	s background	m black	c #949494949494",
"O	s topShadowColor	m white	c #bdbdbdbdbdbd",
"+	c #9E9EB2B2BFBF",
/* pixels */
"                                ",
"                                ",
"    ........................    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .XXXXXXXXXXXXXXXoooooooO    ",
"    .OOOOOOOOOOOOOOOOOOOOOOO    ",
"                                ",
"                                ",
"    ........................    ",
"    .++++++ooooooooooooooooO    ",
"    .++++++ooooooooooooooooO    ",
"    .++++++ooooooooooooooooO    ",
"    .++++++ooooooooooooooooO    ",
"    .++++++ooooooooooooooooO    ",
"    .++++++ooooooooooooooooO    ",
"    .OOOOOOOOOOOOOOOOOOOOOOO    ",
"                                ",
"                                ",
"    ........................    ",
"    .++++++++++++++++++ooooO    ",
"    .++++++++++++++++++ooooO    ",
"    .++++++++++++++++++ooooO    ",
"    .++++++++++++++++++ooooO    ",
"    .++++++++++++++++++ooooO    ",
"    .++++++++++++++++++ooooO    ",
"    .OOOOOOOOOOOOOOOOOOOOOOO    ",
"                                ",
"                                "};
