/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * shred_trash_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray3	m white	c #adadadadadad",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray7	m black	c #424242424242",
"#	s iconColor2	m white	c white",
"$	s iconColor7	m white	c cyan",
"%	s iconColor1	m black	c black",
"&	s iconColor6	m white	c yellow",
"*	s iconGray5	m black	c #737373737373",
/* pixels */
"      .XXXXXXXXXXXXXXXo.OO      ",
"      X.XXXXXXXXXXXXXXXXX.O     ",
"      X+X++++++++++++++++X@     ",
"      X+X++++++++++++++++X@     ",
"      @+X++++++++++++++++X@     ",
"      X@@@@@@@@@@@@@@@@@@@@     ",
"      oX++++++++++++++++++@     ",
"      .o+.................@     ",
"      .o+.......#.........@     ",
"      oo+.......#X........@     ",
"      .o+.#.....#XO.......@     ",
"      oo+.##....#XO.......@     ",
"      .o+.O$#...#XO.......@     ",
"      oo+..O$#..#XO.......@     ",
"      .o+...O##.#XO.......@     ",
"      oo+....O$##XO.......@     ",
"      .o+.....O#%#O.......@     ",
"      oo+......O##O.......@     ",
"      .o+.......##O.......@     ",
"      oo+......&&O#X&&....@     ",
"      .o+.....&O&O.&OO&...@     ",
"      oo+....&O.&O.&...&..@     ",
"      .o+....&O.&O.O&..&..@     ",
"      oo+....&O.&O..O&&O..@     ",
"      .o+....&O.&O...OO...@     ",
"      oo+.....&&O.........@     ",
"      .o+.....OO..........@     ",
"      oo+.................@     ",
"      .o+.....%%%%%%......@     ",
"      %o+.....%XXXXXX*....@     ",
"       %+.....%%%%%%**....@     ",
"        %%%%%%%%%%%%%%%%%%%     "};
