/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
*  All Rights Reserved
**********************************************************************/
static char * shred_trash_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray2	m white	c #bdbdbdbdbdbd",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor2	m white	c white",
"#	s iconGray6	m black	c #636363636363",
"$	s iconColor7	m white	c cyan",
"%	s iconColor6	m white	c yellow",
"&	s iconColor1	m black	c black",
"*	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                ................XX              ",
"               .X.................X             ",
"               .o.oooooooooooooooo.O            ",
"               .o.oooooooooooooooo.O            ",
"               Oo.oooooooooooooooo.O            ",
"               .OOOOOOOOOOOOOOOOOOOO            ",
"               +.ooooooooooooooooooO            ",
"               X+oXXXXXXXXXXXXXXXXXO            ",
"               X+oXXXXXXX@XXXXXXXXXO            ",
"               ++oXXXXXXX@@XXXXXXXXO            ",
"               X+oXXXXXXX@@#XXXXXXXO            ",
"               ++oX@XXXXX@@#XXXXXXXO            ",
"               X+oX@@XXXX@@#XXXXXXXO            ",
"               ++oX#$@XXX@@#XXXXXXXO            ",
"               X+oXX#@@XX@@#XXXXXXXO            ",
"               ++oXXX#$@X@@#XXXXXXXO            ",
"               X+oXXXX#@@@@#XXXXXXXO            ",
"               ++oXXXXX#$@@#XXXXXXXO            ",
"               X+oXXXXXX#@@#XXXXXXXO            ",
"               ++oXXXXXXX@$@X%%OXXXO            ",
"               X+oXXXXXX%%OX%OO%OXXO            ",
"               ++oXXXXX%OO%O%OXX%OXO            ",
"               X+oXXXXX%OX%OX%XX%OXO            ",
"               ++oXXXXX%OX%OXX%%OXXO            ",
"               X+oXXXXX%OX%OXXOOXXXO            ",
"               ++oXXXXXX%%OXXXXXXXXO            ",
"               X+oXXXXXXXXXXXXXXXXXO            ",
"               ++oXXXXXXXXXXXXXXXXXO            ",
"               X+oXXXXX&&&&&&XXXXXXO            ",
"               &+oXXXXX&......*XXXXO            ",
"                &oXXXXX&&&&&&**XXXXO            ",
"                 &&&&&&&&&&&&&&&&&&&            ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
