/* XPM */
static char * SDtSunBolt_s_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 5 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconColor6	m white	c yellow",
"o	s iconGray7	m black	c #424242424242",
"O	s iconColor2	m white	c white",
/* pixels */
"                        ",
"           ..    Xo     ",
"          ....  Xo      ",
"          .. .OXo       ",
"        .. ..OXo        ",
"       . ..XOXo..       ",
"       .. XOXo. .       ",
"     .. .XOXOXOXOXXo    ",
"    .. .XOXOXOXOXXo.    ",
"   .. ..  oooXOXOo..    ",
"  .. .. .. .XOXOo.. ..  ",
" .. .. ....XOXOo.. .... ",
" .... .. .XOXOo.. .. .. ",
"  .. .. .XOXOo.. .. ..  ",
"    .. .XOXOXOXOXo ..   ",
"    . .XOXOXOXOXo ..    ",
"     .. .oooXOXo ..     ",
"       . ..XOXo..       ",
"       .. XOXo. .       ",
"        .XOXo ..        ",
"        XOo ..          ",
"       XOo....          ",
"      Xo   ..           ",
"                        "};
