/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char *magick[] = {
/* columns rows colors chars-per-pixel */
"32 32 10 1",
"  c Gray13",
". c Gray26",
"X c Gray45",
"o c #5151fb",
"O c Gray58",
"+ c Gray68",
"@ c #c0c0c0",
"# c Gray87",
"$ c Gray100",
"% c None",
/* pixels */
"ooooooooooooooooooo%%%%%%%%%%%%%",
"o  ooo++#++#+o o  o%%%%%%%%%%%%%",
"ooooooooooooooooooo%%%%%%%%%%%%%",
"oXXXXXXXXXXXXXXXXXo%%%%%%%%%%%%%",
"oX..+..+..++++..+Xo%%%%%%%%%%%%%",
"oXOOXOOXOOXXXXXXXXo%%%%%%%%%%%%%",
"oX$$$$$$$$$$$$$O#Xo%%%%%%%%%%%%%",
"oX$$$$ooooooooooooooooooo%%%%%%%",
"oX$$$$o  ooo++#++#+o o  o%%%%%%%",
"oX$$$$ooooooooooooooooooo%%%%%%%",
"oX$$$$oXXXXXXXXXXXXXXXXXo%%%%%%%",
"oX$$$$oX..+..+..++++..+Xo%%%%%%%",
"oX$$$$oXOOXOOXOOXXXXXXXXo%%%%%%%",
"oX$$$$oX$$$$$$$$$$$$$O#Xo%%%%%%%",
"oX$$$$oX$$$$$ooooooooooooooooooo",
"oX$$$$oX$$$$$o  ooo++#++#+o o  o",
"oX$$$$oX$$$$$ooooooooooooooooooo",
"oXXXXXoX$$$$$oXXXXXXXXXXXXXXXXXo",
"oooooooX$$$$$oX..+..+..++++..+Xo",
"%%%%%%oX$$$$$oXOOXOOXOOXXXXXXXXo",
"%%%%%%oX$$$$$oX$$$$$$$$$$$$$O#Xo",
"%%%%%%oX$$$$$oX$$$$$$$$$$$$$O+Xo",
"%%%%%%oX$$$$$oX$$$$$$$$$$$$$OOXo",
"%%%%%%oX$$$$$oX$$$$$$$$$$$$$O$Xo",
"%%%%%%oXXXXXXoX$$$$$$$$$$$$$O$Xo",
"%%%%%%ooooooooX$$$$$$$$$$$$$O$Xo",
"%%%%%%%%%%%%%oX$$$$$$$$$$$$$O$Xo",
"%%%%%%%%%%%%%oX$$$$$$$$$$$$$OOXo",
"%%%%%%%%%%%%%oX$$$$$$$$$$$$$O+Xo",
"%%%%%%%%%%%%%oX$$$$$$$$$$$$$O#Xo",
"%%%%%%%%%%%%%oXXXXXXXXXXXXXXXXXo",
"%%%%%%%%%%%%%ooooooooooooooooooo"
};
