/* XPM */
/*********************************************************************
*  (c) Copyright 1999 Sun Microsystems, Inc.
**********************************************************************/
static char *magick[] = {
/* columns rows colors chars-per-pixel */
"48 48 10 1",
"  c Gray13",
". c Gray26",
"X c Gray45",
"o c #5151fb",
"O c Gray58",
"+ c Gray68",
"@ c #c0c0c0",
"# c Gray87",
"$ c Gray100",
"% c None",
/* pixels */
"oooooooooooooooooooooooooooooooooo%%%%%%%%%%%%%%",
"o  ooooooooo++#++##+#oooooooo o  o%%%%%%%%%%%%%%",
"oooooooooooooooooooooooooooooooooo%%%%%%%%%%%%%%",
"oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo%%%%%%%%%%%%%%",
"oX++++++++++++++++++++++++++++++Xo%%%%%%%%%%%%%%",
"oX+...+...+...++++++++++++++...+Xo%%%%%%%%%%%%%%",
"oX++++++++++++++++++++++++++++++Xo%%%%%%%%%%%%%%",
"oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo%%%%%%%%%%%%%%",
"oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo%%%%%%%%%%%%%%",
"oX$$$$$oooooooooooooooooooooooooooooooooo%%%%%%%",
"oX$$$$$o  ooooooooo++#++##+#oooooooo o  o%%%%%%%",
"oX$$$$$oooooooooooooooooooooooooooooooooo%%%%%%%",
"oX$$$$$oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo%%%%%%%",
"oX$$$$$oX++++++++++++++++++++++++++++++Xo%%%%%%%",
"oX$$$$$oX+...+...+...++++++++++++++...+Xo%%%%%%%",
"oX$$$$$oX++++++++++++++++++++++++++++++Xo%%%%%%%",
"oX$$$$$oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo%%%%%%%",
"oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo%%%%%%%",
"oX$$$$$oX$$$$$oooooooooooooooooooooooooooooooooo",
"oX$$$$$oX$$$$$o  ooooooooo++#++##+#oooooooo o  o",
"oX$$$$$oX$$$$$oooooooooooooooooooooooooooooooooo",
"oX$$$$$oX$$$$$oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
"oX$$$$$oX$$$$$oX++++++++++++++++++++++++++++++Xo",
"oX$$$$$oX$$$$$oX+...+...+...++++++++++++++...+Xo",
"oX$$$$$oX$$$$$oX++++++++++++++++++++++++++++++Xo",
"oX$$$$$oX$$$$$oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
"oX$$$$$oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo",
"oX$$$$$oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OO#Xo",
"oXXXXXXoX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"ooooooooX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oX$$$$$oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%oXXXXXXoX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%ooooooooX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$O##Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OO#Xo",
"%%%%%%%%%%%%%%oX$$$$$$$$$$$$$$$$$$$$$$$$$$$OXXXo",
"%%%%%%%%%%%%%%oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo",
"%%%%%%%%%%%%%%oooooooooooooooooooooooooooooooooo"
};
