/* XPM */
static char * smartcard_overall_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray5	m black	c #737373737373",
"o	s iconColor2	m white	c white",
"O	s iconColor1	m black	c black",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconColor7	m white	c cyan",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor6	m white	c yellow",
/* pixels */
"                       .XX.X    ",
"                     X.oooooOO  ",
"                    XoooooooooO ",
"                   XoooooooooooO",
"                   .XoooooooooOO",
"                   Xo.oooooooX.O",
"                   .oo.X..X.O..O",
"                   XooX+++@+O..O",
"                    XoX@@@@+O.O ",
"                     ..+@+@+OO  ",
" X###################oXOOOOOO   ",
"X#$$$@@@@@@@@@@@@@@$$#o..o+O    ",
"#$%%%%%%%%%%%%%%%%%%%$#.O@oO    ",
"#$%%%%%.....%%%%%%%#%$#.oO.O    ",
"#$%%#%&.*$*$&%%%%%%#%$#X++OO    ",
"#$%##%.*$$*$.%%%%%%%%$#..o+O    ",
"#$###%.$$*$$.%%%%%%#%$#XO@oO    ",
"#$%##%.*$*$*.%%%%%%%%$#.XX.X    ",
"#$%%#%.$*$*$.%%%%%%#%$#oooooOO  ",
"#$%%%%%.....%%%%%%%%%$#oOOOoooO ",
"#$%%%%%%%%%%%%%%%%%%%$#O@@+.oooO",
"#$%%%%%%%%%%%%%%%%%%%$#o...oooOO",
"#$%%%%%%%X..X.X%%%%%%$#ooooooX.O",
"#$%%%%%.XoooooOO%%%%%$XX..X.O..O",
"##$+++XoooOOOoooO+++$#X@@@@+O.OO",
" ####XoooO+@+XoooO###X.@++@+OOoO",
"     .Xooo...oooOO X.oXOOOOOOoOO",
"     .oXooooooo..O .@.oooooooO.O",
"     XooX.XX.XO..O X@@......O..O",
"      Xo.+@+@@O.O   .+.@++@@O.O ",
"       X.@+@++OO     .X@@@++OO  ",
"        .OOOOOO       .OOOOOO   "};
