/* XPM */
static char * smartcard_overall_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray6	m black	c #636363636363",
"X	s iconGray5	m black	c #737373737373",
"o	s iconColor2	m white	c white",
"O	s iconColor1	m black	c black",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray3	m white	c #adadadadadad",
"$	s iconColor7	m white	c cyan",
"%	s iconGray7	m black	c #424242424242",
"&	s iconGray4	m white	c #949494949494",
"*	s iconColor6	m white	c yellow",
/* pixels */
"                                   .X.X...X     ",
"                                 X.ooooooooOO   ",
"                                XooooooooooooO  ",
"                               XooooooooooooooO ",
"                               .XooooooooooooOO ",
"                               Xo.ooooooooooX.O ",
"                               .oo.X.X.XXX.O..O ",
"                               XooX++@+@@@+O..O ",
"                               XooX@@@@@@@@O..O ",
"                               XooX@@@@@@@+O..O ",
"                               .ooX@@+@@@@+O..O ",
"                                XoX@@@@@@@+O.O  ",
"                                 ..+@@+@@@+OO   ",
"  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOOOO    ",
" XXX##@@@@@@@@@@@@@@@@@@@@@@@@@@##XXX+o+O.O     ",
" XX#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#XXO+o+OO     ",
" X#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#X@O+o+O     ",
" X#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#XOoO+.O     ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$%%$$$@XoOoO+O     ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$%%$$$@X+oOoOO     ",
" X@$$$$$$$$......$$$$$$$$$$$$$$$$$$@XO+oO.O     ",
" X@$$$$%$$&.*#**#&$$$$$$$$$$$$$$$$$@X@O+oOO     ",
" X@$$$%%$$.*##**#.$$$$$$$$$$$$$%$$$@XOoO+.O     ",
" X@$$%%%$$.##*###.$$$$$$$$$$$$$$$$$@XoOoO+O     ",
" X@$$%%%$$.*#*##*.$$$$$$$$$$$$$$$$$@X+oOoOO     ",
" X@$$$%%$$.#*#**#.$$$$$$$$$$$$$%$$$@XO+oO.O     ",
" X@$$$$%$$.#*#**#.$$$$$$$$$$$$$$$$$@X@O+oOO     ",
" X@$$$$$$$$......$$$$$$$$$$$$$$$$$$@XOoO+.O     ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$@Xo.X.X.X    ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$@X.ooooooOO  ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$@X@oOOOOoooO ",
" X@$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$@X+O+@@+.oooO",
" X#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#Xoo....oooOO",
" X#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#XooooooooX.O",
" XX#$$$$$$$$$$$$.X.....X..$$$$$$$$#XX.X.X.X.O..O",
" XXX##@@@@@@@@@.ooooooooooO@@@@@##XXX.@@@@@@O..O",
"  XXXXXXXXXXXX.ooo@XOOX@oooOXXXXXXXX@.@@@@@@O..O",
"             .ooo@O@@@@O@oooO      X+.@@@@@@O.Oo",
"             .oooO+@@@@+XoooO     .oX.@@@@@@OOoO",
"             .ooo@..@@..@oooO     X.oXOOOOOOOoOO",
"             .Xooo@@..@@oooOO     .@.oooooooo..O",
"             .oXooooooooooO.O     X+@X..X..XO..O",
"             XooX.XXXXX.XO..O     .@@.@@@@@@O..O",
"             XooX@@@@@@@@O..O     X@@.@@@@@@O..O",
"             XooX@@@@@@@@O..O      .+.@@@@@@O.O ",
"              XoX@@@@@@@@O.O        .X@@@@@@OO  ",
"               XX@@@@@@@@OO          .OOOOOOO   ",
"                .OOOOOOOOO                      "};
