/* XPM */
/*********************************************************************
*  Copyright (c) 1999 Sun Microsystems, Inc.
*  All Rights Reserved.
**********************************************************************/
static char * smcicon_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	c #FFFF00000000",
"o	s iconColor1	m black	c black",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray4	m white	c #949494949494",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray7	m black	c #424242424242",
"%	c #00000000FFFF",
"&	s iconGray2	m white	c #bdbdbdbdbdbd",
"*	s iconColor7	m white	c cyan",
"=	s iconGray8	m black	c #212121212121",
/* pixels */
"              .Xo               ",
"             .XOXo              ",
"            .XOXOXo             ",
"           .+++++++o            ",
"          .@@@@@@@@@+           ",
"      ...............#@@@@      ",
"      .OOOOOOOOOOOOOOOOOO@      ",
"      .O@@@@@@@@@@@@@@@@$@      ",
"      .O@$$$$$$$$$$$$$@@$#      ",
"     ..O@$%%%%%%%%%%%%#@$.+     ",
"    .&.O@$%.**+%+%+%++#@$.&o    ",
"   .+&.O@$%*%+%+%+%+%+#@$.&+o   ",
"  .+@&.O@$%*+%+%+%+%++#@$.&@+o  ",
" .X++&.O@$%+%+%+%+%+%+#@$.&++Xo ",
".XO+@&.O@$%%+%+%+%+%++#@$.&@+OXo",
"XOX++&.O@$%+%+%+%+%+%+#@$.&++XOX",
".XO+@&.O@$%+++++++++++#@$.&@+OXo",
" .X++&.O@@#############@$.&++Xo ",
"  .+@&.O@@@@@@@@@@@@@@@@$.&@+o  ",
"   .+&.@$$$$$$$$$$$$$$$$O.&+o   ",
"    .&.  ==============  .&o    ",
"     ..@OOOOOOOOOOOOOOOO@.+     ",
"      .O@@@@@@@@@@@@@@@@O#      ",
"      .O@@@@@@@@@@@@@@@@O@      ",
"      .$$$$$$$$$$$$$$$$$$@      ",
"      .=====........=====@      ",
"      ....############@@@@      ",
"          .@@@@@@@@@+           ",
"           .+++++++o            ",
"            .XOXOXo             ",
"             .XOXo              ",
"              .Xo               "};
