/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * TSdtedit_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray8	m black	c #212121212121",
"O	s iconColor1	m black	c black",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray2	m white	c #bdbdbdbdbdbd",
"&	s iconColor6	m white	c yellow",
"*	s iconGray4	m white	c #949494949494",
"=	s iconColor8	m black	c magenta",
/* pixels */
"   .....................        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XXOO+XOX+O+XXXXXXXXo        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XX+OX+XoXO+OX+OXXXXo        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XXXXXXXXXXXXXXXXXXXo        ",
"   .XXO+OXO@#O@$XXXXXXXo        ",
"   .XXXXXXXX#$..$%XXXXXo        ",
"   .XXXXXXXXX#.X&$%XXXXo        ",
"   .XXXXXXXXX#+$X&$%XXXo        ",
"   .XXXXXXXXXX#+$X&$%XXo        ",
"   .XXX#XXXXXX$#+$X&$%XO        ",
"   .XX#*#XXXXX$$#+$X&$%O        ",
" o#*++XXX++*#oX$$#+$X&$@        ",
" oXXXX$+$XXXXoXX$$#+$X&$        ",
"*o%o+@%X$++o%o$XX$$#+$X&$       ",
"*oXo+*$X%*+oXo$XXX$$#+$X&$      ",
"*o%o+*%X$*+o%o$XXXX$$#+$X&$     ",
"*oXo+*%X$*+oXo$XXXXX$$#+$X&$    ",
"*o%o+*$X%*+o%o$XXXXXX$$#+$X##O  ",
"*oXo+*%X$*+oXo$XXXXXXX$o##+XX*# ",
"*#%o+*$X$*+o%#$XXXXXXXXo*##*X=# ",
"**#Xo+*$*+oX#o$XXXXXXXXO**#*=## ",
" **#X#+@+#X##oooooooOOOO **###* ",
"  **#X+++X#**             ***** ",
"   **#X%X#**               ***  ",
"    **@#@**                     ",
"     *****                      ",
"      ***                       "};
