/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * TSdtedit_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconGray1	m white	c #dededededede",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray5	m black	c #737373737373",
"#	s iconGray7	m black	c #424242424242",
"$	s iconColor1	m black	c black",
"%	s iconColor6	m white	c yellow",
"&	s iconGray2	m white	c #bdbdbdbdbdbd",
"*	s iconGray4	m white	c #949494949494",
"=	s iconColor8	m black	c magenta",
/* pixels */
"                                                ",
"      ............................              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XXXOXOX+XXXXOXXX+OXXXXXXXXo              ",
"      .XXo+Xo++XooX+Oo++O+XXXXXXXo              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXo              ",
"      .XX+O+OXXXXoXoX@XXXXXXXXXXXo              ",
"      .XXoOO+OoXoO@Oo#$$$OOXXXXXXo              ",
"      .XXXXXXXXXXXXX+#$$$OOOXXXXXo              ",
"      .XXXXXXXXXXXXXX+O$X%%&OXXXXo              ",
"      .XXXXXXXXXXXXXX++OOX%%&OXXXo              ",
"      .XXXXXXXXXXXXXXX++OXX%%&OXXo              ",
"      .XXXXXXXXXXXXXXX##+OXX%%&OXo              ",
"      .XXXXXXXXXXXXXXXO##+OXX%%&Oo              ",
"      .XXXX*@XXXXXXXXXOO#++OXX%%&$              ",
"      .XX**XX*@XXXXXXX&OO##+OXX%%&              ",
"O@*   ***XXXXXX**@XXX@**OO##+OXX%%&             ",
"*X****XXXXO**OXXX&***&X*&OO##+OXX%%&            ",
"OXXXXXXXO@*OO*@OXXXXXXX@X&OO##+OXX%%&           ",
"*X&*@*@*@OOOOOO@*@*@*&XoXX&OO##+OXX%%&          ",
"OX&@O*O*OO&&&&OO*O*O@&X@XXX&OO#++OXX%%&         ",
"*X&**OOOO&&&&&&OOOO**&XoXXXX&OO##+OXX%%&        ",
"OX&@OOO&&X&&X&X&&OOO@&X@XXXXX&OO##+OXX***$      ",
"*X&**OO&&&XXXX&&&OO**&XoXXXXXX&OO#++O*XX##$     ",
"OX&@OOO&&XX&X&X&&OOO@&X@XXXXXXX&Oo#++OX#X##O    ",
"*X&**O&&&&XXXX&&&&O**&XoXXXXXXXX&o*###++#XX=#   ",
"OX&@OOO&X&XX&X&X&OOO@&X@XXXXXXXXXo***##+*X=*#   ",
"*X&**OO&&&XXXX&&&OO**&XoXXXXXXXXXo***###*==*#   ",
"OX&@OOO&&XX&X&X&&OOO@&X@XXXXXXXXXo ***##+**###  ",
"*X&**OO&&&XXXX&&&OO**&XoXXXXXXXXXo  ***+####+*  ",
"OX&@OOO&&&&X&X&&&OOO@&X@XXXXXXXXXo   ***####**  ",
"*X&**OO&&&&&X&X&&OO**&XoXXXXXXXXXo    ********  ",
"O&X*OOO&&X&X&&&&&OOO*X&@XXXXXXXXXo     ******   ",
" OX&**O&O&&&&&&O&O**&X@$oooooooooo              ",
" *&X&@OO&&&&&&&&OO@&X&@                         ",
"  *XX&**OO&&&&OO**&XX@                          ",
"   *XX&@OOOOOOOO@&XX#                           ",
"    *XX&**OOOO**&XX@                            ",
"     *XX&@O**O@&XX#                             ",
"      *XXX&**&XXX@                              ",
"       **XXXXXX*@                               ",
"         *@XX@+                                 ",
"           @#                                   ",
"                                                "};
