/* XPM */
/*********************************************************************
*  (c) Copyright 1997 Sun Microsystems, Inc.
**********************************************************************/
static char * TSpath_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray4	m white	c #949494949494",
"X	s iconGray5	m black	c #737373737373",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray2	m white	c #bdbdbdbdbdbd",
"@	s iconGray8	m black	c #212121212121",
"#	s iconGray7	m black	c #424242424242",
"$	s iconGray6	m black	c #636363636363",
/* pixels */
"                                ",
"               .X               ",
"             ..oo.X             ",
"    OX.   ...oooooo..X   X.X    ",
"    .o....ooooO..Oooo+...+o@    ",
"    OoooooooOX.OO.XOoooooooX    ",
"    .o+.X.X.XOOOOOOX.X.X.+o@    ",
"    Oo+XO.O.OO++++OO.O.OX+oX    ",
"    .o+..OOOO++oo++OOOO..+o@    ",
"    Oo+XOOOO+oo+o+o+OOOOX+oX    ",
"    .o+..OO+++oooo+++OO..+o@    ",
"    Oo+XOOO++o+oooo+OOOOX+oX    ",
"    .o+..OO+oooooo+o+OO..+o@    ",
"    Oo+XOOO+++oooo+++OOOX+oX    ",
"    .o+..OO++oooo+o+OOO..+o@    ",
"    Oo+XOOO++oooooo++OOOX+oX    ",
"    .o+..OO+++oo+o+++OO..+o@    ",
"    Oo+XOOO++o+oo++++OOOX+oX    ",
"    .o+..OO+++oooo+O+OO..+o@    ",
"    O+o.OOO+++o+o+++OOOO.o+X    ",
"     Oo+..O+O++o+++++O..+oX     ",
"     .+o+XOO++++++O+OOX+o+X     ",
"      .oo+..O++++++O..+ooX      ",
"       .oo+XOO+O++OOX+oo#       ",
"        .oo+..OOOO..+ooX        ",
"         .oo+XO..OX+oo#         ",
"          .ooo+..+oooX          ",
"           ..oooooo.$           ",
"             .XooX$             ",
"               X#               ",
"                                ",
"                                "};
