
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * BuilderXcessory PRO Version 6.2
 * Code Generator Xcessory 6.2 (08/06/08)  
 *
 */


/* Begin user code block <file_comments> */
/* End user code block <file_comments> */

#include <Xm/Xm.h>
#include <Xm/MainW.h>
#include <Xm/DialogS.h>
#include <Xm/MwmUtil.h>
#include <Xm/MessageB.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/Separator.h>
#include <Xm/ButtonBox.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/FileSB.h>
#include <Xm/CascadeB.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>

/**
 * Globally included information.
 */
#include "utilities.h"

/**
 * Common constant and pixmap declarations.
 */
#include "creation.h"

/**
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer BX_CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer BX_DOUBLE(double);
extern XtPointer BX_SINGLE(float);
extern void BX_MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char **);
extern void BX_SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal *, Pixel);

/**
 * Declarations for callbacks and handlers.
 */
extern void BxExitCB(Widget, XtPointer, XtPointer);
extern void BxUnmanageCB(Widget, XtPointer, XtPointer);
extern void findDlgCB(Widget, XtPointer, XtPointer);
extern void saveAsCB(Widget, XtPointer, XtPointer);
extern void fileOpenCB(Widget, XtPointer, XtPointer);
extern void includeFileCB(Widget, XtPointer, XtPointer);
extern void newDocCB(Widget, XtPointer, XtPointer);
extern void BxManageCB(Widget, XtPointer, XtPointer);
extern void saveCB(Widget, XtPointer, XtPointer);
extern void editCB(Widget, XtPointer, XtPointer);
extern void statusBarToggleCB(Widget, XtPointer, XtPointer);
extern void overstrikeToggleCB(Widget, XtPointer, XtPointer);
extern void backupSaveToggleCB(Widget, XtPointer, XtPointer);
extern void docWrapModifyCB(Widget, XtPointer, XtPointer);
extern void BxVerifyNumericCB(Widget, XtPointer, XtPointer);
extern void lineTextFieldActivateCB(Widget, XtPointer, XtPointer);

/**
 * Create the mainWindow hierarchy of widgets.
 */
Widget
CreatemainWindow(Widget parent)
{
    Cardinal ac = 0;
    Arg      args[256];
    Cardinal cdc; 
    Boolean  argok; 
    Widget   mainWindow;
    Widget   unsupportedDialogShell;
    Widget   unsupportedMessageBox;
    Widget   lineOutOfRangeDialogShell;
    Widget   lineOutOfRangeMessageBox;
    Widget   backupErrorDialogShell;
    Widget   backupErrorMessageBox;
    Widget   changeAllCompleteDialogShell;
    Widget   changeAllCompleteMessageBox;
    Widget   stringNotFoundDialogShell;
    Widget   stringNotFoundMessageBox;
    Widget   findDialogShell;
    Widget   findDialogForm;
    Widget   findDialogRowColumn;
    Widget   fdFindLabel;
    Widget   fdFindTextField;
    Widget   fdChangeLabel;
    Widget   fdChangeTextField;
    Widget   separator7;
    Widget   fdButtonBox1;
    Widget   fdFindPushButton;
    Widget   fdChangePushButton;
    Widget   fdChangeAllPushButton;
    Widget   separator8;
    Widget   fdButtonBox2;
    Widget   fdClosePushButton;
    Widget   fdHelpPushButton;
    Widget   fileSaveFailedDialogShell;
    Widget   fileSaveFailedMessageBox;
    Widget   dialogShell;
    Widget   fileSaveTruncatedMessageBox;
    Widget   fileNotFoundDialogShell;
    Widget   fileNotFoundMessageBox;
    Widget   printDialogShell;
    Widget   printDialog;
    Widget   printForm;
    Widget   bannerTextField;
    Widget   textField2;
    Widget   printerCmdOptsLabel;
    Widget   printPageNumbersToggleButton;
    Widget   separator6;
    Widget   bannerLabel;
    Widget   copiesTextField;
    Widget   copiesLabel;
    Widget   printerTextField;
    Widget   printerLabel;
    Widget   fileNameLabel;
    Widget   fileLabel;
    Widget   settingsDialogShell;
    Widget   settingsForm;
    Widget   buttonBox;
    Widget   paragraphPushButton;
    Widget   allPushButton;
    Widget   closePushButton;
    Widget   helpPushButton;
    Widget   settingsRadioBox;
    Widget   leftAlignToggleButton;
    Widget   rightAlignToggleButton;
    Widget   justifyToggleButton;
    Widget   centerToggleButton;
    Widget   rightMarginTextField;
    Widget   rightMarginLabel;
    Widget   leftMarginTextField;
    Widget   leftMarginLabel;
    Widget   settingsSeparator;
    Widget   saveAsDialogShell;
    Widget   saveAsFileSelectionBox;
    Widget   openDialogShell;
    Widget   openFileSelectionBox;
    Widget   includeDialogShell;
    Widget   includeFileSelectionBox;
    Widget   licenseDialogShell;
    Widget   licenseMessageBox;
    Widget   aboutDialogShell;
    Widget   aboutMessageBox;
    Widget   menuBar;
    Widget   fileMenu;
    Widget   filePdMenu;
    Widget   newButton;
    Widget   openButton;
    Widget   includeButton;
    Widget   separator1;
    Widget   saveButton;
    Widget   saveAsButton;
    Widget   printButton;
    Widget   separator2;
    Widget   closeButton;
    Widget   editMenu;
    Widget   editPdMenu;
    Widget   undoButton;
    Widget   separator4;
    Widget   copyButton;
    Widget   cutButton;
    Widget   pasteButton;
    Widget   separator5;
    Widget   deleteButton;
    Widget   clearButton;
    Widget   separator3;
    Widget   findChangeButton;
    Widget   checkSpellingButton;
    Widget   formatMenu;
    Widget   formatPdMenu;
    Widget   settingsButton;
    Widget   separator;
    Widget   allButton;
    Widget   paragraphButton;
    Widget   optionsMenu;
    Widget   optionsPdMenu;
    Widget   statusLineToggleButton;
    Widget   overstrikeToggleButton;
    Widget   wrapToFitToggleButton;
    Widget   backupOnSaveToggleButton;
    Widget   helpMenu;
    Widget   helpPdMenu;
    Widget   aboutButton;
    Widget   licenseButton;
    Widget   mainForm;
    Widget   textWindowWrapped;
    Widget   documentTextWrapped;
    Widget   textWindow;
    Widget   documentText;
    Widget   statusBar;
    Widget   overstrikeLabel;
    Widget   messageTextField;
    Widget   totalCountLabel;
    Widget   totalLabel;
    Widget   lineTextField;
    Widget   lineLabel;
    
    cdc = 0; argok = False; 
    
    /**
     * Register the converters for the widgets.
     */
    RegisterBxConverters(XtWidgetToApplicationContext(parent));
    XtInitializeWidgetClass((WidgetClass)xmMainWindowWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmDialogShellWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmMessageBoxWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmFormWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmLabelWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmTextFieldWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmSeparatorWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmButtonBoxWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmPushButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmFormWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmToggleButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmFileSelectionBoxWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmCascadeButtonWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmRowColumnWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmScrolledWindowWidgetClass);
    XtInitializeWidgetClass((WidgetClass)xmTextWidgetClass);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 558); ac++;
    XtSetArg(args[ac], XmNheight, 554); ac++;
    mainWindow = XmCreateMainWindow(parent,
        (char *)"mainWindow",
        args, 
        ac);
    XtAddCallback(mainWindow, XmNdestroyCallback, BxExitCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 558); ac++;
    XtSetArg(args[ac], XmNheight, 27); ac++;
    menuBar = XmCreateMenuBar(mainWindow,
        (char *)"menuBar",
        args, 
        ac);
    XtManageChild(menuBar);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 4); ac++;
    XtSetArg(args[ac], XmNy, 4); ac++;
    XtSetArg(args[ac], XmNwidth, 38); ac++;
    XtSetArg(args[ac], XmNheight, 19); ac++;
    fileMenu = XmCreateCascadeButton(menuBar,
        (char *)"fileMenu",
        args, 
        ac);
    XtManageChild(fileMenu);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 119); ac++;
    XtSetArg(args[ac], XmNheight, 139); ac++;
    filePdMenu = XmCreatePulldownMenu(XtParent(fileMenu),
        (char *)"filePdMenu",
        args, 
        ac);
    
    ac = 0;
    newButton = XmCreatePushButton(filePdMenu,
        (char *)"newButton",
        args, 
        ac);
    XtManageChild(newButton);
    XtAddCallback(newButton, XmNactivateCallback, newDocCB, (XtPointer)0);
    
    ac = 0;
    openButton = XmCreatePushButton(filePdMenu,
        (char *)"openButton",
        args, 
        ac);
    XtManageChild(openButton);
    XtAddCallback(openButton, XmNactivateCallback, BxManageCB, (XtPointer)"openFileSelectionBox");
    
    ac = 0;
    includeButton = XmCreatePushButton(filePdMenu,
        (char *)"includeButton",
        args, 
        ac);
    XtManageChild(includeButton);
    XtAddCallback(includeButton, XmNactivateCallback, BxManageCB, (XtPointer)"includeFileSelectionBox");
    
    ac = 0;
    separator1 = XmCreateSeparator(filePdMenu,
        (char *)"separator1",
        args, 
        ac);
    XtManageChild(separator1);
    
    ac = 0;
    saveButton = XmCreatePushButton(filePdMenu,
        (char *)"saveButton",
        args, 
        ac);
    XtManageChild(saveButton);
    XtAddCallback(saveButton, XmNactivateCallback, saveCB, (XtPointer)0);
    
    ac = 0;
    saveAsButton = XmCreatePushButton(filePdMenu,
        (char *)"saveAsButton",
        args, 
        ac);
    XtManageChild(saveAsButton);
    XtAddCallback(saveAsButton, XmNactivateCallback, BxManageCB, (XtPointer)"saveAsFileSelectionBox");
    
    ac = 0;
    printButton = XmCreatePushButton(filePdMenu,
        (char *)"printButton",
        args, 
        ac);
    XtManageChild(printButton);
    XtAddCallback(printButton, XmNactivateCallback, BxManageCB, (XtPointer)"printDialog");
    
    ac = 0;
    separator2 = XmCreateSeparator(filePdMenu,
        (char *)"separator2",
        args, 
        ac);
    XtManageChild(separator2);
    
    ac = 0;
    closeButton = XmCreatePushButton(filePdMenu,
        (char *)"closeButton",
        args, 
        ac);
    XtManageChild(closeButton);
    XtAddCallback(closeButton, XmNactivateCallback, BxExitCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, filePdMenu); ac++;
    XtSetValues(fileMenu, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 42); ac++;
    XtSetArg(args[ac], XmNy, 4); ac++;
    XtSetArg(args[ac], XmNwidth, 38); ac++;
    XtSetArg(args[ac], XmNheight, 19); ac++;
    editMenu = XmCreateCascadeButton(menuBar,
        (char *)"editMenu",
        args, 
        ac);
    XtManageChild(editMenu);
    
    ac = 0;
    editPdMenu = XmCreatePulldownMenu(XtParent(editMenu),
        (char *)"editPdMenu",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNmnemonic, 'o'); ac++;
    undoButton = XmCreatePushButton(editPdMenu,
        (char *)"undoButton",
        args, 
        ac);
    XtManageChild(undoButton);
    XtAddCallback(undoButton, XmNactivateCallback, BxManageCB, (XtPointer)"unsupportedMessageBox");
    
    ac = 0;
    separator4 = XmCreateSeparator(editPdMenu,
        (char *)"separator4",
        args, 
        ac);
    XtManageChild(separator4);
    
    ac = 0;
    copyButton = XmCreatePushButton(editPdMenu,
        (char *)"copyButton",
        args, 
        ac);
    XtManageChild(copyButton);
    XtAddCallback(copyButton, XmNactivateCallback, editCB, (XtPointer)EDIT_COPY);
    
    ac = 0;
    cutButton = XmCreatePushButton(editPdMenu,
        (char *)"cutButton",
        args, 
        ac);
    XtManageChild(cutButton);
    XtAddCallback(cutButton, XmNactivateCallback, editCB, (XtPointer)EDIT_CUT);
    
    ac = 0;
    pasteButton = XmCreatePushButton(editPdMenu,
        (char *)"pasteButton",
        args, 
        ac);
    XtManageChild(pasteButton);
    XtAddCallback(pasteButton, XmNactivateCallback, editCB, (XtPointer)EDIT_PASTE);
    
    ac = 0;
    separator5 = XmCreateSeparator(editPdMenu,
        (char *)"separator5",
        args, 
        ac);
    XtManageChild(separator5);
    
    ac = 0;
    deleteButton = XmCreatePushButton(editPdMenu,
        (char *)"deleteButton",
        args, 
        ac);
    XtManageChild(deleteButton);
    XtAddCallback(deleteButton, XmNactivateCallback, editCB, (XtPointer)EDIT_DELETE);
    
    ac = 0;
    clearButton = XmCreatePushButton(editPdMenu,
        (char *)"clearButton",
        args, 
        ac);
    XtManageChild(clearButton);
    XtAddCallback(clearButton, XmNactivateCallback, editCB, (XtPointer)EDIT_CLEAR);
    
    ac = 0;
    separator3 = XmCreateSeparator(editPdMenu,
        (char *)"separator3",
        args, 
        ac);
    XtManageChild(separator3);
    
    ac = 0;
    findChangeButton = XmCreatePushButton(editPdMenu,
        (char *)"findChangeButton",
        args, 
        ac);
    XtManageChild(findChangeButton);
    XtAddCallback(findChangeButton, XmNactivateCallback, BxManageCB, (XtPointer)"findDialogForm");
    
    ac = 0;
    checkSpellingButton = XmCreatePushButton(editPdMenu,
        (char *)"checkSpellingButton",
        args, 
        ac);
    XtManageChild(checkSpellingButton);
    XtAddCallback(checkSpellingButton, XmNactivateCallback, BxManageCB, (XtPointer)"unsupportedMessageBox");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, editPdMenu); ac++;
    XtSetValues(editMenu, args, ac);
    
    ac = 0;
    formatMenu = XmCreateCascadeButton(menuBar,
        (char *)"formatMenu",
        args, 
        ac);
    XtManageChild(formatMenu);
    
    ac = 0;
    formatPdMenu = XmCreatePulldownMenu(XtParent(formatMenu),
        (char *)"formatPdMenu",
        args, 
        ac);
    
    ac = 0;
    settingsButton = XmCreatePushButton(formatPdMenu,
        (char *)"settingsButton",
        args, 
        ac);
    XtManageChild(settingsButton);
    XtAddCallback(settingsButton, XmNactivateCallback, BxManageCB, (XtPointer)"settingsForm");
    
    ac = 0;
    separator = XmCreateSeparator(formatPdMenu,
        (char *)"separator",
        args, 
        ac);
    XtManageChild(separator);
    
    ac = 0;
    allButton = XmCreatePushButton(formatPdMenu,
        (char *)"allButton",
        args, 
        ac);
    XtManageChild(allButton);
    
    ac = 0;
    paragraphButton = XmCreatePushButton(formatPdMenu,
        (char *)"paragraphButton",
        args, 
        ac);
    XtManageChild(paragraphButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, formatPdMenu); ac++;
    XtSetValues(formatMenu, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 130); ac++;
    XtSetArg(args[ac], XmNy, 4); ac++;
    XtSetArg(args[ac], XmNwidth, 56); ac++;
    XtSetArg(args[ac], XmNheight, 19); ac++;
    optionsMenu = XmCreateCascadeButton(menuBar,
        (char *)"optionsMenu",
        args, 
        ac);
    XtManageChild(optionsMenu);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 107); ac++;
    XtSetArg(args[ac], XmNheight, 78); ac++;
    optionsPdMenu = XmCreatePulldownMenu(XtParent(optionsMenu),
        (char *)"optionsPdMenu",
        args, 
        ac);
    
    ac = 0;
    statusLineToggleButton = XmCreateToggleButton(optionsPdMenu,
        (char *)"statusLineToggleButton",
        args, 
        ac);
    XtManageChild(statusLineToggleButton);
    XtAddCallback(statusLineToggleButton, XmNvalueChangedCallback, statusBarToggleCB, (XtPointer)0);
    
    ac = 0;
    overstrikeToggleButton = XmCreateToggleButton(optionsPdMenu,
        (char *)"overstrikeToggleButton",
        args, 
        ac);
    XtManageChild(overstrikeToggleButton);
    XtAddCallback(overstrikeToggleButton, XmNvalueChangedCallback, overstrikeToggleCB, (XtPointer)0);
    
    ac = 0;
    wrapToFitToggleButton = XmCreateToggleButton(optionsPdMenu,
        (char *)"wrapToFitToggleButton",
        args, 
        ac);
    XtManageChild(wrapToFitToggleButton);
    XtAddCallback(wrapToFitToggleButton, XmNvalueChangedCallback, BxManageCB, (XtPointer)"unsupportedMessageBox");
    
    ac = 0;
    backupOnSaveToggleButton = XmCreateToggleButton(optionsPdMenu,
        (char *)"backupOnSaveToggleButton",
        args, 
        ac);
    XtManageChild(backupOnSaveToggleButton);
    XtAddCallback(backupOnSaveToggleButton, XmNvalueChangedCallback, backupSaveToggleCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, optionsPdMenu); ac++;
    XtSetValues(optionsMenu, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 516); ac++;
    XtSetArg(args[ac], XmNy, 4); ac++;
    XtSetArg(args[ac], XmNwidth, 38); ac++;
    XtSetArg(args[ac], XmNheight, 19); ac++;
    helpMenu = XmCreateCascadeButton(menuBar,
        (char *)"helpMenu",
        args, 
        ac);
    XtManageChild(helpMenu);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 56); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    helpPdMenu = XmCreatePulldownMenu(XtParent(helpMenu),
        (char *)"helpPdMenu",
        args, 
        ac);
    
    ac = 0;
    aboutButton = XmCreatePushButton(helpPdMenu,
        (char *)"aboutButton",
        args, 
        ac);
    XtManageChild(aboutButton);
    XtAddCallback(aboutButton, XmNactivateCallback, BxManageCB, (XtPointer)"aboutMessageBox");
    
    ac = 0;
    licenseButton = XmCreatePushButton(helpPdMenu,
        (char *)"licenseButton",
        args, 
        ac);
    XtManageChild(licenseButton);
    XtAddCallback(licenseButton, XmNactivateCallback, BxManageCB, (XtPointer)"licenseMessageBox");
    
    ac = 0;
    XtSetArg(args[ac], XmNsubMenuId, helpPdMenu); ac++;
    XtSetValues(helpMenu, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNwidth, 558); ac++;
    XtSetArg(args[ac], XmNheight, 527); ac++;
    mainForm = XmCreateForm(mainWindow,
        (char *)"mainForm",
        args, 
        ac);
    XtManageChild(mainForm);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAPPLICATION_DEFINED); ac++;
    textWindowWrapped = XmCreateScrolledWindow(mainForm,
        (char *)"textWindowWrapped",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNwordWrap, False); ac++;
    XtSetArg(args[ac], XmNscrollHorizontal, False); ac++;
    documentTextWrapped = XmCreateText(textWindowWrapped,
        (char *)"documentTextWrapped",
        args, 
        ac);
    XtManageChild(documentTextWrapped);
    XtAddCallback(documentTextWrapped, XmNmodifyVerifyCallback, docWrapModifyCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNscrollingPolicy, XmAPPLICATION_DEFINED); ac++;
    textWindow = XmCreateScrolledWindow(mainForm,
        (char *)"textWindow",
        args, 
        ac);
    XtManageChild(textWindow);
    
    ac = 0;
    XtSetArg(args[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
    XtSetArg(args[ac], XmNsource, XmTextGetSource(documentTextWrapped)); ac++;
    XtSetArg(args[ac], XmNwordWrap, False); ac++;
    XtSetArg(args[ac], XmNscrollHorizontal, True); ac++;
    documentText = XmCreateText(textWindow,
        (char *)"documentText",
        args, 
        ac);
    XtManageChild(documentText);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    statusBar = XmCreateForm(mainWindow,
        (char *)"statusBar",
        args, 
        ac);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(statusBar, (char *)"Insert", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNx, 344); ac++;
        XtSetArg(args[ac], XmNy, 13); ac++;
        overstrikeLabel = XmCreateLabel(statusBar,
            (char *)"overstrikeLabel",
            args, 
            ac);
        XtManageChild(overstrikeLabel);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNcursorPositionVisible, False); ac++;
    XtSetArg(args[ac], XmNeditable, False); ac++;
    XtSetArg(args[ac], XmNx, 210); ac++;
    XtSetArg(args[ac], XmNy, 8); ac++;
    messageTextField = XmCreateTextField(statusBar,
        (char *)"messageTextField",
        args, 
        ac);
    XtManageChild(messageTextField);
    
    ac = 0;
    {
        XmString    tmp0;
        
        tmp0 = (XmString) BX_CONVERT(statusBar, (char *)"1", 
                XmRXmString, 0, &argok);
        XtSetArg(args[ac], XmNlabelString, tmp0); if (argok) ac++;
        XtSetArg(args[ac], XmNalignment, XmALIGNMENT_CENTER); ac++;
        XtSetArg(args[ac], XmNx, 195); ac++;
        XtSetArg(args[ac], XmNy, 13); ac++;
        totalCountLabel = XmCreateLabel(statusBar,
            (char *)"totalCountLabel",
            args, 
            ac);
        XtManageChild(totalCountLabel);
        
        /**
         * Free any memory allocated for resources.
         */
        XmStringFree((XmString)tmp0);
    }
    
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 135); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 60); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    totalLabel = XmCreateLabel(statusBar,
        (char *)"totalLabel",
        args, 
        ac);
    XtManageChild(totalLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 60); ac++;
    XtSetArg(args[ac], XmNy, 5); ac++;
    XtSetArg(args[ac], XmNwidth, 75); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    lineTextField = XmCreateTextField(statusBar,
        (char *)"lineTextField",
        args, 
        ac);
    XtManageChild(lineTextField);
    XtAddCallback(lineTextField, XmNmodifyVerifyCallback, BxVerifyNumericCB, (XtPointer)0);
    XtAddCallback(lineTextField, XmNactivateCallback, lineTextFieldActivateCB, (XtPointer)0);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 60); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    lineLabel = XmCreateLabel(statusBar,
        (char *)"lineLabel",
        args, 
        ac);
    XtManageChild(lineLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 428); ac++;
    XtSetArg(args[ac], XmNheight, 182); ac++;
    aboutDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"aboutDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    aboutMessageBox = XtCreateWidget((char *)"aboutMessageBox",
        xmMessageBoxWidgetClass,
        aboutDialogShell,
        args, 
        ac);
    XtAddCallback(aboutMessageBox, XmNokCallback, BxUnmanageCB, (XtPointer)"aboutMessageBox");
    XtUnmanageChild(XtNameToWidget(aboutMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(aboutMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 606); ac++;
    XtSetArg(args[ac], XmNheight, 310); ac++;
    licenseDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"licenseDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    licenseMessageBox = XtCreateWidget((char *)"licenseMessageBox",
        xmMessageBoxWidgetClass,
        licenseDialogShell,
        args, 
        ac);
    XtAddCallback(licenseMessageBox, XmNokCallback, BxUnmanageCB, (XtPointer)"licenseMessageBox");
    XtUnmanageChild(XtNameToWidget(licenseMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(licenseMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 226); ac++;
    XtSetArg(args[ac], XmNheight, 338); ac++;
    includeDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"includeDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 226); ac++;
    XtSetArg(args[ac], XmNheight, 352); ac++;
    includeFileSelectionBox = XtCreateWidget((char *)"includeFileSelectionBox",
        xmFileSelectionBoxWidgetClass,
        includeDialogShell,
        args, 
        ac);
    XtAddCallback(includeFileSelectionBox, XmNokCallback, includeFileCB, (XtPointer)0);
    XtAddCallback(includeFileSelectionBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"includeFileSelectionBox");
    XtUnmanageChild(XtNameToWidget(includeFileSelectionBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 300); ac++;
    XtSetArg(args[ac], XmNheight, 352); ac++;
    openDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"openDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 226); ac++;
    XtSetArg(args[ac], XmNheight, 352); ac++;
    openFileSelectionBox = XtCreateWidget((char *)"openFileSelectionBox",
        xmFileSelectionBoxWidgetClass,
        openDialogShell,
        args, 
        ac);
    XtAddCallback(openFileSelectionBox, XmNokCallback, fileOpenCB, (XtPointer)0);
    XtAddCallback(openFileSelectionBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"openFileSelectionBox");
    XtUnmanageChild(XtNameToWidget(openFileSelectionBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 226); ac++;
    XtSetArg(args[ac], XmNheight, 338); ac++;
    saveAsDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"saveAsDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 226); ac++;
    XtSetArg(args[ac], XmNheight, 352); ac++;
    saveAsFileSelectionBox = XtCreateWidget((char *)"saveAsFileSelectionBox",
        xmFileSelectionBoxWidgetClass,
        saveAsDialogShell,
        args, 
        ac);
    XtAddCallback(saveAsFileSelectionBox, XmNokCallback, saveAsCB, (XtPointer)0);
    XtAddCallback(saveAsFileSelectionBox, XmNcancelCallback, BxUnmanageCB, (XtPointer)"saveAsFileSelectionBox");
    
    ac = 0;
    XtSetArg(args[ac], XmNitemCount, 3); ac++;
    XtSetValues(XtNameToWidget(saveAsFileSelectionBox, "*ItemsList"), args, ac);
    XtUnmanageChild(XtNameToWidget(saveAsFileSelectionBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNallowShellResize, False); ac++;
    XtSetArg(args[ac], XmNwidth, 470); ac++;
    XtSetArg(args[ac], XmNheight, 225); ac++;
    settingsDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"settingsDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNnoResize, True); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    settingsForm = XtCreateWidget((char *)"settingsForm",
        xmFormWidgetClass,
        settingsDialogShell,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNequalSize, True); ac++;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 176); ac++;
    XtSetArg(args[ac], XmNwidth, 460); ac++;
    XtSetArg(args[ac], XmNheight, 40); ac++;
    buttonBox = XmCreateButtonBox(settingsForm,
        (char *)"buttonBox",
        args, 
        ac);
    XtManageChild(buttonBox);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 42); ac++;
    XtSetArg(args[ac], XmNy, 9); ac++;
    XtSetArg(args[ac], XmNwidth, 62); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    paragraphPushButton = XmCreatePushButton(buttonBox,
        (char *)"paragraphPushButton",
        args, 
        ac);
    XtManageChild(paragraphPushButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 146); ac++;
    XtSetArg(args[ac], XmNy, 9); ac++;
    XtSetArg(args[ac], XmNwidth, 62); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    allPushButton = XmCreatePushButton(buttonBox,
        (char *)"allPushButton",
        args, 
        ac);
    XtManageChild(allPushButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 251); ac++;
    XtSetArg(args[ac], XmNy, 9); ac++;
    XtSetArg(args[ac], XmNwidth, 62); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    closePushButton = XmCreatePushButton(buttonBox,
        (char *)"closePushButton",
        args, 
        ac);
    XtManageChild(closePushButton);
    XtAddCallback(closePushButton, XmNactivateCallback, BxUnmanageCB, (XtPointer)"settingsForm");
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 355); ac++;
    XtSetArg(args[ac], XmNy, 9); ac++;
    XtSetArg(args[ac], XmNwidth, 62); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    helpPushButton = XmCreatePushButton(buttonBox,
        (char *)"helpPushButton",
        args, 
        ac);
    XtManageChild(helpPushButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 50); ac++;
    XtSetArg(args[ac], XmNwidth, 93); ac++;
    XtSetArg(args[ac], XmNheight, 99); ac++;
    XtSetArg(args[ac], XmNisHomogeneous, False); ac++;
    settingsRadioBox = XmCreateRadioBox(settingsForm,
        (char *)"settingsRadioBox",
        args, 
        ac);
    XtManageChild(settingsRadioBox);
    
    ac = 0;
    XtSetArg(args[ac], XmNset, TRUE); ac++;
    XtSetArg(args[ac], XmNwidth, 87); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    leftAlignToggleButton = XmCreateToggleButton(settingsRadioBox,
        (char *)"leftAlignToggleButton",
        args, 
        ac);
    XtManageChild(leftAlignToggleButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 87); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    rightAlignToggleButton = XmCreateToggleButton(settingsRadioBox,
        (char *)"rightAlignToggleButton",
        args, 
        ac);
    XtManageChild(rightAlignToggleButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 87); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    justifyToggleButton = XmCreateToggleButton(settingsRadioBox,
        (char *)"justifyToggleButton",
        args, 
        ac);
    XtManageChild(justifyToggleButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 87); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    centerToggleButton = XmCreateToggleButton(settingsRadioBox,
        (char *)"centerToggleButton",
        args, 
        ac);
    XtManageChild(centerToggleButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 360); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    rightMarginTextField = XmCreateTextField(settingsForm,
        (char *)"rightMarginTextField",
        args, 
        ac);
    XtManageChild(rightMarginTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 260); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    rightMarginLabel = XmCreateLabel(settingsForm,
        (char *)"rightMarginLabel",
        args, 
        ac);
    XtManageChild(rightMarginLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 110); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    leftMarginTextField = XmCreateTextField(settingsForm,
        (char *)"leftMarginTextField",
        args, 
        ac);
    XtManageChild(leftMarginTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    leftMarginLabel = XmCreateLabel(settingsForm,
        (char *)"leftMarginLabel",
        args, 
        ac);
    XtManageChild(leftMarginLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 159); ac++;
    XtSetArg(args[ac], XmNwidth, 460); ac++;
    XtSetArg(args[ac], XmNheight, 12); ac++;
    settingsSeparator = XmCreateSeparator(settingsForm,
        (char *)"settingsSeparator",
        args, 
        ac);
    XtManageChild(settingsSeparator);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 514); ac++;
    XtSetArg(args[ac], XmNheight, 280); ac++;
    printDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"printDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_TEMPLATE); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 514); ac++;
    XtSetArg(args[ac], XmNheight, 280); ac++;
    printDialog = XtCreateWidget((char *)"printDialog",
        xmMessageBoxWidgetClass,
        printDialogShell,
        args, 
        ac);
    XtAddCallback(printDialog, XmNcancelCallback, BxUnmanageCB, (XtPointer)"printDialog");
    
    ac = 0;
    XtSetArg(args[ac], XmNnoResize, True); ac++;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 11); ac++;
    XtSetArg(args[ac], XmNy, 11); ac++;
    XtSetArg(args[ac], XmNheight, 201); ac++;
    printForm = XmCreateForm(printDialog,
        (char *)"printForm",
        args, 
        ac);
    XtManageChild(printForm);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 121); ac++;
    XtSetArg(args[ac], XmNy, 75); ac++;
    XtSetArg(args[ac], XmNwidth, 361); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    bannerTextField = XmCreateTextField(printForm,
        (char *)"bannerTextField",
        args, 
        ac);
    XtManageChild(bannerTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 163); ac++;
    XtSetArg(args[ac], XmNy, 151); ac++;
    XtSetArg(args[ac], XmNwidth, 319); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    textField2 = XmCreateTextField(printForm,
        (char *)"textField2",
        args, 
        ac);
    XtManageChild(textField2);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 156); ac++;
    printerCmdOptsLabel = XmCreateLabel(printForm,
        (char *)"printerCmdOptsLabel",
        args, 
        ac);
    XtManageChild(printerCmdOptsLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 125); ac++;
    printPageNumbersToggleButton = XmCreateToggleButton(printForm,
        (char *)"printPageNumbersToggleButton",
        args, 
        ac);
    XtManageChild(printPageNumbersToggleButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 5); ac++;
    XtSetArg(args[ac], XmNy, 110); ac++;
    XtSetArg(args[ac], XmNwidth, 482); ac++;
    XtSetArg(args[ac], XmNheight, 10); ac++;
    separator6 = XmCreateSeparator(printForm,
        (char *)"separator6",
        args, 
        ac);
    XtManageChild(separator6);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 74); ac++;
    bannerLabel = XmCreateLabel(printForm,
        (char *)"bannerLabel",
        args, 
        ac);
    XtManageChild(bannerLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 382); ac++;
    XtSetArg(args[ac], XmNy, 40); ac++;
    XtSetArg(args[ac], XmNwidth, 100); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    copiesTextField = XmCreateTextField(printForm,
        (char *)"copiesTextField",
        args, 
        ac);
    XtManageChild(copiesTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 331); ac++;
    XtSetArg(args[ac], XmNy, 45); ac++;
    copiesLabel = XmCreateLabel(printForm,
        (char *)"copiesLabel",
        args, 
        ac);
    XtManageChild(copiesLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 67); ac++;
    XtSetArg(args[ac], XmNy, 40); ac++;
    XtSetArg(args[ac], XmNwidth, 244); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    printerTextField = XmCreateTextField(printForm,
        (char *)"printerTextField",
        args, 
        ac);
    XtManageChild(printerTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 42); ac++;
    printerLabel = XmCreateLabel(printForm,
        (char *)"printerLabel",
        args, 
        ac);
    XtManageChild(printerLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
    XtSetArg(args[ac], XmNx, 49); ac++;
    XtSetArg(args[ac], XmNy, 10); ac++;
    XtSetArg(args[ac], XmNwidth, 433); ac++;
    XtSetArg(args[ac], XmNheight, 30); ac++;
    fileNameLabel = XmCreateLabel(printForm,
        (char *)"fileNameLabel",
        args, 
        ac);
    XtManageChild(fileNameLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 10); ac++;
    XtSetArg(args[ac], XmNy, 15); ac++;
    fileLabel = XmCreateLabel(printForm,
        (char *)"fileLabel",
        args, 
        ac);
    XtManageChild(fileLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 348); ac++;
    XtSetArg(args[ac], XmNheight, 118); ac++;
    fileNotFoundDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"fileNotFoundDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    fileNotFoundMessageBox = XtCreateWidget((char *)"fileNotFoundMessageBox",
        xmMessageBoxWidgetClass,
        fileNotFoundDialogShell,
        args, 
        ac);
    XtAddCallback(fileNotFoundMessageBox, XmNokCallback, BxUnmanageCB, (XtPointer)"fileNotFoundMessageBox");
    XtUnmanageChild(XtNameToWidget(fileNotFoundMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(fileNotFoundMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 567); ac++;
    XtSetArg(args[ac], XmNheight, 106); ac++;
    dialogShell = XmCreateDialogShell(mainWindow,
        (char *)"dialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    fileSaveTruncatedMessageBox = XtCreateWidget((char *)"fileSaveTruncatedMessageBox",
        xmMessageBoxWidgetClass,
        dialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(fileSaveTruncatedMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(fileSaveTruncatedMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 293); ac++;
    XtSetArg(args[ac], XmNheight, 106); ac++;
    fileSaveFailedDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"fileSaveFailedDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    fileSaveFailedMessageBox = XtCreateWidget((char *)"fileSaveFailedMessageBox",
        xmMessageBoxWidgetClass,
        fileSaveFailedDialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(fileSaveFailedMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(fileSaveFailedMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 461); ac++;
    XtSetArg(args[ac], XmNheight, 217); ac++;
    findDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"findDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNresizePolicy, XmRESIZE_GROW); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    findDialogForm = XtCreateWidget((char *)"findDialogForm",
        xmFormWidgetClass,
        findDialogShell,
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    findDialogRowColumn = XmCreateRowColumn(findDialogForm,
        (char *)"findDialogRowColumn",
        args, 
        ac);
    XtManageChild(findDialogRowColumn);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 17); ac++;
    fdFindLabel = XmCreateLabel(findDialogRowColumn,
        (char *)"fdFindLabel",
        args, 
        ac);
    XtManageChild(fdFindLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 27); ac++;
    fdFindTextField = XmCreateTextField(findDialogRowColumn,
        (char *)"fdFindTextField",
        args, 
        ac);
    XtManageChild(fdFindTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 17); ac++;
    fdChangeLabel = XmCreateLabel(findDialogRowColumn,
        (char *)"fdChangeLabel",
        args, 
        ac);
    XtManageChild(fdChangeLabel);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 27); ac++;
    fdChangeTextField = XmCreateTextField(findDialogRowColumn,
        (char *)"fdChangeTextField",
        args, 
        ac);
    XtManageChild(fdChangeTextField);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 20); ac++;
    separator7 = XmCreateSeparator(findDialogRowColumn,
        (char *)"separator7",
        args, 
        ac);
    XtManageChild(separator7);
    
    ac = 0;
    XtSetArg(args[ac], XmNequalSize, True); ac++;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdButtonBox1 = XmCreateButtonBox(findDialogRowColumn,
        (char *)"fdButtonBox1",
        args, 
        ac);
    XtManageChild(fdButtonBox1);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 68); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdFindPushButton = XmCreatePushButton(fdButtonBox1,
        (char *)"fdFindPushButton",
        args, 
        ac);
    XtManageChild(fdFindPushButton);
    XtAddCallback(fdFindPushButton, XmNactivateCallback, findDlgCB, (XtPointer)FNDLG_FIND);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 68); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 68); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdChangePushButton = XmCreatePushButton(fdButtonBox1,
        (char *)"fdChangePushButton",
        args, 
        ac);
    XtManageChild(fdChangePushButton);
    XtAddCallback(fdChangePushButton, XmNactivateCallback, findDlgCB, (XtPointer)FNDLG_CHANGE);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 136); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 68); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdChangeAllPushButton = XmCreatePushButton(fdButtonBox1,
        (char *)"fdChangeAllPushButton",
        args, 
        ac);
    XtManageChild(fdChangeAllPushButton);
    XtAddCallback(fdChangeAllPushButton, XmNactivateCallback, findDlgCB, (XtPointer)FNDLG_CHANGEALL);
    
    ac = 0;
    XtSetArg(args[ac], XmNseparatorType, XmNO_LINE); ac++;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 5); ac++;
    separator8 = XmCreateSeparator(findDialogRowColumn,
        (char *)"separator8",
        args, 
        ac);
    XtManageChild(separator8);
    
    ac = 0;
    XtSetArg(args[ac], XmNequalSize, True); ac++;
    XtSetArg(args[ac], XmNwidth, 204); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdButtonBox2 = XmCreateButtonBox(findDialogRowColumn,
        (char *)"fdButtonBox2",
        args, 
        ac);
    XtManageChild(fdButtonBox2);
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 42); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 38); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdClosePushButton = XmCreatePushButton(fdButtonBox2,
        (char *)"fdClosePushButton",
        args, 
        ac);
    XtManageChild(fdClosePushButton);
    XtAddCallback(fdClosePushButton, XmNactivateCallback, BxUnmanageCB, (XtPointer)"findDialogForm");
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 123); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    XtSetArg(args[ac], XmNwidth, 38); ac++;
    XtSetArg(args[ac], XmNheight, 21); ac++;
    fdHelpPushButton = XmCreatePushButton(fdButtonBox2,
        (char *)"fdHelpPushButton",
        args, 
        ac);
    XtManageChild(fdHelpPushButton);
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 217); ac++;
    XtSetArg(args[ac], XmNheight, 110); ac++;
    stringNotFoundDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"stringNotFoundDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_INFORMATION); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    stringNotFoundMessageBox = XtCreateWidget((char *)"stringNotFoundMessageBox",
        xmMessageBoxWidgetClass,
        stringNotFoundDialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(stringNotFoundMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(stringNotFoundMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 410); ac++;
    XtSetArg(args[ac], XmNheight, 110); ac++;
    changeAllCompleteDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"changeAllCompleteDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_INFORMATION); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    changeAllCompleteMessageBox = XtCreateWidget((char *)"changeAllCompleteMessageBox",
        xmMessageBoxWidgetClass,
        changeAllCompleteDialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(changeAllCompleteMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(changeAllCompleteMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 200); ac++;
    XtSetArg(args[ac], XmNheight, 200); ac++;
    backupErrorDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"backupErrorDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    backupErrorMessageBox = XtCreateWidget((char *)"backupErrorMessageBox",
        xmMessageBoxWidgetClass,
        backupErrorDialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(backupErrorMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(backupErrorMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 664); ac++;
    XtSetArg(args[ac], XmNheight, 106); ac++;
    lineOutOfRangeDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"lineOutOfRangeDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_ERROR); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    lineOutOfRangeMessageBox = XtCreateWidget((char *)"lineOutOfRangeMessageBox",
        xmMessageBoxWidgetClass,
        lineOutOfRangeDialogShell,
        args, 
        ac);
    XtUnmanageChild(XtNameToWidget(lineOutOfRangeMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(lineOutOfRangeMessageBox, "*Help"));
    
    ac = 0;
    XtSetArg(args[ac], XmNwidth, 505); ac++;
    XtSetArg(args[ac], XmNheight, 122); ac++;
    unsupportedDialogShell = XmCreateDialogShell(mainWindow,
        (char *)"unsupportedDialogShell",
        args, 
        ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNdialogStyle, XmDIALOG_APPLICATION_MODAL); ac++;
    XtSetArg(args[ac], XmNdialogType, XmDIALOG_WARNING); ac++;
    XtSetArg(args[ac], XmNx, 0); ac++;
    XtSetArg(args[ac], XmNy, 0); ac++;
    unsupportedMessageBox = XtCreateWidget((char *)"unsupportedMessageBox",
        xmMessageBoxWidgetClass,
        unsupportedDialogShell,
        args, 
        ac);
    XtAddCallback(unsupportedMessageBox, XmNokCallback, BxUnmanageCB, (XtPointer)"unsupportedMessageBox");
    XtUnmanageChild(XtNameToWidget(unsupportedMessageBox, "*Cancel"));
    XtUnmanageChild(XtNameToWidget(unsupportedMessageBox, "*Help"));
    ac = 0;
    XtSetArg(args[ac], XmNmenuBar, menuBar); ac++;
    XtSetArg(args[ac], XmNworkWindow, mainForm); ac++;
    XtSetArg(args[ac], XmNmessageWindow, statusBar); ac++;
    XtSetValues(mainWindow, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopOffset, 0); ac++;
    XtSetValues(findDialogRowColumn, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNleftWidget, bannerLabel); ac++;
    XtSetArg(args[ac], XmNtopWidget, printerTextField); ac++;
    XtSetValues(bannerTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNleftWidget, printerCmdOptsLabel); ac++;
    XtSetArg(args[ac], XmNtopWidget, printPageNumbersToggleButton); ac++;
    XtSetValues(textField2, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopWidget, printPageNumbersToggleButton); ac++;
    XtSetValues(printerCmdOptsLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopWidget, separator6); ac++;
    XtSetValues(printPageNumbersToggleButton, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopWidget, bannerTextField); ac++;
    XtSetValues(separator6, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 15); ac++;
    XtSetArg(args[ac], XmNtopWidget, printerLabel); ac++;
    XtSetValues(bannerLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopWidget, fileNameLabel); ac++;
    XtSetValues(copiesTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightWidget, copiesTextField); ac++;
    XtSetArg(args[ac], XmNtopWidget, fileNameLabel); ac++;
    XtSetValues(copiesLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 20); ac++;
    XtSetArg(args[ac], XmNtopOffset, 40); ac++;
    XtSetArg(args[ac], XmNleftWidget, printerLabel); ac++;
    XtSetArg(args[ac], XmNrightWidget, copiesLabel); ac++;
    XtSetValues(printerTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopWidget, fileLabel); ac++;
    XtSetValues(printerLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNleftWidget, fileLabel); ac++;
    XtSetValues(fileNameLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 15); ac++;
    XtSetValues(fileLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 5); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopWidget, settingsSeparator); ac++;
    XtSetValues(buttonBox, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 50); ac++;
    XtSetValues(settingsRadioBox, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetValues(rightMarginTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNrightWidget, rightMarginTextField); ac++;
    XtSetValues(rightMarginLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNleftWidget, leftMarginLabel); ac++;
    XtSetValues(leftMarginTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetValues(leftMarginLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 5); ac++;
    XtSetArg(args[ac], XmNtopOffset, 10); ac++;
    XtSetArg(args[ac], XmNtopWidget, settingsRadioBox); ac++;
    XtSetValues(settingsSeparator, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNmenuHelpWidget, helpMenu); ac++;
    XtSetValues(menuBar, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopOffset, 0); ac++;
    XtSetValues(textWindowWrapped, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNtopOffset, 0); ac++;
    XtSetValues(textWindow, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 10); ac++;
    XtSetArg(args[ac], XmNrightOffset, 5); ac++;
    XtSetValues(overstrikeLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 5); ac++;
    XtSetArg(args[ac], XmNleftOffset, 5); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftWidget, totalCountLabel); ac++;
    XtSetArg(args[ac], XmNrightWidget, overstrikeLabel); ac++;
    XtSetValues(messageTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 10); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftWidget, totalLabel); ac++;
    XtSetValues(totalCountLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftWidget, lineTextField); ac++;
    XtSetValues(totalLabel, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 5); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetArg(args[ac], XmNrightOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftWidget, lineLabel); ac++;
    XtSetValues(lineTextField, args, ac);
    
    ac = 0;
    XtSetArg(args[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
    XtSetArg(args[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
    XtSetArg(args[ac], XmNbottomOffset, 0); ac++;
    XtSetArg(args[ac], XmNleftOffset, 0); ac++;
    XtSetValues(lineLabel, args, ac);
    
    
    
    /* Begin user code block <end_CreatemainWindow> */
    /* End user code block <end_CreatemainWindow> */
    return( mainWindow );
}
