
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 *
 * Created by BuilderXcessory PRO Version 6.2
 * Generated by Code Generator Xcessory 6.2 (08/06/08)  
 *
 */
#ifndef creation_H
#define creation_H

Widget CreatemainWindow(Widget parent);

#define FNDLG_CHANGE 1
#define FNDLG_FIND 0
#define EDIT_COPY 0
#define FNDLG_CHANGEALL 2
#define EDIT_CLEAR 5
#define EDIT_CUT 1
#define EDIT_DELETE 4
#define EDIT_PASTE 3
#endif
