
/* Begin user code block <abstract> */
/* End user code block <abstract> */

/**
 * README: Portions of this file are merged at file generation
 * time. Edits can be made *only* in between specified code blocks, look
 * for keywords <Begin user code> and <End user code>.
 */
/*
 * Generated by the ICS Builder Xcessory (BX).
 *
 * BuilderXcessory PRO Version 6.2
 * Code Generator Xcessory 6.2 (08/06/08)  
 *
 */


/* Begin user code block <file_comments> */
/* End user code block <file_comments> */

/*
 * Motif required Headers
 */
#include <X11/StringDefs.h>
#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/RepType.h>
#include <Xm/MwmUtil.h>

/**
 * Globally included information.
 */
#include "utilities.h"

/*
 * Headers for classes used in this program
 */

/**
 * Common constant and pixmap declarations.
 */
#include "creation.h"

/**
 * Convenience functions from utilities file.
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer BX_CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer BX_DOUBLE(double);
extern XtPointer BX_SINGLE(float);
extern void BX_MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char **);
extern void BX_SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal *, Pixel);

/* Begin user code block <globals> */
/* End user code block <globals> */

/**
 * Change this line via the Output Application Names Dialog.
 */
#define BX_APP_CLASS "Dtpad"

int main( int argc, char **argv)
{
    Widget       parent;
    XtAppContext app;
    Arg          args[256];
    Cardinal     ac;
    Widget   dtpad;
    Widget   mainWindow;
    
    /* Begin user code block <declarations> */
    /* End user code block <declarations> */
    
    ac = 0;
    
    /**
     * Initialize I-18-N features and locale support.
     */
    (void)XtSetLanguageProc(NULL, (XtLanguageProc)NULL, NULL);
    
    /*
     * Initialize Xt. 
     */
    
    XtSetLanguageProc(NULL, (XtLanguageProc) NULL, NULL); 
    
    /*
     * The applicationShell is created as an unrealized
     * parent for multiple topLevelShells.  The topLevelShells
     * are created as popup children of the applicationShell.
     * This is a recommendation of Paul Asente & Ralph Swick in
     * _X_Window_System_Toolkit_ p. 677.
     */
    
    parent = XtVaOpenApplication ( &app, 
                                   BX_APP_CLASS, 
                                   NULL, 
                                   0, 
                                   &argc, 
                                   argv, 
                                   NULL, 
                                   sessionShellWidgetClass, 
                                   NULL );
    
    RegisterBxConverters(app);
    XmRepTypeInstallTearOffModelConverter();
    
    /* Begin user code block <create_shells> */
    /* End user code block <create_shells> */
    
    /*
     * Create classes and widgets used in this program. 
     */
    
    /* Begin user code block <create_dtpad> */
    /* End user code block <create_dtpad> */
    
    ac = 0;
    XtSetArg(args[ac], XmNx, 493); ac++;
    XtSetArg(args[ac], XmNy, 130); ac++;
    XtSetArg(args[ac], XmNwidth, 558); ac++;
    XtSetArg(args[ac], XmNheight, 554); ac++;
    dtpad = XtCreatePopupShell((char *)"dtpad",
        topLevelShellWidgetClass,
        parent,
        args, 
        ac);
    mainWindow = (Widget)CreatemainWindow(dtpad);
    XtManageChild(mainWindow);
    XtPopup(XtParent(mainWindow), XtGrabNone);
    
    /* Begin user code block <app_procedures> */
    	char *title;

	XtVaGetValues(dtpad, XmNtitle, &title, NULL);
    	set_app_name(title);
	
	if (1 < argc)
		load_file(mainWindow, "main", argv[1]);
	else 
		update_window_title(mainWindow, "main");
		
    /* End user code block <app_procedures> */
    
    /* Begin user code block <main_loop> */
    /* End user code block <main_loop> */
    
    XtAppMainLoop(app);
    
    /*
     * A return value regardless of whether or not the main loop ends. 
     */
     return(0); 
}
