void manage_widget(Widget, char *, char *);
Widget get_widget_by_name(Widget, char *, char *);
long str_linecount(char *);
char *long_to_string(long n);
void update_message(Widget, char *, char *);
char *get_file_contents(Widget, char *, char *);
void update_document_linecount(Widget, char *);
void set_save_path(char *);
char *get_save_path();
int save_file(Widget, char *);
Boolean document_find(Widget, char *, XEvent *, char *);
void document_change(Widget, char *, XEvent *);
void document_changeall(Widget, char *, XEvent *);
void set_backup_on_save(Boolean);
void set_been_saved(Boolean);
void set_file_dirty(Boolean);
Widget get_document_text(Widget, char *);
XmTextPosition line_to_position(char *, short, short, short);
Boolean isWrap(Widget, char *);
void load_file(Widget, char *, char *);
void update_window_title(Widget, char *);
void set_app_name(char *);
char *get_app_name();
void batch_wrap(Widget, char *, char *, int *, XmTextPosition);
void edit_clear(Widget);
void toggle_overstrike_gui(Widget, XEvent *, String *, Cardinal);
