all:
	@${MAKE} -C libmotifmm
	@${MAKE} -C libopencde
	@${MAKE} -C dtpad
	@${MAKE} -C dtlock
	@${MAKE} -C dtlogin
	@${MAKE} -C dtsplash
	@${MAKE} -C dtpanel
	@${MAKE} -C dtrun
	@${MAKE} -C dtfile

clean:
	@${MAKE} -C libmotifmm clean
	@${MAKE} -C libopencde clean
	@${MAKE} -C dtpad clean
	@${MAKE} -C dtlock clean
	@${MAKE} -C dtlogin clean
	@${MAKE} -C dtsplash clean
	@${MAKE} -C dtpanel clean
	@${MAKE} -C dtrun clean
	@${MAKE} -C dtfile clean
